### ISSUE TITLE
Saving an embedded record by itself leads to duplication of data

### ISSUE THREAD

**Issue by igorT** [firebase/emberfire#135]
We should tag embedded records when they are normalized with their full _ref so if they are saved by themselves we can save to the correct location. This will probably simplify the saveEmbeddedHasMany code as well

**Comment by tstirrat** [comment]
There is also an issue with rolling back (#95) we will need to ensure the dirty state is removed when saving the parent item, too.

**Comment by tstirrat** [comment]
Deleting records has the same problem, the delete happens at the top of the firebase tree, not at the embedded location.

**Comment by tstirrat** [comment]
Fixed in #249
