### ISSUE TITLE
Can't remove hasMany record

### ISSUE THREAD

**Issue by oskarrough** [firebase/emberfire#143]
Using emberfire 1.2.7, ember  I'm having trouble removing a record from a hasMany relationship. Adding works fine.

```JavaScript
// user model
playlists: DS.hasMany('playlist', { async: true }),
favoritePlaylists: DS.hasMany('playlist', { inverse: null, async: true })

// playlist model
tracks: DS.hasMany('track', { async: true }),
user: DS.belongsTo('user', { inverse: 'playlists', async: true })
```

```JavaScript
// get the user favorites
userFavorites: function() {
	return this.get('auth.user.favoritePlaylists');
}.property('auth.user.favoritePlaylists.[]'),

// add as favorite (WORKS)
this.get('userFavorites').addObject(this.get('model'));
this.get('auth.user').save();

// remove as favorite (DOESNT WORK)
this.get('userFavorites').removeObject(this.get('model'));
// userFavorites: <(subclass of DS.PromiseArray):ember786> 
this.get('auth.user').save();

// remove as favorite (ALSO DOESNT WORK)
this.get('userFavorites').then(function(favorites) {
	// <DS.ManyArray:ember768> 
	favorites.removeRecord(playlist);
	this.get('auth.user').save();
});
```

**Comment by njoshi22** [comment]
@oskarrough thanks for the workaround - this seems like fundamental functionality that the adapter should be handling

**Comment by oskarrough** [comment]
What would be great is a Emberfire documentation page explaining exactly what methods you need to call in order to CRUD models and relationships.

**Comment by sararob** [comment]
@oskarrough This is fixed in the latest release (see @tstirrat's PR #181). Now when you delete a record the associated `hasMany` links will be deleted. We'll also work on improving the documentation around relationships.

**Comment by oskarrough** [comment]
@sararob thank you. This is really great. Looking forward to all the updates.
