### ISSUE TITLE
embedded record deserialization depends on declaration order

### ISSUE THREAD

**Issue by nraynaud** [firebase/emberfire#150]
When declaring 2 embedded attributes with one pointing to the other, depending on the declaration order the deserialization can fail.
```javascript
   Operation = DS.Model.extend({
        outline: DS.belongsTo('shape', {async: true})
   });
   Shape = DS.Model.extend({
        definition: attr('string')
   });
   Job = DS.Model.extend({
        operations: DS.hasMany('operation', {embedded: true}),
        shapes: DS.hasMany('shape', {embedded: true})
   });
```
here in the Job, "shapes" and "operations" are in the wrong order, when de-serializing an Operation, the system will try to resolve its "outline" won't find it in the cache and try to go in a Shape table on the server and not find it.
the correct order is:
```javascript
   Job = DS.Model.extend({
        shapes: DS.hasMany('shape', {embedded: true}),
        operations: DS.hasMany('operation', {embedded: true})
   });
```

But the real solution is not to re-order the fields before de-serialization because Shape and Operation could be referencing each other, I think there is no way around a 2 steps loading (one step to de-serialize the embedded graph and one step to fix the pointers).

**Comment by tstirrat** [comment]
Since EmberFire 1.5.0 we use the `EmbeddedRecordsMixin` from Ember Data to handle embedded records. Can you confirm if this is still a problem? If so, you should raise an issue on [emberjs/data](https://github.com/emberjs/data/issues)
