### ISSUE TITLE
embedded async is not async

### ISSUE THREAD

**Issue by nraynaud** [firebase/emberfire#155]
I have an embedded+async hasMany attribute on my model, and the async is not respected.

Basically I represent each entity as a sub-graph under the user, akin to a document-oriented system. I do it that way to try to limit errors in the access control, since the language is very hard to use.
But when I display the list of documents to the user, the whole recursive content of all the documents is pulled instead of just the root node for each document.

**Comment by tstirrat** [comment]
`embedded: true` tells the adapter that your records are available immediately. Unfortunately, adding `async: true` does not do what you are expecting :( 

This is the same pattern for other ember data adapters. I don't believe the basic ActiveModelAdapter handles both flags at the same time either.

We may be able to re-visit this if we start adding deep link references for embedded records in #135

**Comment by tstirrat** [comment]
Lazy loading embedded records is out of scope of EmberFire. We only support embedded **or** async but not both.
