### ISSUE TITLE
Offline mode does not work

### ISSUE THREAD

**Issue by eibrahim** [firebase/emberfire#159]
I have this code

```
      newProject.save().then(function(){
        console.log('Save success');
        self.transitionToRoute('project.show', newProject.id);
      });
```

This works in offline, but the only problem is that the "then" callback never fires until i go back online.  Is this the correct behavior?  If so, what's the workaround?

**Comment by tstirrat** [comment]
There is no deliberate offline support in EmberFire yet. Offline "kind of works" in the sense that when you reconnect, data you saved will begin syncing back to the server. This is all handled by the underlying Firebase client library.

You'll also notice that things are not happy if you start your app when already offline.

We have not made a concerted effort to get Offline + EmberFire working yet.

**Comment by tstirrat** [comment]
As a point of clarification, the Firebase JS client does not call the callback immediately when in offline mode. Working around this could cause a problem when things come back online. I will do more investigation.

**Comment by xypaul** [comment]
Offline and EmberFire would make Firebase an even more incredible platform to work with. It would do the same thing Firebase has done to solve the real time problem. Also solving the offline problem, would make Firebase the ultimate killing two flies with one hit 'thing' :)

**Comment by adjohnson916** [comment]
+1

**Comment by tstirrat** [comment]
We do not plan support for this until full offline support is built into the Firebase library.
