### ISSUE TITLE
bower install issue with ember 1.8+

### ISSUE THREAD

**Issue by millisami** [firebase/emberfire#160]
When I bower install I get the following option.

```
Unable to find a suitable version for ember, please choose one:
    1) ember#1.7.x which resolved to 1.7.1 and is required by emberfire#1.3.1
    2) ember#1.8.1 which resolved to 1.8.1 and is required by tags
    3) ember#>= 1.7.0 which resolved to 1.8.1 and is required by ember-data#1.0.0-beta.12
    4) ember#> 1.5.0-beta.3 which resolved to 1.8.1 and is required by ember-resolver#0.1.10
    5) ember#>=1.4 <2 which resolved to 1.8.1 and is required by ember-cli-shims#0.0.3
    6) ember#^1.3.0 which resolved to 1.8.1 and is required by ember-qunit#0.1.8Prefix the choice with ! to persist it to bower.json
```
Since, I've ember 1.8.1 dependency, it will error out whatever ember version I choose.

**Comment by sararob** [comment]
@hussfelt @millisami @johnnyoshika this has been fixed with the latest release (1.3.2). We'll do our best to keep EmberFire up to date with the latest Ember and ED versions.

**Comment by johnnyoshika** [comment]
@sararob , this is fantastic!  Which version of Ember and ED does it support?

Thanks

**Comment by sararob** [comment]
@johnnyoshika it now supports Ember 1.9.x and ED 1.0.0-beta.12

**Comment by sararob** [comment]
Closing this issue since it's been resolved.

**Comment by johnnyoshika** [comment]
Hmmm, will it work with ED ED 1.0.0-beta.14?  I think it should, as there are deprecating changes, but I don't think there are any breaking changes:

http://emberjs.com/blog/2014/12/25/ember-data-1-0-beta-14-released.html
