### ISSUE TITLE
[DOCS] FirebaseSerializer

### ISSUE THREAD

**Issue by KirillSuhodolov** [firebase/emberfire#164]
Hello, guys.

Add please information about FirebaseSerializer to readme.

**Comment by tstirrat** [comment]
Hi Kirill,

We can definitely add some info to the [docs](https://www.firebase.com/docs/web/libraries/ember/api.html). Was there anything in particular you're looking for?

The `FirebaseSerializer` works similarly to the `JSONSerializer` except in the way it extracts embedded records.
