### ISSUE TITLE
Orphaned hasMany

### ISSUE THREAD

**Issue by raytiley** [firebase/emberfire#165]
Just throwing this out there so I don't forget, this might be an Ember Data issue and also might go away with all Ember Data work on relationships, however it may be unique to the way Firebase stores data.

Basically you can run into an issue where a hasMany relationship has a link to a record that has been deleted. Loading the record containing the hasMany will load that record into the store, but it can't be worked with properly since there is no corresponding root record.

Example that created this situation:

```js
App.Book = DS.Model.extend({
  title: DS.attr('string'),
  pages: DS.hasMany('page',)
});

App.Page = DS.Model.extend({
  content: DS.attr('string'),
  book: DS.belongsTo('book')
});
```

Ideally calling `destroyRecord` on a record would cleanup any links contained in hasMany relationships.

**Comment by sararob** [comment]
@raytiley I'm closing this as it's been fixed with @tstirrat's work in the latest release (1.3.3). Feel free to re-open if you're still having issues.
