### ISSUE TITLE
Fulfill promise with empty model instead of rejecting when 'record not found' (find, findAll)

### ISSUE THREAD

**Issue by bttf** [firebase/emberfire#172]
Currently, if you do a `find` with an ID that does not exist, the promise will be rejected and an error will be passed.

```
this.store.find('article', params.id).then(function(article) {

  // promise fulfilled

}, function(err) {

  // promise rejected; article not found

  // err.message ~= 'No record was found ...'

});
```

I think rejecting the promise implies that there were some errors with network connectivity, or syntax/parsing issues, i.e. problems with the actual request. 

If there was 'no record found', we can assume that the request itself was successful. I think fulfilling the promise would communicate that. Having the 'article' param set to null would effectively communicate that no record was found, e.g.:

```
this.store.find('article', params.id).then(function(article) {

  if (!article) {
    // successful request, no article found
  }

}, function(err) {
});
```

This is similar to a pattern commonly used with the mongoose library for node.js/mongodb.

I'd be happy to contribute when I have some time in the future; let this be a reminder for myself and an invitation for anyone interested. Any guidance would always be appreciated.

**Comment by sir-dunxalot** [comment]
I think this is a very important issue to address. It blocks some functionality. For example, checking to see if a user with a UID already exists in the Firebase before creating a new profile for them would be done like:

```
store.find('user', authData.uid).then(function(user) {
  if (!user) {
    _this.createUser(user, store).then(function(account) {
      resolve(authData);
    });
  } else {
    resolve(authData);
  }
});
```

Whilst this issue exists that functionality throws an error before running the callback after `then()`.

**Comment by stefanpenner** [comment]
fulfilling with `undefined`/`null` here is not a good idea, its extremely unclear if it is a programmer error or no content. HTTP missing a record === 404, pushing this into ember-data also works well. This should absolutely reject, with a explicit error.

```js
store.find('user', id).catch((reason) => {
  if (reason instanceof EmberFire.RecordNotFound) {
    // reason.id === id
    // raason.message === " Record <type> <id> was not found";
    // ...
  }
});
```

**Comment by tstirrat** [comment]
Rejecting when the record is not found is in line with ember-data conventions. There is a workaround in #146 for a "find or create" pattern.
