### ISSUE TITLE
Firebase onDisconnect cleanup

### ISSUE THREAD

**Issue by foxnewsnetwork** [firebase/emberfire#173]
The docs on the firebase site https://www.firebase.com/docs/web/api/ondisconnect/ has the handy onDisconnect method to clean up when a user dies.

Say I'm building some sort of chat room, how do I do something like: 

```coffeescript
userInRoom = room.get("users").addObject user
userInRoom.onDisconnect().remove()
```
Using the provided emberfire api?

**Comment by foxnewsnetwork** [comment]
Well, seeing as no one responded, I came with a possibly hacky solution to my need to register callbacks to firebase disconnecting:

First, an initializer to monkey-patch the DS store: initializers/firebase-store-monkeypatch.coffee
```coffeescript
`import DS from 'ember-data'`

# Takes two parameters: container and app
initialize = (ctn, app) ->
  DS.Store.reopen
    createRecord: (typeName, inputProperties) ->
      @registerFirecallsToRef @_super typeName, inputProperties

    push: (typeName, data, _partial) ->
      @registerFirecallsToRef @_super typeName, data, _partial

    registerFirecallsToRef: (record) ->
      adapter = @adapterFor record.constructor
      if adapter._getRef and record.firecalls and record.firecalls.onDisconnect
        ref = adapter._getRef record.constructor, record.get("id")
        record.firecalls.onDisconnect ref.onDisconnect()
      record

FirebaseStoreMonkeypatchInitializer =
  name: 'firebase-store-monkeypatch'
  initialize: initialize

`export {initialize}`
`export default FirebaseStoreMonkeypatchInitializer`
```
Now, I can register callbacks for onDisconnect in my DS.Model: models/peer.coffee

```coffeescript
`import Ember from 'ember'`
`import DS from 'ember-data'`

Peer = DS.Model.extend
  username: DS.attr "string"
  room: DS.belongsTo "room", async: true

  firecalls:
    onDisconnect: (ref) ->
      ref.remove()
  
`export default Peer`
```

**Comment by foxnewsnetwork** [comment]
For my use case, I also needed to call onDisconnect on hasMany relationships. I was unable to come up with a more "elegant" solution to this problem, so I just reopened the DS.Store again:

```coffeescript
DS.Store.reopen
  getFireRef: (record, relationKey, id) ->
      adapter = @adapterFor record
      throw new NotUsingFirebaseError(record) unless adapter._getRef?
      ref = adapter._getRef record.constructor, record.get("id")
      ref = adapter._getRelationshipRef ref, relationKey, id if relationKey and id
      ref
```
Using this, I was able to get the necessary child ref to call onDisconnect().remove() to handle firebase disconnection properly killing off crippled users...

But considering I was forced to call two obviously desired-to-be-private functions on adapter from the store, I highly doubt what I am doing can be considered canon. Please tell me how to do this properly, emberfire team (or if this is proper, please let me know and I will pull-request)

**Comment by tstirrat** [comment]
Hi fox,

Apologies for such a delay in responding, (I've since started at Firebase and have been looking through the backlog of issues). 

Thanks for taking the time to report your findings here. There really is no canonical `onDisconnect` pattern for EmberFire yet, but if you're still interested, let's discuss it more.

It seems like this is a good use case for accessing a model's reference directly. I think something like this might be a usable interface to achieve your goals:

```js
// modify single property
this.store.find('user', 'bob').then(record => {
  var ref = record.ref().child('lastOnline');
  ref.onDisconnect().set(Firebase.ServerValue.TIMESTAMP);
});

// remove a user from rooms user listing
this.store.find('room', 'chattypants').then(room => {
  var roomPresence = room.ref().child('connectedUsers/' + currentUser.get('id'));
  roomPresence.onDisconnect().remove();
});
```

Would something like that work?

I am thinking to expose the record's ref directly for a few reasons:

1. Model definition is not usually a good place to define application logic
  - These `onDisconnect` patterns seem to be more suited to a `session` service or `ApplicationRoute`
1. If defined as properties in the model definition, it would probably be difficult to provide a way to `.cancel()` your logic (or know when).

Let me know what you think :)

**Comment by jbrown** [comment]
@tstirrat Just wanted to chime in and say that I think your proposed solution sounds awesome. :+1:

**Comment by tstirrat** [comment]
@jbrown thanks for the feedback, and it should be relatively simple to implement

**Comment by foxnewsnetwork** [comment]
@tstirrat your argument makes a lot of sense, and, after trying to come up with a counter-example of a non-user-session use case of onDisconnect, I realized there really aren't any reasonable ones. The only argument I have is the usual apologetically engineering one of "leaky abstraction", but otherwise, I do agree, exposing ref is a good idea.

That being said, perhaps it'd also make sense to create make some sort of DS.Model extension, say a DS.FireSessionModel, that automatically kills itself and when an user disconnects. What do you folks think?

P.S.: no problemo on the late reply (I'm replying kind of late also), github doesn't send email alerts so it's sometimes hard to know when notifications come in.

**Comment by jbrown** [comment]
@foxnewsnetwork IMHO `DS.FireSessionModel` sounds like it would make a good mixin, but I'm not sure it belongs in the Emberfire framework itself.

**Comment by tstirrat** [comment]
You can now use `record.ref()` to achieve your `onDisconnect` needs. Available in `master`, see [the comment here](https://github.com/firebase/emberfire/issues/138#issuecomment-84148825) on how to use a branch.

We're getting the documentation ready and will make a release this week.
