### ISSUE TITLE
ref.once() cause data to be fetched twice

### ISSUE THREAD

**Issue by donovan-graham** [firebase/emberfire#177]
In my application and also in the blog example of this repo,  when calling to `this.store.find()`, firebase returns all the data twice. 

I've tracked it down to line 355 in emberfire.js where `ref.once` on the `findAll:` method isn't working as documented.  Changing this to `ref.on` instead make a single call and the data is fetched only once.

![emberfire_issue_once](https://cloud.githubusercontent.com/assets/1104135/6146747/8d3d38d0-b1f8-11e4-8b48-76e53cc6a6c7.jpg)

**Comment by tstirrat** [comment]
Thanks for the report :+1:

**Comment by tstirrat** [comment]
Clarification why this is happening: 
1. we first request the record(s) in `find`/`findAll` using `ref.once('value', ...)` ([link](https://github.com/firebase/emberfire/blob/d26632a734bfdc870eced86973755656980c7cbb/addon/adapters/firebase.js#L183))
2. Deserialized payloads are `store.push`ed ([link](https://github.com/emberjs/data/blob/v1.0.0-beta.14.1/packages/ember-data/lib/system/store.js#L1940))
3. Record `push` calls `recordWasPushed` which calls `adapter.listenForChanges` ([link](https://github.com/firebase/emberfire/blob/d26632a734bfdc870eced86973755656980c7cbb/addon/adapters/firebase.js#L125))
4. This calls `ref.on('value', ...)` to listen for changes, a side effect is that it requests the json a second time ([link](https://github.com/firebase/emberfire/blob/d26632a734bfdc870eced86973755656980c7cbb/addon/adapters/firebase.js#L155-L160))

Although this is inefficient, it would need a significant refactor to optimize. I have some ideas on how to do this, but it wont happen until after we get emberfire working with the snapshot changes in `beta.15+`
