### ISSUE TITLE
Doesn't work with Ember Inspector

### ISSUE THREAD

**Issue by sir-dunxalot** [firebase/emberfire#178]
Great work overall - really appreciate the work your team puts in.

**Issue**: When I go to the [Ember Inspector](https://chrome.google.com/webstore/detail/ember-inspector/bmdblncegkenkacieihfhpjfppoconhi) for an Emberfire app, the data tab in the inspector appears blank. The records are loaded in the store/app correctly. However, there seems to be some incompatibility.

**Screenshot**:

![inspector](https://cloud.githubusercontent.com/assets/4495352/6161026/e066423c-b238-11e4-95c5-11e69a2e508e.jpg)

**Comment by sararob** [comment]
@sir-dunxalot could you share the versions of Ember, ED, and EmberFire you're using?

**Comment by sir-dunxalot** [comment]
```
 DEBUG: -------------------------------
DEBUG: Ember             : 1.9.1
DEBUG: Ember Data        : 1.0.0-beta.12
DEBUG: EmberFire         : 1.3.2
DEBUG: Handlebars        : 2.0.0
DEBUG: jQuery            : 1.11.2
DEBUG: Ember Simple Auth : 0.7.2
DEBUG: -------------------------------
```

**Comment by jbrown** [comment]
@sir-dunxalot This might be a good place to start debugging. emberjs/ember-inspector#317

**Comment by tstirrat** [comment]
Can you please confirm if this is still happening with ember-data `beta.16.1` and EmberFire `1.4.4`? I have not seen this problem recently.

Also can you please temporarily disable any other addons you are using to make sure it is not related to that.
