### ISSUE TITLE
Ember fire does not seem compatible with HTMLBars

### ISSUE THREAD

**Issue by habdelra** [firebase/emberfire#180]
When using ember 1.9.1 and handlebars 2.0.0, ember fire does not seem to work. 

When handlebars 2.0.0 is used, the error "Error while processing route: index Unknown template object: function Error" appears in the console. 

It looks like handlebars ~1.3.0 in the bower.json is the last version of handlebars that ember fire works with. 

i saw this error with:

```
-------------------------------
Ember      : 1.9.1
Ember Data : 1.0.0-beta.12
EmberFire  : 1.3.2
Handlebars : 2.0.0
jQuery     : 1.11.2
-------------------------------
```

When I changed to the following the error went away:

```
-------------------------------
Ember      : 1.8.1
Ember Data : 1.0.0-beta.12
EmberFire  : 1.3.2
Handlebars : 1.3.0
jQuery     : 1.11.2
-------------------------------
```

The app was literally an ember CLI new installation with just one route/model hooked up to ember fire. (ember cli ver 0.1.12)

**Comment by tstirrat** [comment]
You need to do a few things to get Handlebars 2.x working. Following the guide [here](http://emberjs.com/blog/2014/10/16/handlebars-update.html)


```
npm uninstall --save-dev broccoli-ember-hbs-template-compiler
npm install --save-dev ember-cli-htmlbars@0.6.0
rm -rf bower_components
bower install --save handlebars#2.0.0
bower install --save ember#1.9.1
bower install
```

Note the version of ember-cli-htmlbars. You **must use 0.6.x** when using ember 1.9.x .. see the note [here](https://github.com/ember-cli/ember-cli-htmlbars):

> Handlebars 2.0 support has been removed. If you are using ember-cli-htmlbars with a 1.9.x project please continue to use ember-cli-htmlbars@0.6.x.

**Comment by habdelra** [comment]
Thanks! I'll give that a shot
