### ISSUE TITLE
Generator should generate an adapter if one is not present

### ISSUE THREAD

**Issue by tomdale** [firebase/emberfire#183]
Currently the setup instructions for EmberFire require you to manually create an `app/adapters/application.js` file and fill it in manually with your Firebase URL.

It would be much nicer if the generator could detect if you do not have an application adapter already (in my case, in a brand new project, I don't) and, in that case, prompt you for your Firebase URL and insert it automatically.

Also, I ran into some trickiness with the content security policy addon out of the box. It would be great if the generator could optionally modify your CSP policy to allow websocket connections to *.firebaseio.com.

**Comment by katowulf** [comment]
Thanks, Tom. We're working on some updates to EmberFire at present. I'll have @sararob add these to the discussion.

**Comment by sararob** [comment]
@tomdale We're working on improving the way EmberFire works with ember-cli this week. Check out the discussion in #120 and @tstirrat's ts-ember-cli-addon-refactor branch.

**Comment by tstirrat** [comment]
@tomdale some good points on the CSP and default adapter checking. Will definitely keep them in mind as I make enhancements

**Comment by tstirrat** [comment]
@tomdale see #196 

I'll look into the CSP stuff too before emberconf

**Comment by tstirrat** [comment]
Fixed in #196
