### ISSUE TITLE
embedded belongsTo is not correctly serialized.

### ISSUE THREAD

**Issue by nraynaud** [firebase/emberfire#200]
As stated in the README, embedded belongTo records need to have an 'id' property defined, but the serializer itself doesn't define this property when saving the record. When deserializing, we get the "Embedded relationship "%@" of "%@" must contain an "id" property in the payload".

I guess it's because of the [line 322 in updateRecord()](https://github.com/firebase/emberfire/blob/master/addon/adapters/firebase.js#L322)  where includeId is unconditionally set to false, but [this doc](http://emberjs.com/api/data/classes/DS.JSONSerializer.html#toc_ids) says that it should be true for creation and false for update.

This is mostly black magic to me, so I'm not sure I have understood the issue, I have just defined my own JSONSerializer to circumvent the issue for now:

        var ManualShapeSerializer = DS.JSONSerializer.extend({
            serialize: function (snapshot, options) {
                var json = this._super.apply(this, arguments);
                json.id = snapshot.id;
                return json;
            }
        });
       var Shape = DS.Model.extend({
            manualDefinition: DS.belongsTo('manualShape', {embedded: true}),
       });

**Comment by tstirrat** [comment]
Fixed in #249
