### ISSUE TITLE
Trouble compiling 

### ISSUE THREAD

**Issue by h55nick** [firebase/emberfire#217]
getting the following error:

```bash
Path or pattern "EmberFire/**/*.js" did not match any files
Error: Path or pattern "EmberFire/**/*.js" did not match any files
```

after following the [docs](https://www.firebase.com/docs/web/libraries/ember/guide.html#section-ember-add-firebase)
 
looked into the pathing and the example app and can't identify why this is happening.

bower specs:
```
    "handlebars": "~1.3.0",
    "jquery": "^1.11.1",
    "ember": "1.8.1",
    "ember-data": "1.0.0-beta.11",
... 
    "firebase": "~2.1.0"

```

**Comment by tstirrat** [comment]
Interesting.. what version of `ember-cli` is your project using?

```
$ cd project
$ ember --version

version: 0.2.0
node: 0.10.36
npm: 2.7.0
```

and what steps did you follow to install emberfire?

**Comment by h55nick** [comment]
```
version: 0.2.0
node: 0.10.36
npm: 2.7.1
```

After a fresh reboot and a cleaning/reinstall of npm/bower the error subsided (swear I did that multiple times before posting). Not sure what was up. This just goes to show I should be looking for a front-end dependency manger shortly! :trollface: 

Thanks for your quick response. Loving working with firebase!

**Comment by tstirrat** [comment]
Not a problem, it was potentially a npm cache problem. In future you can do this to clean out any badly cached packages:

```
npm cache clean
rm -rf node_modules
npm install
```

**Comment by h55nick** [comment]
yup. one of those situations where I feel frequently it's third times the charm unfortunately.

thanks again.

**Comment by tstirrat** [comment]
FYI, the missing files error also shows when using early `ember-cli` versions.

I've done a quick test and EmberFire 1.4.x works with `ember-cli` 0.1.13 and up.

**Comment by h55nick** [comment]
This would make perfect sense as I was upgrading from ~0.1.12 to 0.2.0

**Comment by tstirrat** [comment]
Thanks for the update :)

#219 should fix it to allow older versions. I'm still testing to work out exactly which versions :) Ideally, `0.0.43+`
