### ISSUE TITLE
.on('child_change') binding doesn't appear to be working properly in 1.4.0

### ISSUE THREAD

**Issue by dustinbrownman** [firebase/emberfire#221]
At least I think that's where the problem is. One of the best features of this library has been the automatic binding of the `.on('...')` event listeners. When an child is added on firebase, it automatically goes out to all devices connected. Same goes for when a child is removed, changed, or moved.

But when upgrading from 1.3.3 to 1.4.0, the child change part no longer works. Here's my app for demonstration:

![example of remove_child not working](http://i.gyazo.com/9e449f951bca7b36d8b0ca14a9f7f3ec.gif)

The two windows to the right are running the same version of my app. The only difference is the far right one is using emberfire 1.4.0, and the middle one is using 1.3.3. The screen to the left is being used to create and close a ticket (add and change a child).

As you can see, when a child is added, it appears on both version of the app. But when it is changed, it is only updated on the 1.3.3 version.

I'm stumped. I've dug into the `emberfire.js` as much as I feel comfortable, but it seems like it should be working. There's a chance that there's some gross oversight on my part. If so, I apologize, and feel free to set me straight.

If you think it might be an emberfire bug, and have an idea of where it might be, I'm willing to do some of the leg work on this (if you can point me in the right direction).

**Comment by dustinbrownman** [comment]
Just realized this may be being addressed in #141.

**Comment by tstirrat** [comment]
I'm assuming you've tried 1.4.2 and/or 1.4.3?

To clarify, are you using a `findAll` to get your "Queue" or is it a `store.filter` or a `hasMany` relationship from another parent model?

So for the sake of writing a test that captures this bug:
1. A new record created on the server appears in your list
2. Once it has appeared, it should receive property updates (<-- failing here)

Is this correct?

Does it receive **any** property changes at all, like the title, when you change in the firebase forge?

**Comment by tstirrat** [comment]
Also, any errors in the `console.log`?

**Comment by dustinbrownman** [comment]
Great questions. For clarity:

I thought 1.4.0 was the latest release. Just tried with 1.4.3 and have the same issue.

I'm using a standard `find` to get all of the "ticket" objects. So `this.store.find('ticket')`.

Yes, I believe that's where it breaks down. I can change properties in the forge and watch them change in the Ember inspector on the version using 1.3.3. But no property updates happen in 1.4.0 (or 1.4.3).

On the version that is working, I get a `Uncaught Error: Assertion Failed: calling set on destroyed object` error in the console, which is strange, but, I believe, unrelated.

Hopefully that adds more context. Thanks!

**Comment by tstirrat** [comment]
ah interesting. when you complete a task in these queues are you deleting the object locally with `model.deleteRecord` or `model.destroyRecord`?

**Comment by dustinbrownman** [comment]
Neither. I'm updating the `closed` property. And Then in the controller, I have a computed property called `tickets` that watches `'model.@each.closed'`.

**Comment by tstirrat** [comment]
thanks, should be enough to reproduce

**Comment by tstirrat** [comment]
What version of `ember-data` are you using, and does the problem persist with `beta.12`?

**Comment by dustinbrownman** [comment]
I'm using `beta.14.1`, but just tried it with `beta.12` with the same results.

**Comment by tstirrat** [comment]
ok, thanks for checking :)

**Comment by sararob** [comment]
@dustinbrownman I tried reproducing the issue here: https://github.com/sararob/emberfire-issue-221 but wasn't able to. Could you take a look and let me know if there's anything I'm missing? I'm using this demo Firebase url: https://issue-221.firebaseio-demo.com/.

**Comment by dustinbrownman** [comment]
@sararob Thank you so much for looking into this! I compared your implementation to mine and found one major difference: my ember-cli version was outdated (`0.1.13` I think). I upgraded to `0.2.3` and it worked!

While I feel silly, I think I saw a couple other people having the same issue, so I'm curious if upgrading would work for them. At any rate, thank you (and @tstirrat) so much!
