### ISSUE TITLE
Install failed. Could not find addon with name: emberfire

### ISSUE THREAD

**Issue by somlor** [firebase/emberfire#224]
I cannot install emberfire for some reason. 

Seeing error: __Install failed. Could not find addon with name: emberfire__

![emberfire-not-found](https://cloud.githubusercontent.com/assets/81008/6769604/1c143744-d07a-11e4-9032-fea1fd5d97d5.png)

Other addons are installing fine. 

Any ideas?

Thanks.

**Comment by tstirrat** [comment]
very strange. I thought it might be iojs, but i just installed iojs myself and it all works:

```
$ which node
/Users/tstirrat/.nvm/versions/io.js/v1.6.1/bin/node

$ ember new iojs
version: 0.2.0
installing
...

$ ember install:addon emberfire
version: 0.2.0
Installed packages for tooling via npm.
installing
  create app/adapters/application.js
Installing browser packages via Bower...
  cached git://github.com/firebase/firebase-bower.git#2.2.3
Installed browser packages via Bower.

EmberFire has been installed. Please configure your firebase URL in config/environment.js

Installed addon package.
```

**Comment by tstirrat** [comment]
Can you get `npm info` for the emberfire package?

```
npm info emberfire
```

Are you using some kind of cloud IDE? or npm in cached offline mode?

**Comment by tstirrat** [comment]
I think it's because your project name is `emberfire`. I had other issues once before when I had a project called `firebase` (it overwrite the `window.Firebase` object). However, in this case, calling your project `emberfire` will cause npm to not look globally for the real `emberfire` package.

please create an ember project with a different name and report back. :)

**Comment by somlor** [comment]
Wow, I just finally figured it out.

It's because I named my Ember app itself `emberfire`. 

![sheepish](https://cloud.githubusercontent.com/assets/81008/6770017/0884052e-d089-11e4-8b6b-0443e1c8df19.gif)

Naming collision is not unique to emberfire, e.g., I just tried `ember new torii && cd torii && ember install:addon torii` and same error.

**Comment by somlor** [comment]
Hah, nice, you beat me by 20 seconds. :)

**Comment by tstirrat** [comment]
:)

**Comment by somlor** [comment]
Thanks for your help @tstirrat

**Comment by constantm** [comment]
This issue just saved me a lot of time. :D
