### ISSUE TITLE
ember data 1.0.0-beta.15 DS.Snapshot.get() is deprecated

### ISSUE THREAD

**Issue by foxnewsnetwork** [firebase/emberfire#226]
The good folks at ember-data has decided to deprecate some of the API on the Snapshot, this means:

```javascript
// addon/serializers/firebase.js
serializeHasMany: function(record, json, relationship) {
    var key = relationship.key;
    var payloadKey = this.keyForRelationship ? this.keyForRelationship(key, "hasMany") : key;
    json[payloadKey] = Ember.A(record.get(key)).mapBy('id'); // this line is bad
  },
```
requires some updating. 

Ember itself spits out the following two deprecation warnings:
```
DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead.
```
and
```
DEPRECATION: Using DS.Snapshot.get() is deprecated. Use .attr(), .belongsTo() or .hasMany() instead.
```
Although I assume there is no shortage of engineers at google firebase who can fix this, I can make the upgrades and pull request if no one is already on it.

**Comment by jshao17** [comment]
Think a lot of things needs to be updated. ember-cli just released 0.2.1 with ember data bumped to 1.0.0-beta.16 and things didnt seem to be working in the 2 minutes I was playing around with it.

**Comment by tstirrat** [comment]
Hey, I've been in the midst of diagnosing a relationships bug right now. I'd absolutely love a PR with `15+` snapshot support. We really need to make sure it's backwards compatible.

I have a plan to use a modified technique like in the [ef4/liquid-fire](https://github.com/ef4/liquid-fire) repo to have travis test against multiple `ember-data` versions. I will try to get this merged ASAP.

**Comment by tstirrat** [comment]
see #229

**Comment by tstirrat** [comment]
There seem to be more issues than just deprecation warnings in `ember-data` 14+. I was seeing issues when rendering `hasMany` relationships. A ghost/duplicate view appears at the end of the list after something is added on the server. Even though the list shows 1 too many items, the relationship's `.length` reports a correct count!

I'd recommend people stick to `beta.12` until we can diagnose what's going on here.

**Comment by xypaul** [comment]
Thanks @tstirrat, looking forward to the fixes.

**Comment by foxnewsnetwork** [comment]
It's just deprecation warnings in 15, in 16 all hell breaks loose and you start getting "snapshot.get" is null. Replacing the .get with the appropriate .id, .hasMany, or .belongsTo allows things to mostly work again... until I run the tests, then deleteRecord for the belongsTo relationships gets borked. My hypothesis is that, due to the recent ember data overhaul of DS.Snapshot, the adapter is getting a wrong type and just sort of running with it.

In any case, the deprecation warnings were just the tip of the iceberg, this beast might be trickier to tame than I originally thought.

**Comment by ivohanke** [comment]
@tstirrat this would help me a lot...

**Comment by tstirrat** [comment]
I've sorted out most of the issues and will raise a PR on this today.

Just to manage everyones expectations, even after 16.1 support stops throwing errors, a lot of testing needs to be done to check that relationships are all still working properly. As I mentioned before, 15+ is showing some weird ghosted views on when rendering `hasMany` relationships.

**Comment by tstirrat** [comment]
PR is here: #234

**Comment by tstirrat** [comment]
EmberFire to 1.4.4 has landed with `beta16+` support

**Comment by foxnewsnetwork** [comment]
hooray :+1:

**Comment by ivohanke** [comment]
Great, thank you Tim!
