### ISSUE TITLE
Cannot get a very simple .save() to work?

### ISSUE THREAD

**Issue by constantm** [firebase/emberfire#231]
I'm still very new to Ember, and I'm using Emberfire to play around with it. I can't seem to save a very simple model. When invoking save() in the model, it results in a `Uncaught TypeError: undefined is not a function` error on line 334 of firebase.js - which is the following line of code: 

`var serializedRecord = record.serialize({includeId:false});`

Any ideas what may be causing this?

Some debug info:
```
ember.debug.js:3975DEBUG: -------------------------------
ember.debug.js:3975DEBUG: Ember      : 1.10.0
ember.debug.js:3975DEBUG: Ember Data : 1.0.0-beta.16
ember.debug.js:3975DEBUG: Firebase   : 2.2.3
ember.debug.js:3975DEBUG: EmberFire  : 1.4.3
ember.debug.js:3975DEBUG: jQuery     : 1.11.2
ember.debug.js:3975DEBUG: -------------------------------
```

```
// clients/new.js

import Ember from 'ember';

export default Ember.Controller.extend({
	actions: {
		saveClient: function(){
			var newClient = this.store.createRecord('client', {
				clientName: this.get('clientName'),
				clientEmail: this.get('clientEmail')
			});
			newClient.save();
			this.setProperties({
				clientName: '',
				clientEmail: ''
			});
		}
	}
});
```

```
// models/client.js

import DS from 'ember-data';

export default DS.Model.extend({
    clientName: DS.attr('string'),
    clientEmail: DS.attr('string')
});
```

**Comment by tstirrat** [comment]
Hey, please downgrade your `ember-data` to `1.0.0-beta.12` for now. `beta.15` changed the way serialization works and I am working on updating emberfire to support it.

**Comment by tstirrat** [comment]
I forgot to mention, you'll need to downgrade it in both `package.json` and `bower.json`.

**Comment by constantm** [comment]
Okay will do, thanks! I'll keep this open for now.

**Comment by tstirrat** [comment]
PR has been created to support beta 16: #234

**Comment by tstirrat** [comment]
for others coming to this issue, you can downgrade with these commands:

```
npm install --save-dev ember-data@1.0.0-beta.12
bower install --save ember-data#1.0.0-beta.12
```

**Comment by tstirrat** [comment]
You can now upgrade emberfire to 1.4.4 in `package.json` to fix this.
