### ISSUE TITLE
Installing addon with ember-cli 0.2.3 causes 'ember generate' error

### ISSUE THREAD

**Issue by bttf** [firebase/emberfire#236]
Starting a new project with ember-cli v0.2.3 and installing the emberfire add-on will produce this output:

```
$ ember install emberfire
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Installed packages for tooling via npm.
installing
  identical app/adapters/application.js
Installing browser packages via Bower...
  cached git://github.com/firebase/firebase-bower.git#2.2.3
Installed browser packages via Bower.

EmberFire has been installed. Please configure your firebase URL in config/environment.js

installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.
```

**Comment by tstirrat** [comment]
Thanks for the heads up.

I think this could be a bug in `ember-cli`. We are overriding `normalizeEntityName` in [our blueprint](https://github.com/firebase/emberfire/blob/v1.4.4/blueprints/emberfire/index.js#L11-L15) which has been sufficient up until now.

Also, when you re-run `ember g emberfire` you do not see the warning anymore.

The base prototype method which [shows that warning](https://github.com/ember-cli/ember-cli/blob/v0.2.3/lib/models/blueprint.js#L314-L316) seems only to be called on addon install and not when running `ember generate`
