### ISSUE TITLE
everything stop working if referential integrity breaks (relation to a non-existing record)

### ISSUE THREAD

**Issue by nadeemkhedr** [firebase/emberfire#240]
let me explain by showing the following scenario 

There is two collections `users` & `todos`, the `user` has multiple `todos` if there is a relation to a non-existing record (for an example if a `user` has a relation to a non-existing `todo`) the ember app just stops working

``` plain
users
  simplelogin:1
    name: "nadeem"
    todos
      firstTodoId: "true"
      secondTodoId: "true"

todos
  firstTodoId
    name: "my first todo"
```

This is not a normal case, this should not happen (I know), but if it does & it did in a couple of times during testing, the app stops functioning at that point

can't emberfire ignore records like these instead of just crashing, how can we handle this scenario on our end

**Comment by tstirrat** [comment]
Thanks for the report.

I'll need to see what the standard Ember Data way of handling this is and see how we can stop breaking the rest of the app.
