### ISSUE TITLE
Uncaught Error: Could not find module firebase-app/app

### ISSUE THREAD

**Issue by 20v100** [firebase/emberfire#244]
Hello,

Just installed Emberfire on a new project using Ember-CLI v0.2.3 and got this error: 

     Uncaught Error: Could not find module firebase-app/app

I installed firebase with this command (as required by the v0.2.3)
      
     ember install emberfire

I'm not sure how to fix this issue. Emberfire is working on my other app that use Ember-cli v0,2.2.

**Comment by tstirrat** [comment]
the command changed in 0.2.3 to `ember install emberfire`

**Comment by 20v100** [comment]
My bad. I did install emberfire with ` ember install emberfire`. I corrected my comment above. I re-installed emberfire several times. Still the same error.

**Comment by tstirrat** [comment]
sometimes there is a name collision with the project name. e.g. you will get lots of problems if your ember-cli project name is either `firebase` or `emberfire` (because these module names are used internally)

I tried to replicate your issue but mine was successful. What else are you doing that I am not doing?

```
$ ember new firebase-app
version: 0.2.3
installing
  create .bowerrc
  ...
Installed packages for tooling via npm.
Installed browser packages via Bower.
Successfully initialized git.

$ cd firebase-app

$ ember install emberfire
version: 0.2.3
Installed packages for tooling via npm.
installing
  create app/adapters/application.js
Installing browser packages via Bower...
  cached git://github.com/firebase/firebase-bower.git#2.2.4
Installed browser packages via Bower.

EmberFire has been installed. Please configure your firebase URL in config/environment.js

$ cat package.json | grep emberfire
    "emberfire": "1.4.4"

$ ember build
version: 0.2.3
Built project successfully. Stored in "dist/".
```

Perhaps reinstall your global ember-cli:

```
npm uninstall -g ember-cli
npm cache clean
npm install -g ember-cli
```

**Comment by tstirrat** [comment]
Any update on this? Can you post your global `ember-cli` version?

**Comment by 20v100** [comment]
Sorry for the delay. I will try to troubleshoot tomorrow and get back to you. tks

**Comment by 20v100** [comment]
@tstirrat: I re-installed ember-cli and emberfire. I got the following error and installing emberfire: 

    The `ember generate` command requires an entity name to be specified. For more details, use `ember help`. 

Here is the extract of the command line:
    Caction@mkf2-219362:~/workspace/mkfc(master*)$ ember install emberfire                                                                                                                                                         
    Future versions of Ember CLI will not support v0.10.26. Please update to Node 0.12 or io.js.
    version: 0.2.3
    Could not find watchman, falling back to NodeWatcher for file system events.
    Visit http://www.ember-cli.com/#watchman for more info.
    Installed packages for tooling via npm.
    installing
      identical app/adapters/application.js                              
    Installing browser packages via Bower...
      cached git://github.com/firebase/firebase-bower.git#2.2.4
    Installed browser packages via Bower.

    EmberFire has been installed. Please configure your firebase URL in config/environment.js                                        
    installing
    The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.
    action@mkf2-219362:~/workspace/mkfc(master*)$  

Further to your comments, I'm not using emberfire name in other areas of my application. I did however, re-recreated this project from an older version of the project by copying the old code into the new project. Could a name conflict be created by this operation.

This project is in an IDE. I can give you access if this can help.

**Comment by tstirrat** [comment]
So the emberfire error is a ember-cli bug: #236 

> I did however, re-created this project from an older version of the project by copying the old codes into the new project. Could a name conflict be created by this operation?

Yep! check your `modulePrefix` in `config/environment.js` matches your `name` in `package.json`

It is looking for `firebase-app` as your module prefix but this doesn't appear to be the prefix that all your app modules are generated with.

**Comment by tstirrat** [comment]
also look across your project for anywhere that is saying to import from `firebase-app/` and correct it to your real modulePrefix.

**Comment by 20v100** [comment]
@tstirrat: I will close this issue. I created a brand new project instead and started from scratch (The former project was more for testing purpose). If the error repeat. I will follow the above instruction. Thanks for your help!

**Comment by medinasod** [comment]
In case someone stumbles upon this...
I was getting this error after using Ember CLI v.1.13.13 to install Emberfire:

`Could not find module 'emberfire/adapters/firebase'`

I was able to resolve by stopping the local server and running `ember build`.

When I restarted the local server the error went away.

**Comment by gthapar** [comment]
Stumbled upon this error today.. basically you just need to restart ember server. No need to run `ember build`.
