### ISSUE TITLE
Expose testing helpers

### ISSUE THREAD

**Issue by tstirrat** [firebase/emberfire#251]
Expose the internal testing helpers so that others may use them in integration/acceptance tests.

Something like the following should be possible:

```js
var application, mockRef;

module('Acceptance: User listing', {
  beforeEach: function() {
    application = startApp();
    mockRef = createFirebaseMockRef(MY_FIXTURE_DATA);
    overrideAdapterRef(application, mockRef, 'user');
    // this is effectively setting the adapterFor('user')._ref
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
  }
});

test('user online status is updated', function(assert) {
  var userId = 'someuserid';
  var userRef = mockRef.child('users').child(userId);
  
  visit('/users');
  // and password
  andThen(() => {
    // test some user state is online
  });
  andThen(() => {
    return userRef.child('status').set('offline');
  });
  andThen(() => {
    // test that the user state is 'offline'
  });
});
```

**Comment by tstirrat** [comment]
We should also look at using [MockFirebase](https://github.com/katowulf/mockfirebase) instead of the offline reference.

**Comment by brancusi** [comment]
+1

**Comment by aceofspades** [comment]
:+1:

**Comment by scolyer** [comment]
:+1:

**Comment by tstirrat** [comment]
@edborden re your comment in #344, how are you testing the firebase related stuff? [mockfirebase](https://github.com/katowulf/mockfirebase), using offline refs like I [do](https://github.com/firebase/emberfire/blob/master/tests/helpers/stub-firebase.js) [here](https://github.com/firebase/emberfire/blob/master/tests/helpers/create-test-ref.js), or using real firebase instances for test code?

Thinking out aloud here.. I suppose mockfirebase is the way to go for simple test cases.. but exposing helpers for offline refs will be necessary for some complex operations, like queries (which mockfirebase [does not do](https://github.com/katowulf/mockfirebase/pull/61))

**Comment by edborden** [comment]
@tstirrat I'm currently using real firebase instances for test code, haven't experimented yet with libraries for offline testing. Definitely willing to jump on a best practices train, though, and contribute where possible along the way.

**Comment by tstirrat** [comment]
@edborden great, good to know.

I need to figure out how to expose es6 modules for test-only builds.

**Comment by edborden** [comment]
@tstirrat I believe that anything placed in `test-support/` in the add-on will get merged into `tests/` in the consuming application. So emberfire's `test/helpers/` going into `test-support/helpers` would be an easy first step.

Aptible has a shared module they are using across their apps that is a great in-production example. Here's the [shared module](https://github.com/aptible/ember-cli-aptible-shared) with their test code and [an app that consumes it](https://github.com/aptible/dashboard.aptible.com).

**Comment by tstirrat** [comment]
@edborden thanks, was trying to find an example. I'll get on this
