### ISSUE TITLE
emberfire not working with ember-data beta 18

### ISSUE THREAD

**Issue by mohrt** [firebase/emberfire#254]
When I try to delete a record:

message.destroyRecord();

 I get:

this.store.recordWillDelete is not a function

Using emberfire 1.4.4

This is inside the controller action where this.store exists.

[edit] emberfire line 817, I comment out this line and the problem goes away.
//this.store.recordWillDelete(this);

**Comment by tstirrat** [comment]
OK, thanks I will look into it

**Comment by mohrt** [comment]
just noting, when I delete a record it is not updating the view on other open browser windows, just the one I click delete on. The firebase db is getting the delete.

**Comment by mohrt** [comment]
I  fixed the error, but the delete on remote browser still does not get the update.

https://github.com/mohrt/emberfire/commit/fdc03b9b8166c03ddd9e6a6fbc97cfe3ce604bce

**Comment by tstirrat** [comment]
yeah its strange, there are two different stores and one of them does not have the emberfire extensions. I've seen this before but fixed it a least one other time. #213

**Comment by tstirrat** [comment]
are you using ember-cli or including the emberfire js manually?

**Comment by mohrt** [comment]
I'm implementing manually.

**Comment by mohrt** [comment]
Sure enough, I applied your patch and that seems to fix the issue. changing 'store' to 'ember-data'

**Comment by tstirrat** [comment]
oh wow, I thought that patch was already in 1.4.4

I guess I need to release 1.4.5 asap, thanks for bringing this to my attention

**Comment by mohrt** [comment]
Those instructions for ember-cli are outdated too, instead of:

    ember install:addon emberfire

should be

    ember install emberfire

**Comment by tstirrat** [comment]
We just released emberfire 1.4.5 which fixes this issue. Thanks for the note on the install command too, I'll get that updated asap.

**Comment by tstirrat** [comment]
Dupe of #213 
Fixed in #241
