### ISSUE TITLE
Error message does not give indication to problem

### ISSUE THREAD

**Issue by brandonjmckay** [firebase/emberfire#265]
I'm getting errors on saving one of my models. This is likely from importing a bunch of data I exported from a Postgres database, but everything is displaying, and I can access the relations attached to the models.

I'm getting:

```
Error: Some errors were encountered while saving mystics@model:interpretation: 26
```

and the line the error message comes from is:

```
if (rejected.length !== 0) {
            var error = new Error(fmt('Some errors were encountered while saving %@ %@', [type, record.id]));
                error.errors = rejected.mapBy('reason');
            reject(error);
          } else {...
```

Not sure how to debug this, as it doesn't give me too much information on where to begin looking.

**Comment by brandonjmckay** [comment]
Seems to be coming from [here](https://github.com/firebase/emberfire/blob/a99f2867eb1886b04d4cd5e61e18c229ab332664/addon/adapters/firebase.js#L383)

**Comment by tstirrat** [comment]
you'll need to look into `error.errors` which should contain an array of strings (or **Error** objects)

```js
record.save()
  .then(...)
  .catch(e => {
    console.log(error.errors);
  });
```

**Comment by tstirrat** [comment]
I can probably add some logic here so that if there is only one error it will surface a single error.

**Comment by brandonjmckay** [comment]
Cool. I was able to guesstimate what my problem was in this case, lucky!
I had a field that was an array, in my model I was doing:

```
tags: DS.attr(),
...
```

Which Firebase barfed at. So my personal issue is fixed.

That is great information, @tstirrat. Thanks. I'll make sure to do that in future.

**Comment by tstirrat** [comment]
Great, glad you cleared it up!

**Comment by psrivongse** [comment]
@brandonjmckay What did you do to fix your issue? I'm also having an issue saving an array to Firebase.
