### ISSUE TITLE
findQuery (orderBy) not working

### ISSUE THREAD

**Issue by oskarrough** [firebase/emberfire#268]
Hi, I'm having trouble querying records by a property.

```js
model() {
	return this.store.filter('channel', {
		orderBy: 'isFeatured',
		equals: true
	}, (channel) => {
		return channel.get('isFeatured');
	});
}
```

The filter at the end makes sure only featured channels are returned but the query still returns all channels, featured or not. Any ideas?

I'm on ember and data 1.13.2 with emberfire https://github.com/firebase/emberfire/commit/0b919fa060022a09ef5925e3068bc2e6b4a06856

**Comment by tstirrat** [comment]
it seems filter is deprecated and moving to https://github.com/ember-data/ember-data-filter

It's probably because of that.. but I'll look into it to see if something else broke in the recent PR merge

**Comment by tstirrat** [comment]
This seems to work for me in Ember 1.13.2 + Ember Data 1.13.2

Using query + `equalTo`:

```js
return this.store.query('channel', {
  orderBy: 'isFeatured',
  equalTo: true
});
```

or filter:

```js
return this.store.filter('channel', {
  orderBy: 'isFeatured',
  // equalTo: true
}, (channel) => channel.get('isFeatured'));
```

**Comment by tstirrat** [comment]
With both of those options I can toggle the `isFeatured` flag on items and the array auto updates

**Comment by oskarrough** [comment]
Both work here as well. I messed up the syntax with `equals` instead of `equalTo`. Sorry about that and thanks for the examples!

**Comment by tstirrat** [comment]
no problem, glad it's working :zap:
