### ISSUE TITLE
EmberFire Login helpers

### ISSUE THREAD

**Issue by katowulf** [firebase/emberfire#270]
We intend to absorb https://github.com/MattMSumner/torii-fire into emberfire and fix up any missing features and documentation.

**Comment by tstirrat** [comment]
#256

**Comment by Ghostavio** [comment]
this is amazing, how is it going?

**Comment by tstirrat** [comment]
torii fire is integrated, docs are online :) https://www.firebase.com/blog/2015-07-28-emberfire-1-13-0.html

**Comment by Ghostavio** [comment]
awesome
