### ISSUE TITLE
Dynamic routes not updated in real-time

### ISSUE THREAD

**Issue by bjones6** [firebase/emberfire#271]
I have single flat routes with a model returning this.store.find("something", params.something_id);

And the models don't update, while this.store.find("something"); will update in real time.

Any quick fixes?

**Comment by tstirrat** [comment]
Can you provide an example? We have several tests to ensure single models receive property updates from the server.

I might not understand the extent of the problem

**Comment by bjones6** [comment]
Certainly:

With the following ember router:

```javascript
  this.route('main', {path: '/'});
  this.route('honeybee', {path: '/:list_id'});
  this.route('lavender', {path: '/:list_id/:todo_id'});
```

this route:

```javascript
model: function(params) {
	return this.store.find('list', params.list_id);
},
```

and,

```javascript
model: function(params) {
	return this.store.find('todo', params.todo_id);
},
```

do NOT receive real time updates. However if they are refreshed they will receive updated models.

while:
```javascript
model: function() {
	return this.store.find('list');
},
```

will receive update models in real time.

Any ideas? Please let me know if more info would be helpful.

**Comment by tstirrat** [comment]
That's odd! can you provide your ember/ember-data/emberfire versions?

**Comment by bjones6** [comment]
Sorry for the delay,

Relevant package.json:
```json
"devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "0.2.3",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-cordova": "0.0.17",
    "ember-cli-dependency-checker": "0.0.8",
    "ember-cli-font-awesome": "0.0.9",
    "ember-cli-foundation-sass": "^1.1.1",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.10",
    "ember-cli-sass": "^3.1.0",
    "ember-cli-uglify": "1.0.1",
    "ember-cli-zero-clipboard": "^1.0.2",
    "ember-data": "1.0.0-beta.16.1",
    "ember-export-application-global": "^1.0.2",
    "ember-linkify": "^1.2.2",
    "ember-localstorage-adapter": "^0.5.3",
    "ember-masonry-grid": "0.4.1",
    "ember-moment": "1.2.1",
    "emberfire": "^1.4.4",
    "grunt": "^0.4.5",
    "liquid-fire": "0.19.4",
    "sendgrid": "^1.8.0"
  }
```

**Comment by tstirrat** [comment]
I tried to make a minimal test and it seems to be working here:

My versions:

```
DEBUG: -------------------------------
DEBUG: Ember      : 1.12.0
DEBUG: Ember Data : 1.0.0-beta.18
DEBUG: Firebase   : 2.2.7
DEBUG: EmberFire  : 1.4.7
DEBUG: jQuery     : 1.11.3
DEBUG: -------------------------------
```

Code:

```js
// routes
Router.map(function() {
  this.route('post', { path: '/post/:post_id' });
});
```

```js
// models/post
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  body: DS.attr('string')
});
```

```js
// routes/post
import Ember from 'ember';

export default Ember.Route.extend({
  model(params) {
    console.log('loading model...');
    return this.store.find('post', params.post_id);
  }
});
```

```hbs
<h1>{{model.title}}</h1>

{{model.body}}
```

with these settings I can edit the data [here](https://emberfire-issue-271.firebaseio-demo.com/) and it updates in my UI.

**Comment by tstirrat** [comment]
If you can still reproduce it, please send me a link to a jsbin or a repo that demonstrates the error.

**Comment by bjones6** [comment]
Unfortunately I can't provide further insight into this because we decided to make the switch to angular. I've fought many frameworks but Ember was likely one of the worst, and angularfire (one of several reasons for the switch) is a delight to work with.
