### ISSUE TITLE
Passing classes to store methods has been removed

### ISSUE THREAD

**Issue by 20v100** [firebase/emberfire#272]
Hello,

Just updated to Ember-Data 1.13 and Ember 2.0.0-beta-1 and for the following error:

   `Uncaught Error: Assertion Failed: Passing classes to store methods has been removed. Please pass a dasherized string instead of krc@model:user:`

After investigation, I think the error is between Ember-Data and Ember-Fire.

My code is: 

`return this.store.findAll('user').then(function(user) {... ``

**Comment by tstirrat** [comment]
Please use the `master` branch for ember data `1.13.x` compat. (see #138 for how to use a branch)

Duplicates #261 

See also #267

**Comment by tstirrat** [comment]
Reopening for visibility

**Comment by IsaiahJTurner** [comment]
Could you explain what your message above means? The latest release version doesn't work?

**Comment by tstirrat** [comment]
I am reopening this issue so that it is clear it is a known issue and we don't get [more](https://github.com/firebase/emberfire/issues/261) [duplicates](https://github.com/firebase/emberfire/issues/288).

We are working on the EmberFire 1.13.x compatible release. The code is done, the documentation is being reviewed now.

Use `master` branch until we do that:

```
ember new app
cd app
ember install firebase/emberfire#master
```

**Comment by IsaiahJTurner** [comment]
Ahh, thank you! For some reason I was thinking the latest release was master.

Does this mean anything to you? It looks like something is expecting an array and not getting one. It might be a personal code issue, not a EmberFire issue; I'll keep looking into it.
<img width="896" alt="screen shot 2015-07-27 at 1 51 02 pm" src="https://cloud.githubusercontent.com/assets/3732588/8913349/8f826110-3466-11e5-8872-b9e00c2d6090.png">

**Comment by tstirrat** [comment]
Looks like it's going through the JSON-API serializer.. we dont use that for emberfire (we are based off the JSONSerializer).

Check if you have a serializer in `app/serializers/application.js` or  `app/serializers/<model>.js`

If you do have one, usually you just want to delete the file and let emberfire use the default. If you have some need for a custom serializer, make sure it extends from the right one:

```js
// app/serializers/post.js
import FirebaseSerializer from 'emberfire/serializers/firebase';

export default FirebaseSerializer.extend({
});
```

**Comment by tstirrat** [comment]
1.5.0 is released :)
