### ISSUE TITLE
app/adapters/emberfire.js does not get created during installation

### ISSUE THREAD

**Issue by notmessenger** [firebase/emberfire#286]
I am running Ember CLI 1.13.1, Ember 1.13.3, Ember Data 1.13.5 and installed the master branch via `ember install firebase/emberfire#master`.  Once I added this file into my local `node_modules` folder installation all began working as expected.  I haven't had a chance yet to dig into what specifically is causing the problem but at least wanted to raise awareness of the issue.

**Comment by tstirrat** [comment]
hey, `app/adapters/emberfire.js` should not be created. it should be `app/adapters/application.js`

The file should be created when you run `ember g emberfire`.

Is this not happening?

**Comment by notmessenger** [comment]
I have tried re-creating this problem with a new project but haven't been able to.  If I run into this again I'll research and post, if appropriate.
