### ISSUE TITLE
master branch not saving hasMany relationship

### ISSUE THREAD

**Issue by sir-dunxalot** [firebase/emberfire#287]
I have a hasMany relationship on a model:

```js
// models/feature.js

export default DS.Model.extend({
  stages: DS.hasMany('stage', {
    async: true
  }),
});
```

```js
// models/stage.js
export default DS.Model.extend({
  feature: DS.belongsTo('feature', {
    async: true
  }),
});
```

I am creating stages and setting them on a feature. The stages array exists on the feature client-side. However, it is not persisted to the Firebase DB.

This is how I am saving the models:

```
  save() {
    this.get('model').save().then(function(feature) {
      feature.get('stages').forEach(function(stage) {
        stage.save();
      });
    });
  },
```

Here is how the feature model appears in the Firebase DB:

![image](https://cloud.githubusercontent.com/assets/4495352/8769306/232efe78-2e68-11e5-862b-3833afb46ed3.png)

One would expect an array of stages to be persisted to the feature model.

The stage model persists as expected:

![image](https://cloud.githubusercontent.com/assets/4495352/8769350/2417140a-2e69-11e5-8d8c-d1abcac6f31c.png)

Is there something obviously wrong here or could this be a bug on master branch?

- Ember 1.13.2
- Ember Data 1.13.5
- Emberfire master branch

**Comment by tmayr** [comment]
Having the same issues, seems like updateRecords isnt serializing the records properly.

**Comment by tstirrat** [comment]
Thanks for the report, will do some testing and work out what's wrong.

**Comment by sir-dunxalot** [comment]
Thanks, Tim. Also, to confirm the error is not existent with Ember fire `1.4.7` and ED `beta.18`.

**Comment by tstirrat** [comment]
ok, I figured out what this is.

It's ember-data JSONSerializer's `_shouldSerializeHasMany` returns `false` on `manyToOne` relationships

**Comment by sir-dunxalot** [comment]
Thanks for looking into it, Tim. is there something we should do in apps to mitigate this or is it likely to be solved by either ED or Emberfire in an upcoming release?

**Comment by tstirrat** [comment]
I have a fix ready, just creating a breaking test to ensure this issue doesn't pop up again.

**Comment by tstirrat** [comment]
Let me know if an updated master fixes your issue.

Reopen this issue if you still have problems :)

**Comment by sir-dunxalot** [comment]
Looks like that fixed it. Thanks a lot!
