### ISSUE TITLE
Custom Login Support

### ISSUE THREAD

**Issue by IsaiahJTurner** [firebase/emberfire#293]
When I try to use Torii with "custom" I get a pop up that directs me to https://auth.firebase.com/v2/APP-NAME/auth/custom?&v=js-0.0.0&transport=popup&suppress_status_codes=true

**Comment by tstirrat** [comment]
eek, yep this is a bug. It should pass through to `authWithCustomToken`, not the oauth popup.

**Comment by tstirrat** [comment]
Thanks for the report :cake:

**Comment by sararob** [comment]
@IsaiahJTurner could you try it from my `sr-torii-fix` branch and let me know if you run into any issues?

```
"devDependencies": {
  ...
  "emberfire": "firebase/emberfire#sr-torii-fix",
  ...
}
```

**Comment by tstirrat** [comment]
This is now in `master`

**Comment by IsaiahJTurner** [comment]
See PR #298.
