### ISSUE TITLE
Transaction Support

### ISSUE THREAD

**Issue by IsaiahJTurner** [firebase/emberfire#297]
I'll try working on this myself but wanted to discuss the best way to go about it. Ember itself doesn't seem to have a good way to implement this feature unless we extend the object model; adding a `transaction` method. This is a duplicate of #93 but that issue was closed instead of being marked as an enhancement. The conversation on that issue is also very off topic. Apologies if opening a new issue was the incorrect course of action, feel free to close this one and open the other one if desired.

Requested flag: enhancement

Relevant: https://www.firebase.com/docs/web/api/firebase/transaction.html

**Comment by tstirrat** [comment]
This could be difficult without lower level support in ember-data. What sort of API were you thinking?

**Comment by IsaiahJTurner** [comment]
I am relatively new to Ember so this could make no sense at all but potentially having a FirebaseModel that extends DS.Model.

``DS.Model.extend({
  transaction: transaction(updateFunction, [onComplete], [applyLocally]) // piggy backing off the Web API
});
```

The main issue I see with this is that it's asynchronous unlike `set`.

**Comment by tstirrat** [comment]
The asynchronicity of it shouldn't matter too much, when the record is updated via the transaction the changes will come back through the `on('value')` hook and update the model.

Can you give some examples on how one would use this?

For the record, we now provide a `record.ref()` method which allows you to get the reference to the model. From here you can use transactions:

```js
var votesRef = record.ref().child('votes');

votesRef.transaction(function(votes) {
  if (votes === null) {
    return 1;
  } else {
    return votes + 1;
  }
}, function(error, committed, snapshot) {
  if (error) {
    console.log('Transaction failed abnormally!', error);
  } else if (!committed) {
    console.log('We aborted the transaction');
  }
},
false // don't apply the update, in case the transaction fails (e.g. a security rule fails)
);
```

**Comment by jamesdaniels** [comment]
Going to close, since this isn't supported in the Ember-data world + there is a work around.
