### ISSUE TITLE
Monkeypatch of store.push broken

### ISSUE THREAD

**Issue by wolfbiter** [firebase/emberfire#299]
versions:
![image](https://cloud.githubusercontent.com/assets/1360563/9023600/a8580614-3857-11e5-821c-4437090a11a6.png)

error:
![image](https://cloud.githubusercontent.com/assets/1360563/9023602/b26098a6-3857-11e5-89e7-bc79eeea53f5.png)

breaking code (see highlighted line corroborated by error above):
![image](https://cloud.githubusercontent.com/assets/1360563/9023608/0aa04520-3858-11e5-9d19-21d512bdc976.png)

emberfire push source: https://github.com/firebase/emberfire/blob/bd0fc460236b6b32e41d5a079cbe9f7377fa838f/addon/initializers/emberfire.js#L25

ember store.push source:
https://github.com/emberjs/data/blob/v1.13.7/packages/ember-data/lib/system/store.js#L1810

**Comment by wolfbiter** [comment]
love emberfire - please LMK if i can provide more info or if I'm doing something wrong...

**Comment by tstirrat** [comment]
Thanks for the report :)

Can you give me the original arguments sent to `push` in the debug trace listed above?

I am guessing it was not a JSON-API formatted payload, but want to be sure.

**Comment by wolfbiter** [comment]
![image](https://cloud.githubusercontent.com/assets/1360563/9028570/f2812118-3932-11e5-8930-65113ef4c90a.png)

to be honest, i'm really not sure what's going on here >.< is that sufficient?

**Comment by tstirrat** [comment]
Thanks, thats perfect :)

**Comment by wolfbiter** [comment]
@tstirrat so i played around with it a bit, and got it to stop breaking - i think this was just a false positive from weird behaviour...

specifically, i had one model which was breaking. it was defined with (among other things) `DS.Model.extend(Ember.MutableArrayMixin)`. i removed the mixin from the definition and it works fine. not sure what collision caused the issues, but at least seems isolated to my case.

**Comment by tstirrat** [comment]
Ah, thanks for the update! I was trying to reproduce and wasn't able to get `record` to be a string value as seen in your debugging state in the original post.
