### ISSUE TITLE
Embedded child records get added twice

### ISSUE THREAD

**Issue by nosli** [firebase/emberfire#301]
On the save the new child record get added to the store again. 

```javascript
// controllers\crimeapp.js
addCrime: function() {
			var newCrime = this.store.createRecord('crime',{
				title: 'testCrime'
			});
			this.get('model.crimes').pushObject(newCrime);
			newCrime.save()
}
```
workaround is to reload the content. 
```javascript
// controllers\crimeapp.js
addCrime: function() {
			var newCrime = this.store.createRecord('crime',{
				title: 'testCrime'
			});
			this.get('model.crimes').pushObject(newCrime);
			
			var _this = this;
			newCrime.save().then(function() {
				_this.get('content').reload();
			});
		}
```
Maybe this is more related to Ember-data? HTMLBars gives an error that the ids are not unique, to prevent that error you can do this in the template:

    {{#each model.crimes key="@index" as |crime|}}
     {{crime.title}}<br>
     {{/each}}

**Comment by tstirrat** [comment]
Do you mean that the child record (newCrime) now appears twice in the `hasMany` array?

**Comment by nosli** [comment]
Yes, after I add and save one child the ```model.crimes.length``` states 2.
In the backend everything is stored correctly. 

After the ```_this.get('content').reload();``` model.crimes is correct.
I am using **embedded** child records by the way(!)

I am using these versions:
Ember      : 1.13.3
Ember Data : 1.13.7
Firebase   : 2.2.9
EmberFire  : 1.5.0

**Comment by courthead** [comment]
The same is happening to me:

Ember: 1.13.6
Ember Data: 1.13.7
EmberFire: 1.5.0

**Comment by eibrahim** [comment]
The same is happening to me:

Ember: 1.13.8
Ember Data: 1.13.8
EmberFire: 1.5.0

**Comment by benedikt-d** [comment]
Same with:
Ember: 1.13.8
Ember Data: 1.13.9
Ember Fire: 1.5.0

After reloading the page it is there only once.
Only the direct response after calling the save method is that the data is there twice.

**Comment by roosnic1** [comment]
Same with:
Ember: 1.13.7
Ember Data: 1.13.8
Firebase: 2.2.9
EmberFire: 1.5.0

Do you have a ETA for the fix?

**Comment by andrejunges** [comment]
Same with: 
Ember      : 2.2.0
Ember Data : 2.2.0
Firebase   : 2.3.2
EmberFire  : 1.6.0
jQuery     : 2.1.4

**Comment by adjohnson916** [comment]
+1 Same with:
```
"ember-cli": "1.13.8",
"ember": "~1.13.10",
"ember-data": "~1.13.15",
"emberfire": "^1.6.0",
```

Agreed with @nosli that it's resolved after a call to `reload()` after `save()` on an instance of has many relationship, though mine is async. Unfortunately in the interim, there are two duplicate records locally.

**Comment by tstirrat** [comment]
This appears to be due to the fact that the child record is new and you are saving it directly. We have some detection logic that determines if a record is embedded, and it may not be working correctly on records that are new and unsaved locally.

Adding the new child record to the relationship and then saving the parent, should stop the record from duplicating locally.

**Comment by 20v100** [comment]
Is this related to https://github.com/emberjs/data/issues/1829 ?

**Comment by tstirrat** [comment]
Does the embedded child appear twice in the firebase db?

Does it appear once under the root of the db at /crimes/:id and another time embedded inside the intended parent object?

Need to know if this is also a db data saving problem.

**Comment by nosli** [comment]
In the firebase db the data is stored correctly, so nothing wrong there. It got embedded in the right place. 

It's like Ember sees it as two different entities within it's own store. (After a refresh the duplicate disappears)

**Comment by tstirrat** [comment]
ok, thanks for the clarification. this is the same issue as emberjs/data#1829 

Can you confirm if you have better luck by saving only the parent record. (it will cascade and save the child automatically)?

**Comment by nosli** [comment]
No saving the parent/root after the added embedded child does not change
the behavior. (it still gets added twice)

2015-12-04 21:45 GMT+01:00 Tim Stirrat <notifications@github.com>:

> ok, thanks for the clarification. this is the same issue as
> emberjs/data#1829 <https://github.com/emberjs/data/issues/1829>
>
> Can you confirm if you have better luck by saving only the parent record.
> (it will cascade and save the child automatically)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firebase/emberfire/issues/301#issuecomment-162077463>.
>



-- 
Met vriendelijke groet,

Nordin Slimati

Nosli ICT Direct

**Comment by tstirrat** [comment]
Thanks for the clarification. I've [seen this sort of thing before](http://discuss.emberjs.com/t/proposal-fix-saving-new-embedded-records-creates-duplicates/3677) and it's related to how Ember Data handles relationships with local changes and new changes coming from the server..

Use the reload workaround for now, while I see what can be done when saving embedded relationships.

**Comment by 20v100** [comment]
The `.reload()` workaround did not for me. I'm using the below in the meantime:

    link.save().then(link => {
      this.store.unloadRecord(_link);
      this.store.findRecord('link', _link.id);
    });

Issue is that the user can see the record being add twice and then removed from the template a second after. I may have to create further logic to insure that the template do not show the same record twice. Looking foward for a better option.

**Comment by tstirrat** [comment]
Can you try the branch in #337 and see if it exhibits the same ghosting? The branch there writes embedded records in a totally different way. I wonder if it is more or less resilient.

Would love to get some testing on real user problems rather than my synthetic test apps.

**Comment by 20v100** [comment]
I plan to give it a try over the weekend if I can figure out to "try the branch" (my knowledge of git is very basic...)

**Comment by tstirrat** [comment]
This comment should outline how to do it: https://github.com/firebase/emberfire/issues/138#issuecomment-84148825

**Comment by Znegl** [comment]
Getting the same bug:
Saving new embedded hasMany records results in duplicate content in the frontend. One if the items in the frontend is marked as isNew.

Ember : 2.3.0
Ember Data : 2.3.3

**Comment by tstirrat** [comment]
This is related to emberjs/data#4149
