### ISSUE TITLE
Firebase.update failed: First argument contains undefined in property

### ISSUE THREAD

**Issue by jpadilla** [firebase/emberfire#303]
I'm getting the following error which has been a bit hard to debug.

```
"Firebase.update failed: First argument contains undefined in property 'previews.708e43a2-607a-4fa6-9d7d-e333dded9791.layers.__nextSuper'"
```

Model:
```javascript
import Ember from 'ember';
import DS from 'ember-data';

var attr = DS.attr;
var computed = Ember.computed;

export default DS.Model.extend({
  layers: attr('raw'),
  url: attr(),
  status: attr()
});
````

Raw Transformer
```javascript
import DS from 'ember-data';

export default DS.Transform.extend({
  deserialize: function(serialized) {
    return serialized;
  },

  serialize: function(deserialized) {
    return deserialized;
  }
});
```
Any ideas what might be going wrong?

**Comment by tstirrat** [comment]
Thanks for the report, I will get a chance to look at this tomorrow.

**Comment by tstirrat** [comment]
Seems like there are two things happening here:

1. It looks like you are getting the extra prototype properties on your `layers` object. I am assuming that `__nextSuper` is not something you added manually.

2. The underlying Firebase library throws an error when you try to update a property with the value of `undefined`. It will allow `null` (and will essentially ignore them).

You'll need your raw transformer to ensure that it ignores all prototype methods and properties and converts `undefined` to `null` or removes any properties with with `undefined` values altogether.

You'll also want to update your transform to allow for when the entire `layers` property is not defined:

```js
  serialize: function(deserialized) {
    return deserialized || null;
  }
```

**Comment by Sirajamd** [comment]
+1

**Comment by Adarshsingh2k** [comment]
Uncaught Error: Reference.set failed: First argument contains undefined in property 'messages.-MGUlN85Tfz2LvMqYXr5.message'
    at oe (validation.ts:145)
    at validation.ts:204
    at Rt (util.ts:417)
    at oe (validation.ts:185)
    at Kt (validation.ts:122)
    at Li.set (Reference.ts:137)
    at saveMessage (form.js:57)
    at HTMLFormElement.submitForm (form.js:37)

whats wrong with this
