### ISSUE TITLE
Embedded relationships not loading

### ISSUE THREAD

**Issue by IsaiahJTurner** [firebase/emberfire#309]
Consider the following data set of Livestreams accessed at `super-fire410.firebaseio.com/livestreams`

```javascript
{
  "-34345dsasdf": {
    "duration": 21,
    "viewers": {
      "-12234fssdf": {
        "lastSeen": "Tue Sep 01 2015 11:29:33 GMT-0400 (EDT)"
        }
      }
    },
    "-54345sddgss": {
      "duration": 10,
      "viewers": {
        "-45324ffsdf": {
        "lastSeen": "Tue Sep 01 2015 11:10:33 GMT-0400 (EDT)"
      }
    }
  }
}
```

with Livestream defined as

```javascript
import DS from 'ember-data';

export default DS.Model.extend({
  duration: DS.attr('number'),
  viewers: DS.hasMany('viewer', { embedded: true })
})
``` 

and Viewer defined as

```javascript
import DS from 'ember-data';

export default DS.Model.extend({
  lastSeen: DS.attr('date')
})
```

The expected behavior is for the viewers to be populated when accessed. But instead an error is thrown.

> Uncaught Error: Assertion Failed: You looked up the 'viewers' relationship on a 'livestream' with id -34345dsasdf but some of the associated records were not loaded. Either make sure they are all loaded together with the parent record, or specify that the relationship is async (`DS.hasMany({ async: true })`)

Any ideas why this is?

**Comment by tstirrat** [comment]
After EmberFire 1.5.0 (due to the underlying Ember Data "new serializer API") you should not define `embedded: true` on the model anymore.

Instead, you need to configure embedding via a serializer ([see the docs on embedded relationships](https://www.firebase.com/docs/web/libraries/ember/guide.html#section-relationships)): 

1. define the `viewers` attribute in the model as `async: false`

    ```js
    // app/models/livestream.js
    import DS from 'ember-data';

    export default DS.Model.extend({
      duration: DS.attr('number'),
      viewers: DS.hasMany('viewer', { async: false })
    });
    ```
2. create a serializer and configure the `livestream` attribute to be embedded:
    
    ```js
    // app/serializers/livestream.js
    import FirebaseSerializer from 'emberfire/serializers/firebase';
    
    export default FirebaseSerializer.extend({
      attrs: {
        viewers: { embedded: 'always' }
      }
    });
    ```

**Comment by tstirrat** [comment]
Closing for now, feel free to reopen if you find any problems.
