### ISSUE TITLE
Snapshot.serialize is not a function

### ISSUE THREAD

**Issue by bradcypert** [firebase/emberfire#311]
Hello Firebase team and friends!

I'm trying to use EmberFire for the first time and am running into a small issue.
![Console Error](http://i.imgur.com/vh2yLFb.png)

This error is being raised when I call the following action
```
actions : {
    saveArticle: function(){
      let data = {
        content: this.get('model').body,
        keywords: this.get('keywords'),
        description: this.get('description'),
        title: this.get('name'),
        timestamp: new Date().getTime(),
        status: 'PUBLISHED'
      };
      console.log(data.content, data.name);
      if(data.content === "" || data.title.toString() === "" || data.title.toString() === "<!---->"){
        console.log('TODO: Cant save empty content');
      } else {
        let article = this.store.createRecord('article', data);
        console.log(article);
        article.save();
      }
    }
  }
```

And here is my model...

```
import DS from 'ember-data';

export default DS.Model.extend({
  title: DS.attr('string'),
  content: DS.attr('string'),
  timestamp: DS.attr('number'),
  organizationId: DS.attr('number'),
  authorId: DS.attr('number'),
  description: DS.attr('string'),
  status: DS.attr('string')
});
```

Any idea what's causing this issue? Package.json is as follows...
https://gist.github.com/bradcypert/cd47809d8347e7b638ff

Thanks so much in advanced for your help!

**Comment by tstirrat** [comment]
Hey, thanks for the report, can you list your library versions which show in the browser console?

I think this might be a mismatch between emberfire and ember-data. `snapshot` doesn't have a `serialize` method for ember-data versions below `beta.15`

**Comment by bradcypert** [comment]
Yup. Turns out that was a pretty goofy mistake on my end!

Thanks @tstirrat !
