### ISSUE TITLE
Not able to access content array in model hook after a findAll

### ISSUE THREAD

**Issue by tyleriguchi** [firebase/emberfire#314]
The mapBy should be returning the records after the find to the server, but getting the content results in an empty array. If I log the content property I can see the returned models but if I run a debugger I can see that the content property is empty. Not sure what's going on here. I'm running Ember 1.13.7, Ember Data 1.13.8, and EmberFire 1.5.0
```
model() {
  return this.store.findAll('news-feed').then ( (newsFeeds) => {
      return newsFeeds.get('content').mapBy('record').sort(function(a, b) {
        return moment(a.get('formattedDate')).isBefore(moment(b.get('formattedDate')));
      })
  })
}
```

**Comment by tyleriguchi** [comment]
Looked into the content array more, apparently not meant to be accessed, so there's an issue in my code. https://github.com/emberjs/data/issues/3604

**Comment by tyleriguchi** [comment]
Never mind, looks like I'm still running into issues when trying to access it by converting it into an array. In the controller:
```
newsFeeds: Ember.computed('model', function() {
    return this.get('model').toArray()
  },
```
return nothing. If I then use the Ember inspector to get the property, it returns an array with the expected models.

**Comment by tyleriguchi** [comment]
Needed to have a computed over the array
```
newsFeeds: Ember.computed('model.[]', function() {
    return this.get('model').toArray()
  },
```

**Comment by tstirrat** [comment]
I'm glad you sorted it out.

And, thanks for posting the solution back in the issue so that others can find it!

**Comment by psrivongse** [comment]
I'm having the same issue, however @tyleriguchi 's workaround did not work in my case.

Using 
```
this.store.query(modelName, {})
```
produces desired results, however, the 'query' part does not work as intended in Ember and returns everything.
