### ISSUE TITLE
Serializer deprecation

### ISSUE THREAD

**Issue by SirZach** [firebase/emberfire#316]
Hey all, just wondering if anyone else is getting this as it's making up most of my deprecation warnings...
```
Ember Inspector (Deprecation Trace): Your custom serializer uses the old version of the Serializer API, with `extract` hooks. Please upgrade your serializers to the new Serializer API using `normalizeResponse` hooks instead.
```

I'm running Ember 1.13.10, Ember-Data 1.13.8 and Emberfire 1.5.0.

Thanks!

**Comment by tstirrat** [comment]
It sounds like you have files in the `app/serializers/`directory that are probably not needed anymore. Do you have anything there?

If you are only using EmberFire, you can remove the `app/serializers/application.js` file or any other files in the folder.

**Comment by SirZach** [comment]
@tstirrat you can check out the serializers I have here - https://github.com/SirZach/bbbbbbbbbbbbbbb/tree/master/app/serializers but in summary, I have two serializers that extend the Firebase serializer to declare embedded records and one serializer that extends the RestSerializer since that model doesn't user Firebase

**Comment by tstirrat** [comment]
If you remove the RESTSerializer for `card` does the deprecation warning go away? I think this will be related to that and the warning will go away in future versions of ember data.

**Comment by tstirrat** [comment]
I am certain this is not to do with our serializer. If you think otherwise please provide a [MCVE](http://stackoverflow.com/help/mcve)
