### ISSUE TITLE
Model in after model hook isn't resolved

### ISSUE THREAD

**Issue by tyleriguchi** [firebase/emberfire#317]
When the afterModel hook is hit, the model hook hasn't resolved the find method.
```
model () {
    return this.store.findAll('news-feed')
  },
  afterModel(newsFeed) {
    return newsFeed.forEach( model => {
      ...
    })
  },
```
When trying to loop over the content of newsFeed, there aren't any models loaded. After the page has been rendered, the models are loaded into the store. Seems like the model hook is resolving before the models are finished loading into the store.

**Comment by SirZach** [comment]
I'm seeing the same behavior. 
```
DEBUG: -------------------------------
ember.debug.js:5378DEBUG: Ember      : 1.13.7
ember.debug.js:5378DEBUG: Ember Data : 1.13.8
ember.debug.js:5378DEBUG: Firebase   : 2.3.0
ember.debug.js:5378DEBUG: EmberFire  : 1.5.0
ember.debug.js:5378DEBUG: jQuery     : 1.11.3
ember.debug.js:5378DEBUG: -------------------------------
```

**Comment by theworkerant** [comment]
Thirded.

**Comment by lmerriam** [comment]
Same, model in afterModel is blank, then records load in afterwards

**Comment by tgreiser** [comment]
This behavior was working correctly under versions:

    "ember": "1.13.5",
    "ember-data": "1.13.7",

**Comment by tstirrat** [comment]
This will be fixed with #335 . I will make a release today

**Comment by lmerriam** [comment]
:+1:

**Comment by tstirrat** [comment]
1.6.2 is out
