### ISSUE TITLE
patch of ember data store to enable push events causes error in acceptance tests

### ISSUE THREAD

**Issue by remkoboschker** [firebase/emberfire#318]
When running acceptance tests with the async helpers, the following error is triggered

``Uncaught Error: Assertion Failed: You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run``

The source appears to be the ember data store patch to enable push events. 

https://github.com/firebase/emberfire/blob/master/addon/initializers/emberfire.js

It needs the run loop that is not available during testing. Wrapping the async helpers does not help.

In the test I visit a route that has a model that does a query.

````
export default Ember.Route.extend({
  model(params) {
    return Ember.RSVP.hash({
      thing: this.store.query('things', { orderBy: 'name', equalTo: params.thing_name })
        .then(list => list.get('firstObject')),
      otherThing: this.store.query('otherThings', { orderBy: 'name', equalTo:  params.otherThing_name })
        .then(list => list.get('firstObject'))
    });
  }
});
````
Any thought on preventing the error?

**Comment by gabrielgrant** [comment]
I'm running acceptance tests and not seeing this error. Can you show the context of the failing test?

**Comment by remkoboschker** [comment]
@gabrielgrant Hi, I have had to abandon the firebase based project due to issues with privacy regulation in the eu. If I get around to the issue again. I'll include more context. Thank you.
