### ISSUE TITLE
Async doesn't tell the adapter to fetch the record if it hasn't already been loaded

### ISSUE THREAD

**Issue by rmmpaderes** [firebase/emberfire#324]
DEBUG: -------------------------------
    DEBUG: Ember      : 2.1.0
    DEBUG: Ember Data : 2.1.0
    DEBUG: Firebase   : 2.3.1
    DEBUG: EmberFire  : 1.6.0
    DEBUG: jQuery     : 1.11.3
    DEBUG: -------------------------------

Reading the docs from [here](https://www.firebase.com/docs/web/libraries/ember/guide.html#section-relationships). It's said that: *Any relationship that is flagged as async: true tells the adapter to fetch the record if it hasn't already been loaded*.

I have the following models:

    // app/models/room.js
    export default DS.Model.extend({
      name: DS.attr('string'),
      messages: DS.hasMany('message')
    });

and

    // app/models/message.js
    export default DS.Model.extend({
      content: DS.attr('string')
    });

I didn't declare the `async: true` in my room model since I believe that in Ember Data 2.x, all relationships are async by default.

Now, when I do a `this.store.findAll('room')` it's only returning the room model. I would need to do `this.get('room').get('messages')` to further load the message model itself.

The behavior that I'm getting is what I'd really expect (and what I'd like too) from Ember Data, but the statements in the docs is not inline with what's happening. So I'm not sure if this is a bug or just a wrong documentation. Am I missing something here?

I think it's important to know because if we're only be able to fetch the async model by **only** explicitly asking for it then I guess there would be one less reason to follow the [best practice](https://www.firebase.com/docs/web/guide/structuring-data.html) of flattening out the data structure since this will avoid the scenario of *iterating over "rooms" to get a list of names requires potentially downloading hundreds of megabytes of messages*.

**Comment by tstirrat** [comment]
> Now, when I do a this.store.findAll('room') it's only returning the room model. I would need to do this.get('room').get('messages') to further load the message model itself.

That is the expected `async: true` behaviour. So, it looks like we need to update our documentation to be more clear. Thanks for the feedback. :cake: 

Is something like this a little bit more clear:

---

Relationships flagged with `async: true` instruct EmberFire to fire off a second request to look up the related records independently. This will not happen until you request the contents of the relationship.

```js
this.store.findRecord('post', 'post_1').then(function (post) {
  post.get('comments').then(function (comments) {
    // comments can be accessed here
  });
});
```

**Comment by rmmpaderes** [comment]
Yes. That's better IMO.

Though I just wanted to note that I may have been a little to hasty when I said that this would be one less reason to follow the best practice of flattening out data. In Ember, I guess you can get away of not flattening your data but if you have an Android or iOS app that uses the same DB, I think flattened data is the way to go.

**Comment by tstirrat** [comment]
ok cool, I will get this updated in the docs, thanks
