### ISSUE TITLE
Use new Firebase mult-location writes for Emberfire relationships

### ISSUE THREAD

**Issue by gabrielgrant** [firebase/emberfire#326]
The extra manual tracking that Emberfire requires around relationships is a real footgun. Now that [multi-location atomic writes are supported](https://www.firebase.com/blog/2015-09-24-atomic-writes-and-more.html) it seems Emberfire should make use of those to just automatically update both sides of a relationship following some variation of [the fan-out pattern.](https://www.firebase.com/blog/2015-10-07-how-to-keep-your-data-consistent.html)

**Comment by tstirrat** [comment]
Similar to #304 

I think the solution is to just write the  model payload + relationships array in one step.

**Comment by gabrielgrant** [comment]
Yes, I was specifically talking about writing both sides of the relationship without requiring a `save()` call on each model. It's pretty explicit in the [relevant Ember docs](http://guides.emberjs.com/v2.1.0/models/working-with-relationships/#toc_updating-existing-records) that this isn't supposed to be required, and I read somewhere recently that this was one of the reasons Emberfire was ruled out for a new intro-to-ember tutorial. (I can't seem to find that discussion at the moment, I'll update with the link if I come across it again)

**Comment by tstirrat** [comment]
Please do, if you can find the link.

In regards to saving on both sides. As far as I know, the standard REST adapters do no do this automatically.

What is often happening is that the relationship is stored on the server in only one direction and a single save is all that is needed. This same functionality also works in EmberFire -- it auto reconciles the relationships locally when only one side is defined. However, if you define it on both sides you need to save it on both sides.

**Comment by gabrielgrant** [comment]
I believe you're right that the standard REST adapters don't automatically, explicitly save both sides, but as I understand it, the difference is that they assume that if the relationship gets saved on one side, then it will automatically appear when (re)fetching the other side (as would generally be the case with a standard relational backend). Firebase isn't doing this bi-directional linking for us, so to simulate this  behavior requires the client to write to both locations.

Hope that makes (some) sense? :)

**Comment by tstirrat** [comment]
I agree this could help with relationships but it is not something I'm actively working on. PRs welcome. As I stated in #147, the edge cases and interplay with Ember Data's internal relationship reconciliation might get tricky.

**Comment by adjohnson916** [comment]
+1

**Comment by alexparker** [comment]
+1, any update here?

**Comment by jamesdaniels** [comment]
Closing in favor of #366
