### ISSUE TITLE
Relationships getting saved first before the direct attributes

### ISSUE THREAD

**Issue by rmmpaderes** [firebase/emberfire#327]
Using **Ember Data v2.1.0** and **EmberFire v1.6.0**

I have the following models:

    // app/models/post
    export default DS.Model.extend({
      title: DS.attr('string'),
      tags: DS.hasMany('tag')
    });

    // app/models/tag
    export default DS.Model.extend({
      name: DS.attr('string'),
      posts: DS.hasMany('post')
    });

When I do:

    let tag = this.store.createRecord('tag', {
      name: 'Funny'
    });

    let post = this.store.createRecord('post', {
      title: 'This is a funny post',
      tags: [tag]
    });

    tag.save().then(() => {
      post.save();
    });

What's happening is that the tag and post will have a transaction on Firebase to save the record with a relationship attribute only. Then immediately, another transaction will happen that will save the non-relationship (*name* for tag model and *title* for post model) attributes.

This makes security rules such as `".write": "!data.exists()"` where we only want to allow creating (no edit) of post and tag records not work since when the second transaction to add the non-relationship attributes comes around, the data already exists which causes permission denied error.

**Comment by adjohnson916** [comment]
+1 Having the same issue here.

**Comment by adjohnson916** [comment]
@rmmpaderes Found any solutions yet?

**Comment by rmmpaderes** [comment]
@adjohnson916 I only did a workaround in terms of the security in Firebase. Like for my case above where we only want to allow creating of data, my security will allow to write if *(data doesn't exist) or (data exists but the non-relationship attributes doesn't exist yet)*.

Here's a sample rule for tags in my example above:

`".write": "!data.exists() || ( data.exists() && !data.hasChild('name') )"`

Will be a pain to maintain for sure. The best solution I guess would be to change up Emberfire to save everything in a single call but I'm not sure if saving relationships and non-relationships in separate calls was designed intentionally or not. Maybe @tstirrat can shed some insights?

**Comment by tstirrat** [comment]
That decision was made before my time and no one has argued a case to keep that functionality. I plan to update the adapter to write in a single payload.

**Comment by adjohnson916** [comment]
@tstirrat Great if there are plans to change it! We're running into this issue in an app getting closer to production deadline now. Let us know if you'd like help, and if so what ideas you might have.

**Comment by tstirrat** [comment]
I've been working on a branch to solve this ( [serialize-relationships-atomic](https://github.com/firebase/emberfire/tree/serialize-relationships-atomic) ). There is still one remaining error with embedded record dirty states that I need to tackle.

Unfortunately there isn't a well established API to set a record to "clean".

**Comment by BrianTMaurer** [comment]
+1
