### ISSUE TITLE
Introduction to emberfire at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [firebase/emberfire#342]
Hi there, would you someone familiar with the project would be open to giving an "Introduction to emberfire" lightning talk at an upcoming Global Ember Meetup in the beginning of next year? We'll edit the video and give you video that you can embed into the addon's README. You can see an example of other introduction videos here https://vimeo.com/album/3607049

The talk usually covers:
1. What's use case for the addon?
2. How to get stated using it?
3. What should the user be aware of?

What do you think?

**Comment by tstirrat** [comment]
Hey Taras,

At this point we don't have much free time. But it is something that I think we could revisit in the new year :). I've forwarded on the request to our developer relations team.

**Comment by taras** [comment]
Cool, thank you :)
