### ISSUE TITLE
Install fails on ember-cli 2.x

### ISSUE THREAD

**Issue by mphasize** [firebase/emberfire#346]
The peerDependency in package.json is currently set to `"ember-cli": ">=1.13.1"`, which leads `ember install emberfire` to fail with `The package ember-cli@2.2.0-beta.1 does not satisfy its siblings' peerDependencies requirements!`.

Can this potentially be fixed with just updating the dependency?
Or did the addon integration change so much that more work is needed here?

**Comment by tstirrat** [comment]
I have not tried it with 2.0 beta. It seems strange that 2.0 doesnt satisfy `>=1.13.1`. Can you create a test repo with this problem so I can look further?

**Comment by Cryrivers** [comment]
I tried installing `emberfire` with `ember-cli@2.2.0-beta.1` and failed as well. Will any screenshots help?

**Comment by Cryrivers** [comment]
@tstirrat the `-beta.1` part in `2.2.0-beta.1` makes it not satisfy constraint `>=1.13.1`.

**Comment by Kuzirashi** [comment]
Same error here. I tried everything but I always get:

~~~
npm WARN EPEERINVALID emberfire@1.6.3 requires a peer of ember-cli@>=1.13.1 but none was installed.
~~~

**Comment by brownie3003** [comment]
I have the same problem

**Comment by tstirrat** [comment]
Please use `ember install firebase/emberfire#master` for now

**Comment by ksnyde** [comment]
@tstirrat that command doesn't work but if I take you less literally ... you can get it to work by using `npm install` instead of `ember install`

**Comment by tstirrat** [comment]
interesting. the repo#branch format of the `ember install` command usually works.

**Comment by ksnyde** [comment]
@tstirrat out of interest have you had #master successfully interact with ember-data 2.3.0? I was getting problems with the store and seeing as I haven't seen chatter on this issue just wondering if it might be Firebase/emberfire related.

**Comment by tstirrat** [comment]
@ksnyde it's related to torii. can you try the branch in #353 and let me know if that fixes it?
