### ISSUE TITLE
store.query question

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#351]
@tstirrat et al. - This may be simple but I couldnt find in the documentation.

I am using the following:
```
    let filterText = this.get('filterText');
    return this.store.query('company', {
      name: filterText
    });
```

If ```filterText``` is "rub"  I want to return both of the following:

...name: "scrub brush"
...name: "rubbermaid" 

As is it only returns the second but not the first.

Is this doable with EmberFire?  Also, a way to do a case insensitive query? 

BTW the recent improvements to emberfire are fantastic!!! Great work.

Brendan

**Comment by tstirrat** [comment]
Unfortunately, we don't have a way to do a "like" style queries that match substrings. For that, and case insensitive queries, you might want to try some type of indexer such as ElasticSearch. There are a bunch of [resources](https://github.com/firebase/flashlight) out [there](http://www.waltza.com/2015/07/16/firebase-elasticsearch-dummy-walkthrough/) about this.

Also, your query syntax is incorrect. The only properties that are accepted in the query hash are `orderBy`, `limitToFirst`, `startAt`, `endAt`, and `equalTo`. These map to the underlying Firebase [query methods](https://www.firebase.com/docs/web/guide/retrieving-data.html#section-queries).

From the [docs](https://www.firebase.com/docs/web/libraries/ember/guide.html#section-querying):

> ... combine `orderBy` with `limitToFirst`, `startAt`, `endAt`, and `equalTo` to construct more complex queries. See the [EmberFire API docs](https://www.firebase.com/docs/web/libraries/ember/api.html) and documentation on Firebase's [querying methods](https://www.firebas[e.com/docs/web/guide/retrieving-data.html#section-queries) for more details.

**Comment by brendanoh** [comment]
Thanks for the reply @tstirrat 

> Also, your query syntax is incorrect. 

This is really strange because this syntax 100% works the exact way I wrote it above and effectively works as an autocomplete. 

However, it is case sensitive and it has to start with whatever the value is ("rub" in my example).

Is this a surprise that it actually works? Is this a "bug" and not a "feature"?

**Comment by brendanoh** [comment]
@tstirrat - I see now what it is doing. The syntax above is actually just pulling down ALL and then doing the filter client side. Weird.

Is there any documentation on debugging Firebase connections in the browser? Checking the frames in chrome isn't the most user friendly.

**Comment by tstirrat** [comment]
I was very surprised to see it partially working, figured there might be some sort of client side filtering.

Re: the debugging connections: [turn on debug logging](http://stackoverflow.com/a/21611103/2812803): `Firebase.enableLogging(true, true)`. Note that this is on the Firebase class, not on the ref

**Comment by brendanoh** [comment]
Yeah this should be closed. @tstirrat, I came up with a creative approach to the autocomplete problem (without using Elastisearch) that may be helpful for others in the same position. Any place I should write it up?

**Comment by tstirrat** [comment]
I'd be interested, in here is fine. Or if it's better suited, maybe as a series of gists.

**Comment by brendanoh** [comment]
Here is the GIST to my workaround of the case insensitive, partial string search for an autocomplete: https://gist.github.com/brendanoh/79921203529ab9a57cb3
