### ISSUE TITLE
emberfire breaks with ember data 2.3

### ISSUE THREAD

**Issue by jagthedrummer** [firebase/emberfire#352]
Looks like there have been some pretty hefty changes in how ember data is imported. This is causing some problems with emberfire. http://emberjs.com/blog/2016/01/12/ember-data-2-3-released.html

**Comment by tstirrat** [comment]
Thanks for the heads up. this will be interesting, trying to support both types of importing

**Comment by tstirrat** [comment]
It seems if we remove torii, all the tests pass and things seem to continue working fine

**Comment by tstirrat** [comment]
Added an issue here: Vestorly/torii#261

**Comment by jagthedrummer** [comment]
Weird. In the app where I discovered this issue we have both torii and emberfire installed. After upgrading ember data the app wouldn't even boot/load, and on a hunch I tried removing emberfire. After removing emberfire the app would boot just fine even with torii still installed (required by the app itself).

**Comment by spovich** [comment]
I'm seeing this also.  Until this is fixed in torii, you can add/keep `ember-data` in your `bower.json` and things will continue to work (although ember-data will bark warning)

**Comment by jagthedrummer** [comment]
This may be due to an old version of torii (0.5.1) being used in emberfire. When I use torii 0.6.2 or torii#master directly I don't have an issue (and without emberfire).

**Comment by tstirrat** [comment]
ok, lets bump it

**Comment by tstirrat** [comment]
Can you try `ember install firebase/emberfire#update-torii` and see if that fixes it.. I don't seem to be able to recreate the error in a new repo

**Comment by spovich** [comment]
@tstirrat That doesn't fix it for me.  I updated my package.json so I have `"emberfire": "firebase/emberfire#update-torii",` and nuked `node_modules` and `bower_components`, but I still get `No application initializer named 'store'`

**Comment by ksnyde** [comment]
I too was getting the "No application initializer named 'store'" error and decided to step back to Ember Data 2.2.1 (in both Bower and NPM) but maintain all the other dependencies articulated in `ember-cli@2.2.0-beta.6`. Now I get:

![2016-01-16_00-18-19](https://cloud.githubusercontent.com/assets/980757/12368831/55963a4a-bbe7-11e5-9c5c-f28d8ee55c62.png)

**Comment by tstirrat** [comment]
emberjs/data#4087

**Comment by ksnyde** [comment]
Great. Misery loves company ... And it really loves an explanation. Looks like we've got both now. :+1:

**Comment by bmac** [comment]
@jagthedrummer and @ksnyde do you mind trying out Ember Data [v2.3.2](https://github.com/emberjs/data/releases/tag/v2.3.2) to see if it fixes the issue?

**Comment by ksnyde** [comment]
Yup, will do but it will be late tomorrow or possible Wednesday as I'm in the middle of pulling an all nighter to hit a deadline. :8ball:

**Comment by spovich** [comment]
2.3.2 fixed the issue for me!  Thank you!
