### ISSUE TITLE
Ember-cli install with 2.3.0-beta.1 application.js issue

### ISSUE THREAD

**Issue by agustinsaldias** [firebase/emberfire#357]
Hi!

I installed emberfire today on a clean installation with ember-cli@beta and had some issues getting it to work properly until I found the issue, although I'm not sure if it was just my bad luck.

I'm on Win10x64 if that makes a difference.

```
npm install -g ember-cli@beta
```
```
D:\Work\EmberJS> ember -v:
version: 2.3.0-beta.1
node: 4.2.4
npm: 2.14.10
os: win32 x64
```
Of course I run the ember new projectname command and then entered my newly created project to run
```
ember install emberfire
```

It seemed to work, at least the installation worked and the files were created, but, I constantly got this error on my chrome console whenever I tried to use ember-data (this.store.*):
> Could not find module `emberfire/adapters/firebase` from X

After searching online for a few hours I couldn't find the answer nor anyone having the same issue. I decided to read the official guide again to see if there was something missing and decided to compare my files and how they were supposed to look, and found the culprit.

The **app/adapters/application.js** file that was created by the installation *didn't include* this particular line at the top:
```javascript
import config from '../config/environment';
```

Anyone else had the same issue by any chance? Tried looking for an older issue here but couldn't find it either. I created a new project from scratch, installed emberfire on it and got the same results. 

Thanks!

p.s. I was just checking the repo and saw that the blueprint for emberfire doesn't include that line anymore, could that be the issue? And if so, is there a reason it got removed in the first place?

edit: I'm not sure if this is the issue, but this corrected my problem 100% (I'm new to ember). I know the changes were made to allow firebase as a service, but I'm not sure why that line in particular helped me.

**Comment by agustinsaldias** [comment]
And now I can't reproduce it anymore....maybe it was a coincidence or something similar..

I'll just close it to remove the clutter, will reopen if needed. Thanks anyways!

**Comment by tstirrat** [comment]
That's odd. nowadays `adapters/application.js` doesn't need the config. It uses the firebase service which reads the config... Please do reopen, if you can find a repro.
