### ISSUE TITLE
Emberfire hasMany storage and order question?

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#362]
I store hasMany relationships on a model and it works as expected in most ways. However, the way the "array" is stored seems very unconventional. See below:

<img width="414" alt="screen shot 2016-02-05 at 5 38 50 pm" src="https://cloud.githubusercontent.com/assets/3473461/12861182/8bd4786c-cc2f-11e5-9b85-0f902107ef27.png">

I have read the following blog post which explains the 'why": https://www.firebase.com/blog/2014-04-28-best-practices-arrays-in-firebase.html but this still is causing some issues for me because I am using https://github.com/jgwhite/ember-sortable to allow users to SORT the related items so I need to store this relationship in a certain order which would normally be possible if it stored a pure array of keys. Screen below:

<img width="903" alt="screen shot 2016-02-05 at 5 41 19 pm" src="https://cloud.githubusercontent.com/assets/3473461/12861230/e7ca94c6-cc2f-11e5-8512-9c4ffdb2bfbd.png">

@tstirrat et al. 
Is this something that people have come across before? I couldnt find any answers related to this here. Just looking for a workaround if anyone has one.

Cheers!

**Comment by brendanoh** [comment]
I am not sure why the second value is always ```true``` in the storage image above but I assume there is likely a good reason. I guess for my use case it would be optimal to serialize with a sequence integer value instead of always being boolean true. Something like:

```
employments  
 -K8V9qndsl6cTfcaWHVA: 3
 -K92bn9xmi6RTMiH_BHI: 4
 -K92hQ-44QaxfnkwAL3l: 2
 -K92hqVrEoXglwqAZ924: 1
```

And then have the array sorted in the serializer using the sequence value. Just thinking aloud...

**Comment by tstirrat** [comment]
This is not something that has directly been asked for, but I can definitely see the need. I think we can use [priorities](https://www.firebase.com/docs/web/api/firebase/setpriority.html) for this, so that we can remain backwards compatible with existing data sets.

**Comment by brendanoh** [comment]
Thanks @tstirrat. So below works fine:
```
    reorderEmployment(newOrder) {
      const modelId = this.get('model.id'); 
      newOrder.forEach(function(employment, index) {
        let ref = new Firebase('https://amber-fire-9286.firebaseio.com/personSkills/' + modelId + '/employments/' + employment.get('id'));
        ref.setPriority(index);         
      });
    }, 
```

**Comment by tstirrat** [comment]
That's good as a short term solution, but you might have problem getting correct ordering from the server. For this we need to use Firebase's [forEach](https://www.firebase.com/docs/web/api/datasnapshot/foreach.html) implementation on relationships.

> Because of the way JavaScript object hashes work, the ordering of data in the JavaScript object returned by val() is not guaranteed to match the ordering on the server nor the ordering of child_added events. That is where forEach() comes in handy. It guarantees the children of a DataSnapshot will be iterated in their actual order, the same order as they are kept in your Firebase database.

**Comment by brendanoh** [comment]
Yeah this is just a workaround for now but so far ordering has always been consistent.

@tstirrat if you know what you want to do and just need someone to help with an Emberfire implementation - I can give you some time. I would just need guidance as I do not have a handle on the Firebase internals.

**Comment by sirvine** [comment]
We were using an approach similar to @brendanoh above—iterating over each record and setting priority with:

```javascript
itemModels.forEach(function(item, index) {
    let itemId = get(item, 'id');
    let ref = new Firebase(`https://<app-name>.firebaseio.com/<model-name>/${itemId}`;
    ref.setPriority(index); 
});
```

However, since bumping up to emberfire 2.0.1 and Firebase SDK 3.2.0, we receive the following error: 

```
_firebase.default is not a constructor
```

I suspect that `new Firebase()` is no longer able to create a valid connection?

**Comment by tstirrat** [comment]
You could use the model's `.ref()`

```js
itemModels.forEach(function(item, index) {
  item.ref().setPriority(index);
});
```

Or you could inject the `firebase` service:

```js
const ref = this.get('firebase');
itemModels.forEach(function(item, index) {
    let itemId = get(item, 'id');
    let modelRref = ref.child(`<model-name>/${itemId}`);
    modelRef.setPriority(index); 
});
```

**Comment by sirvine** [comment]
The latter worked like a charm, since I needed to reach down into a nested child model. Thank you!

**Comment by GerritSommer** [comment]
I dont get this to work.

I have a model with:
`documents: hasMany('document', { async: true })`;

Before I save I set a priority:
`model.get('documents').forEach((doc, index)=> {
  doc.ref().setPriority(index);
})`

It doesnt do anything when I show it in the template.

The hasManyArray doesnt have any collection ref, which I could sort by priority. 
It seems to be possible when manally querying, but with an async relationship emberfire does it all.

Im abit lost.

**Comment by brendanoh** [comment]
I am assuming what you are wanting to is have the documents in a certain order? If so below is how I update the order of the `hasMany` array.

I don't know what your model is called so in the example below I am assuming it is a hasMany on a `person` model. So if you have injected firebase at the top of your controller or component file the you pass a sorted array of `documents` to an action called `update` and the following should work:
```
  actions: {
    update(orderedDocuments) {
      const fb = this.get('firebase');
      const personId = this.get('person.id');
      orderedDocuments.forEach(function(doc, index) {
          let docId = Ember.get(doc, 'id');
          let personRef = fb.child(`people/${personId}/documents/${docId}`);
          personRef.setPriority(index); 
      });
    }
}

```
This works for me.

Then if you do the following in your template it should always show in the correct order:

```
{{#each person.documents as | document |}}
  {{document.name}} <br>
{{/each}}
```

**Comment by GerritSommer** [comment]
Thank. I found my error. I added the index on the documents and not the relation-ids.

Im not very used to contribute to public repos, but I did alot of ember-data internals and will try to write a PR for emberfire. Thank you again.

**Comment by Ghostavio** [comment]
Priorities are `DEPRECATED` now, as far as I could see, [this is the line](https://github.com/firebase/emberfire/blob/master/addon/adapters/firebase.js#L563) that saves `true` to the relationship, by playing around with it I managed to save the order

<img width="289" alt="screen shot 2017-05-17 at 07 09 36" src="https://cloud.githubusercontent.com/assets/377506/26139296/d97fc476-3acf-11e7-9a3f-5386b3fe2acc.png">

Is there any plan on supporting this?
