### ISSUE TITLE
Emberfire reporting: Cannot read property 'sendRequest' of null

### ISSUE THREAD

**Issue by moranje** [firebase/emberfire#363]
I have debugged this from as many different angles as I can think of but I can figure this one out.

I'm trying to to load a set of projects which have an images property on them. The projects are loading fine, but the images aren't. I have tried with ember-cli `1.13.15` and emberfire `1.5.0` as well as with ember-cli `2.3.0-beta.2` with emberfire `1.6.4`. My setup is roughly the same as in the official guide. I haven't touched the application adapter, I have no CSP errors and I don't have any authentication set up yet.

### Models
```js
// models/project
import DS from 'ember-data';
import Ember from 'ember';

const {
    computed
  } = Ember, {
    Model,
    attr,
    hasMany
  } = DS;

export default Model.extend( {
  name: attr( 'string' ),
  type: attr( 'string' ),
  client: attr( 'string' ),
  description: attr( 'string' ),
  images: hasMany( 'image', { async: true } ),

  cover: computed( 'images', function() {
    return this.get( 'images.firstObject.src' );
  } )
} );
```

```js
// models/image
import DS from 'ember-data';

const {
    Model,
    attr,
    belongsTo
  } = DS;

export default Model.extend( {
  name: attr( 'string' ),
  src: attr( 'string' ),
  caption: attr( 'string' ),
  project: belongsTo( 'project', { async: true } )
} );
```
### Route
```js
import Ember from 'ember';

export default Ember.Route.extend( {
  model() {
    return this.store.query( 'project', {
      orderBy: 'type',
      equalTo: 'maquette'
    } ).then( ( projects ) => {
      return projects.sortBy( 'name' );
    } );
  }
} );
```

### Data
Imported to firebase
```json
{
  "images" : [ {
    "caption" : "caption",
    "name" : "name",
    "project" : "1",
    "src" : "url/filename.jpg"
  }, {
    "caption" : "caption",
    "name" : "name",
    "project" : "2",
    "src" : "url/filename.jpg"
  }, {
    "caption" : "caption",
    "name" : "name",
    "project" : "2",
    "src" : "url/filename.jpg"
  } ],
  "projects" : [ {
    "client" : "client",
    "description" : "description",
    "image" : {
      "1" : true
    },
    "name" : "name",
    "type" : "maquette"
  }, {
    "client" : "client",
    "description" : "description",
    "image" : {
      "2" : true,
      "3" : true
    },
    "name" : "name",
    "type" : "maquette"
  } ]
}
```

As far as I know the computed property `cover` on the `project` model should trigger a request to firebase and fetch the record, alas that doesn't happen. I am having a hard time figuring  out what does in fact happen, as websockets are obscuring the data flow to me. What does happen is that I get the following errors:

```
Uncaught Connection is not connectedfb.realtime.Connection.sendData_@ firebase-debug.js:11297
fb.realtime.Connection.sendRequest @ firebase-debug.js:11067
fb.core.PersistentConnection.goog.defineClass.sendRequest @ firebase-debug.js:11379
fb.core.PersistentConnection.goog.defineClass.reportStats @ firebase-debug.js:11561
fb.core.PersistentConnection.goog.defineClass.sendConnectStats_ @ firebase-debug.js:11801
fb.core.PersistentConnection.goog.defineClass.onReady_ @ firebase-debug.js:11617
fb.realtime.Connection.onConnectionEstablished_ @ firebase-debug.js:11245
fb.realtime.Connection.onHandshake_ @ firebase-debug.js:11203
fb.realtime.Connection.onControl_ @ firebase-debug.js:11161
fb.realtime.Connection.onPrimaryMessageReceived_ @ firebase-debug.js:11135
(anonymous function) @ firebase-debug.js:11054
fb.realtime.WebSocketConnection.appendFrame_ @ firebase-debug.js:10821
fb.realtime.WebSocketConnection.handleIncomingFrame @ firebase-debug.js:10853
mySock.onmessage @ firebase-debug.js:10778
```

followed by a couple of these:
```
Uncaught TypeError: Cannot read property 'sendRequest' of null
fb.core.PersistentConnection.goog.defineClass.sendRequest @ firebase-debug.js:11379
fb.core.PersistentConnection.goog.defineClass.sendListen_ @ firebase-debug.js:11408
(anonymous function) @ firebase-debug.js:11779
goog.object.forEach @ firebase-debug.js:995
(anonymous function) @ firebase-debug.js:11778
goog.object.forEach @ firebase-debug.js:995
fb.core.PersistentConnection.goog.defineClass.restoreState_ @ firebase-debug.js:11777
fb.core.PersistentConnection.goog.defineClass.onReady_ @ firebase-debug.js:11619
fb.realtime.Connection.onConnectionEstablished_ @ firebase-debug.js:11245
fb.realtime.Connection.onHandshake_ @ firebase-debug.js:11203
fb.realtime.Connection.onControl_ @ firebase-debug.js:11161
fb.realtime.Connection.onPrimaryMessageReceived_ @ firebase-debug.js:11135
(anonymous function) @ firebase-debug.js:11054
fb.realtime.WebSocketConnection.appendFrame_ @ firebase-debug.js:10821
fb.realtime.WebSocketConnection.handleIncomingFrame @ firebase-debug.js:10853
mySock.onmessage @ firebase-debug.js:10778
firebase-debug.js:5284
FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'sendRequest' of null
    at fb.core.PersistentConnection.goog.defineClass.sendRequest (http://localhost:4200/u/10112105/aaltaminimoa/assets/vendor.js:82942:17)
    at fb.core.PersistentConnection.goog.defineClass.sendListen_ (http://localhost:4200/u/10112105/aaltaminimoa/assets/vendor.js:82971:8)
    at http://localhost:4200/u/10112105/aaltaminimoa/assets/vendor.js:83342:12
    at Object.goog.object.forEach (http://localhost:4200/u/10112105/aaltaminimoa/assets/vendor.js:72558:7)
    at http://localhost:4200/u/10112105/aaltaminimoa/assets/vendor.js:83341:17
    at Object.goog.object.forEach (http://localhost:4200/u/10112105/aaltaminimoa/assets/vendor.js:72558:7)
    at fb.core.PersistentConnection.goog.defineClass.restoreState_ (http://localhost:4200/u/10112105/aaltaminimoa/assets/vendor.js:83340:15)
    at fb.core.PersistentConnection.goog.defineClass.onReady_ (http://localhost:4200/u/10112105/aaltaminimoa/assets/vendor.js:83182:8)
    at fb.realtime.Connection.onConnectionEstablished_ (http://localhost:4200/u/10112105/aaltaminimoa/assets/vendor.js:82808:10)
    at fb.realtime.Connection.onHandshake_ (http://localhost:4200/u/10112105/aaltaminimoa/assets/vendor.js:82766:10)
```

Which seem to be caused bij the `fb.realtime_` (websocket connection?) being disconnected (and `fb.realtime_ = null`) through `onRealtimeDisconnect_`. I don't know whether my async relationship problem has anything todo with the vague errors I'm getting, but I could use some help getting the images to loading through the reference in projects.

Thanks in advance,

Martien

**Comment by brendanoh** [comment]
I have hit a lot of weirdness but not seen those errors in my console. A few questions that may help or may not: 

1. If you look in forge are the hasMany relationships still there for those projects on both sides (belongsTo in image and hasMany in project)?
2. Are the ID's for those images still 1 and 2 as importing them again would erase the old ones and I believe give them new larger int IDs? 
3. Are you using the cover property in your template? Because I am not sure the computed itself will trigger the request if it isn't used.
4. Have you tried removing the sortBy in your model hook? 
5. What browser are you using? I have gotten error messages with Firefox that were different than in chrome (still not sure why)

Brendan

**Comment by tstirrat** [comment]
One problem that I can immediately see is the property in your project json for `images` is not correct (you have `image`):

```js
  {
    "client" : "client",
    "description" : "description",
    "image" : { //  should be `images`
      "1" : true
    },
    // ...
  }
```

However, this looks like a connectivity issue. Can you try an incognito window (something that disables browser extensions). Sometimes ad-blockers can block the realtime connections.

**Comment by moranje** [comment]
Hi Brendan and Tim, thanks for taking the time to respond.

@brendanoh 
_1. If you look in forge are the hasMany relationships still there for those projects on both sides (belongsTo in image and hasMany in project)?_

I am looking into Forge, looks like I should be able to find it on the firebase dashboard. Can you give me a nudge in the right direction.

_2. Are the ID's for those images still 1 and 2 as importing them again would erase the old ones and I believe give them new larger int IDs?_

Will have to check.

_3. Are you using the cover property in your template? Because I am not sure the computed itself will trigger the request if it isn't used._

Yes the cover property is being used in a template. It's being called, but I just can't see a request being sent (but like I said, with websockets it's a little harder to keep track of the data flow).

_4. Have you tried removing the sortBy in your model hook?_

It had the expected effect of scrambling my data.

_5. What browser are you using? I have gotten error messages with Firefox that were different than in chrome (still not sure why)_

Chrome, latest stable build. Tried firefox as well but hit the peak connections limit...

@tstirrat 
That got me half way,  the images are loaded nog but the errors still appear. I tried it in an incognito window in chrome, same errors. I tried firefox and fresh install of chrome canary but I've hit "Peak Connections limit", so I guess I'll have to wait or discuss an upgrade.

Anything I can do or send in order to get more insight into what causing this?

Thanks again, Martien

**Comment by tstirrat** [comment]
You can enable debug logging as mentioned [here](http://stackoverflow.com/questions/22419073/how-do-i-turn-on-logging-in-the-firebase-javascript-client)

**Comment by moranje** [comment]
I have opened a ticket with firebase, for the concurrent connections peak (I have been the only one using the app). I'll post more as soon as I hear back from Firebase.

**Comment by tstirrat** [comment]
Let me know if you got further on this. The `sendRequest` error is really strange, I've not seen it with EmberFire before.

**Comment by jamesdaniels** [comment]
Going to close for now. Stale + seems to be a firebase.js issue. If you bump into it again feel free to discuss here.
