### ISSUE TITLE
EmberFire seems to need full autorisation to return a subset of an object.

### ISSUE THREAD

**Issue by scandinave** [firebase/emberfire#371]
Hi,
I have to model like this : 
```
//conversation.js
import DS from 'ember-data';

export default DS.Model.extend({
   users: DS.hasMany('user', {async : true}),
   messages : DS.hasMany('message', {async : true}),
   notify : DS.attr('string'),
   block : DS.attr('string'),
});
```
and
```
import DS from 'ember-data';

export default DS.Model.extend({
	email : DS.attr('string'),
  	name: DS.attr('string'),
  	age: DS.attr('number'),
  	sex: DS.attr('string'),
  	location: DS.attr('string'),
  	timestamp: DS.attr('number'),
  	conversations : DS.hasMany('conversation', {async:true})
});
```

I want to retrieve all notifications for one user, that have a notify property equals to a userID. So i make this request in my route :
```
this.store.query('conversation', {
       orderBy : 'notify',
       equalTo : userId
}),
```

This works. But i started to implement Firebase security to restrict access of User to their own conversation.

My rule is has follow : 
```
"conversations" : {
        ".indexOn" : "notify",
        "$conversation" : {
           ".read" : "auth !== null && root.child('conversations/'+$conversation+'/users').hasChild(auth.uid)", 
           ".write": "auth !== null && root.child('conversations/'+$conversation+'/users').hasChild(auth.uid)"
        }
      }
```

With this rule the request above doesn't work anymore because the node "conversations" has no a read rule access. So how can i do to make this request works again? Is the rule that I needs modify or the request itself

**Comment by tstirrat** [comment]
The issue here is that [rules are not filters](https://www.firebase.com/docs/security/guide/securing-data.html#section-filter) and cannot be used this way. You do not have permission to query on the parent node if you do not have access to **all** children.

You'll need to look at the `user.conversations` relationship to get access to specific nodes. Querying all conversations will not be possible with those rules.

**Comment by scandinave** [comment]
ok. do you have a solution ,so i can retrieve in real time all conversation with a notify attribute and that passe this rule? Or do i need to rewrite the model of my application?

**Comment by tstirrat** [comment]
Inspired by this question I'm proposing an enhancement to EmberFire here: #432

**Comment by jamesdaniels** [comment]
Closing due to proposal #432
