### ISSUE TITLE
Cannot read property 'notify' of undefined

### ISSUE THREAD

**Issue by sirvine** [firebase/emberfire#374]
Three models, where `playbook` <--embedded-- `clause` <--embedded-- `definition`.

    
    # models/playbook.js
    export default Model.extend({
      title: attr('string'),
      clauses: hasMany('clause', {async: false})
    });

    # models/clause.js
    export default Model.extend({
      title: attr('string'),
      definitions: hasMany('definition', {async: false})
    });
    
    # models/definition.js
    export default Model.extend({
      title: attr('string'),
      meaning: attr('string')
    });

I also have the following serializers:

    # serializers/playbook.js
    export default FirebaseSerializer.extend({
      attrs: {
        clauses: { embedded: 'always' }
      }
    });

    # serializers/clause.js
    export default FirebaseSerializer.extend({
      attrs: {
        definitions: { embedded: 'always' }
      }
    });

Since everything is embedded into the `playbook`, I am adding the childen on the client side and saving only the `playbook` to Firebase. 

When a `playbook` contains only `clauses` (i.e., without any `definitions`), there is no problem. 

However, when a `definition` is added to any `clause` in a `playbook`, I receive the following error in the console when attempting to save the parent `playbook`:

<img width="682" alt="screen shot 0028-03-04 at 1 11 20 am" src="https://cloud.githubusercontent.com/assets/68167/13522933/b2b8239a-e235-11e5-89d1-878f1187d24a.png">

In the past, I've seen this error when my data model is inconsistent. But in this case, I don't know where to look to debug the problem. 

This error only appears the first time the `playbook` is saved, and the changes seem to be persisted on Firebase without any problem. All subsequent saves work fine without this error. Also, if I comment out the `definitions` relationship from the `clause` model, the error is completely gone.

**Comment by sirvine** [comment]
It looks like this was a problem with a computed property that sorted and filtered the `definitions` for the template. Closing...

**Comment by tstirrat** [comment]
Thanks for following up and posting the resolution here :+1:
