### ISSUE TITLE
Relationship must be key/value pair

### ISSUE THREAD

**Issue by jrock2004** [firebase/emberfire#379]
Getting the following error:
```
firebase.js:119 Uncaught Error: thunder@model:provider: relationship hasMany('address') must be a key/value map. Example: { "address": { "address_1": true } } instead got: "-KDehK2aAE15KEQXjHC-"
```

Address Model

```
export default DS.Model.extend({
  city: DS.attr('string'),
  state: DS.attr('string'),
  street: DS.attr('string'),
  zip: DS.attr('string'),
  provider: DS.belongsTo('provider')
});
```

Provider Model

```
export default DS.Model.extend({
  category: DS.attr('string'),
  status: DS.attr('boolean'),
  name: DS.attr('string'),
  description: DS.attr('string'),
  address: DS.hasMany('address', {async: true}),
  phone: DS.attr('string'),
  email: DS.attr()
});
```

Here is what I have in Firebase
<img width="510" alt="screen shot 2016-03-24 at 7 23 38 pm" src="https://cloud.githubusercontent.com/assets/655716/14034064/fb6ca9d8-f1f5-11e5-9551-64f36c3c681e.png">

**Comment by steven-ferguson** [comment]
The ```address``` relationship is setup as a belongsTo in your firebase, but you have defined it as a hasMany in ember. Check out the [example in the docs](https://www.firebase.com/docs/web/libraries/ember/guide.html#section-relationships). If you want addresses as a hasMany it should look like this in firebase (assuming you change the property name in Ember from address to addresses):

```json
"providers": {
  "providerIdOne" : {
     "addresses": {
       "addressIdOne": true    
    }
  }
}

**Comment by jrock2004** [comment]
This was all user error. Thanks
