### ISSUE TITLE
How to set scope when using the torii adapter

### ISSUE THREAD

**Issue by danpaz** [firebase/emberfire#381]
Not sure this is documented anywhere -- I couldn't find it anyway -- but I discovered the way to pass the `scope` option when using the torii firebase adapter is:
```
this.get('session').open('firebase', { provider: 'github', settings: { scope: 'user,gist' }})
```

I discovered this after seeing https://github.com/firebase/emberfire/pull/325.

Perhaps this belongs in the authentication section of the emberfire guide? https://www.firebase.com/docs/web/libraries/ember/guide.html#section-authentication

**Comment by tstirrat** [comment]
Thanks!

I'll pass it along to the docs people and get it updated.

**Comment by danpaz** [comment]
Good stuff, thanks!

**Comment by jamesdaniels** [comment]
Scope is mentioned in our newest docs https://github.com/firebase/emberfire/blob/master/docs/guide/authentication.md
