### ISSUE TITLE
Firebase.open in same window (or iframe?)

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#382]
@tstirrat is it possible to implement social login without the secondary window opening up? It doesn't seem to be in the docs anywhere. I plan on shipping my App packaged with Electron as a desktop app and the new window does not work in that environment anyway.

Any help would be appreciated.

Brendan

**Comment by tstirrat** [comment]
You can use [authWithOAuthRedirect()](https://www.firebase.com/docs/web/api/firebase/authwithoauthredirect.html), but it will lose the current state of the ember app, because it uses redirects.

**Comment by rmmpaderes** [comment]
@brendanoh, @tstirrat - I haven't really looked into it yet but I seems that Torii already supports iframe for authentication. That should solve the problem with pop-up not working and us falling back to redirect loses the state of the ember app.

I haven't tried anything yet with it though so I'm not exactly sure. But I'd like to share it just in case.

**Comment by jpguzman** [comment]
You can also try:
'this.get("session").open("firebase", { provider: provider, redirect: true }).then(function(data) {
  // Callback
});'

The user will be forced to a new page, where they'll need to verify their social login credentials, but then they'll be redirected back.
