### ISSUE TITLE
Authentication issue after upgrade with this.get("session").open("firebase"...

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#383]
I am not sure if this is a regression but after upgrading ember and ember-cli to the latest versions ~2.4.3 and emberfire to 1.6.6 I am getting weird behavior seen below.

![screen recording 2016-04-08 at 02 55 pm](https://cloud.githubusercontent.com/assets/3473461/14394897/91c1e40a-fd9c-11e5-9e09-1862be73596c.gif)

The popup opens but never closes and the page redirects right away instead of after and the debugger below never gets hit. 

```
        const self = this;
        this.get("session").open("firebase", { provider: provider}).then(function(data) {
          debugger
          self.get('register').perform(data);
        });  
```
Hoping someone recognizes this issue as I don't get any errors anywhere.

**Comment by brendanoh** [comment]
As a follow up -I cloned emberfire, upgraded everything to 2.4.3 and ran the dummy app and the auth works as expected.

The main issue seems to be that the main window is redirecting before the auth window even opens AND once I auth in the popup that window never closes.

I assume this is somehow a problem of my own making but I am so down in the weeds that I am hoping someone has some idea how this would happen.

**Comment by brendanoh** [comment]
And when I try ```redirect: true``` I get the same thing minus the popup.

 
![screen recording 2016-04-10 at 04 41 pm](https://cloud.githubusercontent.com/assets/3473461/14412986/62a32e72-ff3b-11e5-8fa6-5dbc56c8c25f.gif)

**Comment by jatugade** [comment]
Did you figure out how to fix this issue? I'm on emberfire 2.0.1 and torii 0.8.0 and I keep getting this.get('session').open is not a function

**Comment by brendanoh** [comment]
Are you injecting the session?
```
  session:        inject.service(),
```

**Comment by Nishkixs** [comment]
@jatugade Did you end up figuring out the problem? I'm having the same one.

**Comment by brendanoh** [comment]
@Nishkixs are you on Ember Slack? I created an Emberfire room and it is a great place to get help.

https://embercommunity.slack.com/archives/e-emberfire
