### ISSUE TITLE
3.0 upgrade

### ISSUE THREAD

**Issue by zurnet** [firebase/emberfire#384]
To confirm, I'm assuming this library will need an upgrade to work with the recently launched firebase 3.0 api (upgraded on 5/18/2016)? If so, is there an eta for that?

-Matt

**Comment by abehaskins** [comment]
It will - I was hoping to have this before I/O, but it didn't quite make it. No promises on deadline, but it shouldn't be too long :)

**Comment by tstirrat** [comment]
Some points of clarification before we make the new release:

- If you haven't migrated a project, keep using EmberFire 1.6.x as usual.
- If you migrate a project, existing EmberFire 1.6.x will continue to work for database operations, but **the Torii auth provider will not work**.

Bottom line: If you aren't using Torii auth, you can migrate away.

**Comment by James-Parsons** [comment]
Any update on the update :D

**Comment by brendanoh** [comment]
@tstirrat I am under no pressure to migrate my projects however I am not clear how long the deprecated firebase.com will be available. And the warning is a little scary 👊 
<img width="675" alt="screen shot 2016-05-20 at 6 17 12 pm" src="https://cloud.githubusercontent.com/assets/3473461/15443563/5282f806-1eb7-11e6-8d11-041189682ca8.png">

**Comment by katowulf** [comment]
Brendan,

Upgrading your dashboard is not related to updating your SDK versions or code. Please wait patiently for the EmberFire upgrade. Please do upgrade your dashboard as soon as practical.

☼, Kato

**Comment by katowulf** [comment]
Hi All! Wanted to give a quick update here. The bulk of the work needed to support the I/O release is done (thanks @abehaskins!). We're working out some auth issues and tweaks, adding in tests, and this should be ready to go!

**Comment by tstirrat** [comment]
3.0 SDK compat. has landed in EmberFire 2.0.0
