### ISSUE TITLE
Cannot save records to Firebase

### ISSUE THREAD

**Issue by tavosansal** [firebase/emberfire#388]
### Version info

```
DEBUG: Ember      : 2.5.1
DEBUG: Ember Data : 2.6.0
DEBUG: Firebase   : 3.0.4
DEBUG: EmberFire  : 2.0.0
DEBUG: jQuery     : 2.2.4
```

### Steps to reproduce

Try saving a new record to Firebase

### Expected behavior

I should be able to create new records using emberfire

### Actual behavior
Getting this error: 
```Uncaught TypeError: _firebase.default is not a constructor```

Not sure if the following part of the guide is still relevant? https://www.firebase.com/docs/web/libraries/ember/guide.html#section-ember-add-firebase

If I change my adapter to look something like this:
```
import config from '../config/environment';
import Firebase from 'firebase';
import FirebaseAdapter from 'emberfire/adapters/firebase';

export default FirebaseAdapter.extend({
  firebase: Firebase.initializeApp(config.firebase)
});
```
Then I get a little farther along but an error is thrown inside Firebase.js inside ```generateIdForRecord``` method. ```firebase.js:72 Uncaught TypeError: this._ref.push is not a function```

I have tried to find answers without any luck so help is very much appreciated.

**Comment by keithkelly** [comment]
I ran into the same issue.  The adapter configuration in the current docs is out of date.  It should look like this now:

```javascript
import FirebaseAdapter from 'emberfire/adapters/firebase';

export default FirebaseAdapter.extend({
});
```

**Comment by tavosansal** [comment]
Thanks for the reply. I did change that and now when I try to save a record I get a bunch of 404 errors that look like this ```https://coschedule-time-off.firebaseapp.com/.lp?start=t&ser=14418816&cb=1&v=5```. Any idea what this could be?

**Comment by tstirrat** [comment]
Hey Gustavo,

Sorry for the confusion here. The old guides are out of date. I'm working on moving the docs into to this github repo.

The legacy guide is still relevant in terms of storing and retrieving records, but the initial configuration part has changed. You need to use the new style configuration format:

```js
// config/environment.js
var ENV = {
  // ...
  firebase: {
    apiKey: 'xyz',
    authDomain: 'YOUR-FIREBASE-APP.firebaseapp.com',
    databaseURL: 'https://YOUR-FIREBASE-APP.firebaseio.com',
    storageBucket: 'YOUR-FIREBASE-APP.appspot.com',
  },
```

You can get this info from [the Firebase console](https://console.firebase.google.com/)

Select your Firebase project and then click **[Add Firebase to your web app]** on the overview page.

**Comment by tavosansal** [comment]
Thank you...I am gonna go ahead and close the issue. Appreciate the help.

**Comment by andrewevans** [comment]
Similar issue. I have application.js as stated above and my environment.js as stated above, and I get this error, even though the data is exactly the values that firebase provided:
```firebase.js:186 Error: permission_denied at /posts/-KKv2I2d18Dn6CTBXKsn: Client doesn't have permission to access the desired data.```

**Comment by keithkelly** [comment]
@andrewevans I think your issue might have to do with the new Firebase default security rules.  The new defaults require users to be authenticated in order to read or write data.  You will probably need to change your rules or authenticate in order to avoid your error.
