### ISSUE TITLE
createUser is not a function with Emberfire 2.0

### ISSUE THREAD

**Issue by netvampire** [firebase/emberfire#390]
Hi There,

I have recently upgraded to Emberfire 2.0 and Firebase 3.0. The upgrade went very smooth over all. Everything seems to be forward compatible except for the "createUser" call. I am using Torii with email/password authentication.

When I try to call:

`this.get('firebase').createUser({...})
`
I receive the error:
`this.get(...).createUser is not a function
`
If you have nay feedback it would be most appreciated.

Thank you

**Comment by tstirrat** [comment]
Hey, yes the new Firebase 3.0 SDK changed the API. Now you use [firebase.auth().createUserWithEmailAndPassword](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#createUserWithEmailAndPassword)

I am working on a migration guide that will address all these changes. 

Here is the updated way to do it:

```js
firebaseApp: Ember.inject.service(),

actions: {

  createUser(email, pass) {
    const auth = this.get('firebaseApp').auth();
    auth.createUserWithEmailAndPassword().then((userResponse) => {
      const user = this.store.createRecord('user', {
        id: userResponse.uid,
        email: userResponse.email
      });
      return user.save();
    });
  }

}
```

**Comment by netvampire** [comment]
Thank you tstirrat for your assistance. I have it working successfully.

Two things to note for anyone else in a similar boat:

1. The createuserWithEmailAndPassword takes two parameters, email and password.  Eg createUserWithEmailAndPassword(myEmail, myPassword)

2. In the past, i had used 
`firebase: Ember.inject.service() `

This simply did not work. I believe 'firebase' is now a keyword. I simply renamed it as follows and things worked:
`firebaseApp: Ember.inject.service() `

**Comment by tstirrat** [comment]
ahh, thanks, will update the original code snippet.

**Comment by ScottMcintire90** [comment]
Hey this code is great, is there any chance you could provide a sign in action? We're having trouble implementing that in our app, but thanks to you our create user action works swimmingly.

**Comment by tstirrat** [comment]
There are docs on a `signIn` action here: https://github.com/firebase/emberfire/blob/master/docs/guide/authentication.md

**Comment by ScottMcintire90** [comment]
Thanks for the link. I've followed along with it and can't figure out why I keep getting this error when signing in, " Uncaught TypeError: this.get(...).open is not a function ". It seems my session is not injecting properly in firebase. I've triple checked my config files, toriiadapter files, etc. Any idea what's going on?

**Comment by tstirrat** [comment]
Check that you have torii installed in `package.json` and it is present in `node_modules`.

Check that you have this in your `config/environment.js`.

```
  torii: {
    sessionServiceName: 'session'
  }
```

If you cannot `this.get('session')`, then something else is broken. I am not sure and cannot debug it without seeing the code.

**Comment by ScottMcintire90** [comment]
this.get('session') returns a session object, but as soon as something is called on that (eg open, fetch) it returns an error. We have all of the things that you mentioned. Maybe our versions are not compatible or ember updated. Thanks for the help I know its not really possible to debug our code from a distance.

**Comment by tstirrat** [comment]
what's the session object look like?

maybe torii changed the way they do things. or maybe you have some other addon that also injects this.session into things.

**Comment by ScottMcintire90** [comment]
The session object looks like this: 
Class {__ember1466534270621: null, __ember_meta__: Meta}
__ember1466534270621: null
__ember_meta__: Meta
_super: ROOT()
container: (...)
__proto__: Class

**Comment by es6Test** [comment]
@tstirrat 

I'm using emberfire like this to sign in, should I do it the way you demonstrated for createUser?

```js
actions: {
    signIn: function (provider, model) {
      this.get('session').open('firebase', {
          provider: provider,
          email: model.username,
          password: model.password
        }
      ).then((data) => {
        console.log(data.currentUser);
        this.transitionTo('app')
      }).catch((error)=>{
        console.log(error)
      });
    }
  }
```

**Comment by es6Test** [comment]
`createUserWithEmailAndPassword` doesn’t throw a catch if you give it a null email

you just get a console error

Probably a firebase api thing

**Comment by es6Test** [comment]
@tstirrat I was wondering what advantage setting `email` on the user has, given it is stored in the Authentication table?

```js
const user = this.store.createRecord('user', {
        id: userResponse.uid,
        email: userResponse.email
      });```

![image](https://user-images.githubusercontent.com/13809207/27600411-bdcd101c-5b63-11e7-86a9-907e18d3ee25.png)
