### ISSUE TITLE
Authentication Migration Guide (Google+Twitter)

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#393]
Since the new version of EmberFire is out I thought I would try it but there have been issues:
1. I had to change the auth callback URI in Github for it to work but now it seems ok. 
2. Google say wrong redirect URI but since there are now 2 projects in my google console with the same name (the FB one and the one for Google sign-in) it is confusing and I am not clear how to fix it in development without bombing production. 
3. Twitter auth works but seems to not recognize the previous ID it gave before so my system thinks old users are new users and now the API is not bringing back any data for Twitter so that login is now not working right. 5

The old auth guides were fantastic but in the new general firebase docs they are less explicit and I cant find info on migrating.

Any help would be appreciated.

**Comment by brendanoh** [comment]
@tstirrat no pressure to complete but do you have an idea on timing or who to contact because this is a pretty huge blocker for me.

**Comment by oskarrough** [comment]
Just leaving it here for others.

If you've migrated your Firebase project to the new Google console and have been using Facebook login, you'll need to update the oAuth redirect URL. It's under Auth > Sign-in methods > Facebook and you'll enter it on developers.facebook.com

**Comment by 20v100** [comment]
Not sure if this is by design: Firebase SDK 3.0 (or Emberfire on Firebase SDK 3.0) does not support a user creating a Google account and a Facebook account using the same email. It was not a problem in version prior to Firebase 3.0.

**Comment by brendanoh** [comment]
@20v100 there is a new option in the fire base with console whether to allow creation of multiple accounts with the same email address. I haven't tested this with Facebook and Google but it should work if that option is set to allow multiple accounts with same email.
