### ISSUE TITLE
Error on save data. this._ref.push is not a function

### ISSUE THREAD

**Issue by sandinosaso** [firebase/emberfire#397]
### Version info

```
DEBUG: -------------------------------
DEBUG: Ember      : 2.6.0
DEBUG: Ember Data : 2.6.1
DEBUG: Firebase   : 3.0.5
DEBUG: EmberFire  : 2.0.0
DEBUG: jQuery     : 1.11.3
DEBUG: -------------------------------
```

### Steps to reproduce
Create a component to use firebase. Try to save a record on init:

```
  init() {
    this._super(...arguments);
    let store = get(this, 'store');

    let newMessage = store.createRecord('message', {
        content: 'Mensaje de prueba',
        createdAt: new Date()
    });

    newMessage.save();
  },
```
### Expected behavior

Save record

### Actual behavior

firebase.js:72 Uncaught TypeError: this._ref.push is not a function

**Comment by ajainvivek** [comment]
I am also facing the same issue. Any idea how to resolve this ?

**Comment by ajainvivek** [comment]
Looks like the root or child database location reference is broken as per the latest firebase documentation. Raised a PR for the fix

https://github.com/firebase/emberfire/pull/414
