### ISSUE TITLE
Firebase does not stop listening to record changes when unloading records with store.unloadAll()

### ISSUE THREAD

**Issue by scnewma** [firebase/emberfire#400]
### Version info

DEBUG: -------------------------------
DEBUG: Ember      : 2.6.0
DEBUG: Ember Data : 2.6.1
DEBUG: Firebase   : 3.0.5
DEBUG: EmberFire  : 2.0.0
DEBUG: jQuery     : 2.2.4
DEBUG: -------------------------------
### The problem

I have an application that is loading store records in the Torii application adapter.

```
export default ToriiFirebaseAdapter.extend({

  firebaseApp: Ember.inject.service(),
  store: Ember.inject.service(),

  open(authData) {
    return this._findOrCreateUser(authData)
      .then((user) => {
        return {
          currentUser: user
        };
      });
  },

  close() {
    this.get('store').unloadAll();
    this.get('firebaseApp').auth().signOut();
    return new Ember.RSVP.Promise(resolve => {

      resolve({
        currentUser: null
      });
    });
  },

  _findOrCreateUser(authData) {
    let store = this.get('store');

    return store.find('user', authData.uid)
      .catch(() => {
        let newUser = store.createRecord('user', this.extractUserProperties(authData));

        return newUser.save();
      });
  },

  extractUserProperties(authData) {
    return {
      id: authData.uid,
      displayName: authData.displayName || authData.username || 'Unknown',
      email: authData.email || null,
      photoUrl: authData.photoUrl || null
    };
  }

});
```

When the close hook is called, I want to unload all of the records from the ember data store.
### Expected behavior

All of the records are successfully unloaded from the store and firebase stops listening for changes on those records.
### Actual behavior

Records are successfully unloaded, but firebase throws an authentication error.

firebase.js:186 Error: permission_denied at /users/<user-id>: Client doesn't have permission to access the desired data.
### What I believe the problem to be

Emberfire is overriding the behavior of unloadRecord from ember-data/model.  This works great when I want to unload a specific model because the willUnloadRecord hook is called as expected.

This does not work with unloadAll(), however.  The reason is because Ember uses an 'InternalModel' to reference the records inside of their code.  This 'InternalModel' does not extend the basic 'Model' class therefore willUnloadRecord never has a chance to be called.

**Comment by duro** [comment]
I am also having this exact same issue.

**Comment by timothyerwin** [comment]
_still_ having this issue...anyone from the team want to comment?

**Comment by mileszim** [comment]
I can't find any event in the ember data events API called `recordWillUnload`, nor is there any call to that function in emberfire itself. Thus, emberfire never stops listening to any record after its loaded. I might be wayyy off but this seems to be the case as far as I can tell.

**Comment by jernejc** [comment]
Same issue here, any update ?
