### ISSUE TITLE
Embedded hasMany, explicit belongsTo relationship problem

### ISSUE THREAD

**Issue by tsubik** [firebase/emberfire#401]
I've got a problem with embedded relationships (detailed use case with sample repository below). I know how to fix this problem in emberfire, but first, I want to ask why only implicit relationships are taken into consideration in [getFirstEmbeddingParent method](https://github.com/firebase/emberfire/blob/ec3b9112691d5f1f8f7ed9e0eeaf53cf5c1cd692/addon/adapters/firebase.js#L682), looking also at `initializedRelationships` will solve this problem.

### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 2.6.0
DEBUG: Ember Data : 2.6.1
DEBUG: Firebase   : 3.0.5
DEBUG: EmberFire  : 2.0.0
DEBUG: jQuery     : 2.2.3
DEBUG: -------------------------------
```

### Test case

app/serializers/event.js

```
import FirebaseSerializer from "emberfire/serializers/firebase";

export default FirebaseSerializer.extend({
    attrs: {
        users: { embedded: "always" },
    },
});
```

app/models/event.js

```
import DS from "ember-data";
import Ember from "ember";

export default DS.Model.extend({
    name: DS.attr("string"),
    users: DS.hasMany("user", { async: false }),
});
```

app/models/user

```
import DS from "ember-data";

export default DS.Model.extend({
    name: DS.attr("string"),
    event: DS.belongsTo("event"),
});
```

creating event

```
const user = this.store.createRecord("user", {
    name: "Tomasz"
});
const event = this.store.createRecord("event", {
    name: "New Test event"
});
event.get("users").addObject(user);
event.save();
```

here is [the sample repository](https://github.com/tsubik/emberfire-embedded-relationships-bug)

### Expected behavior

Should save as:

```
{
  "events" : {
    "-KLHFFNBhYXDM-4mTJeY" : {
      "name" : "New Test event",
      "users" : {
        "-KLHFFMtAShJGvzUTjHo" : {
          "event" : "-KLHFFNBhYXDM-4mTJeY",
          "name" : "Tomasz"
        }
      }
    }
  }
}
```

### Actual behavior

But saved as:

```
{
  "events" : {
    "-KLHEPhJDkxpHg4j4wV5" : {
      "name" : "New Test event"
    },
  },
  "users" : {
    "-KLHEPhIyg8GpriaGisc" : {
      "event" : "-KLHEPhJDkxpHg4j4wV5",
      "name" : "Tomasz"
    }
  }
}
```

**Comment by tstirrat** [comment]
Hey, thanks for the detailed issue report! 

re: the usage of implicitRelationships only. The original solution was devised based on my own testing and stepping through with a debugger.. I agree that we should be checking `initializedRelationships`.

Could you submit a PR with tests that cover these cases?

**Comment by tsubik** [comment]
Sure. I will do it tomorrow.
