### ISSUE TITLE
Error in acceptance test

### ISSUE THREAD

**Issue by villander** [firebase/emberfire#404]
![screen shot 2016-06-29 at 6 42 29 pm](https://cloud.githubusercontent.com/assets/10222774/16469820/5c70f912-3e29-11e6-9cee-25f6fca0d23d.png)

I make this test that fail when i find a new animal after saved rendered into DOM. The use of run loop not solved my problem

``` javascript
test('flow of to create a new animal', function (assert) {
  visit('/animals');

  click('#new-animal');

  andThen(function () {
    assert.equal(currentURL(), '/animals/new');
  });

  fillIn('#first-name', 'Leão');
  fillIn('#last-name', 'Marinho');
  click('#create-or-update');
  andThen(function () {
    assert.equal(currentURL(), '/animals'); // Pass
    Ember.run(() => { // Here fail
      const animalCreated = find('div.md-list-item-text:eq(2) h2:first').text(); // The element exist, but return empty string
      assert.equal(animalCreated, 'Leão');
    });

  });

});
```

**Comment by villander** [comment]
@tstirrat  you can help me?

**Comment by gabrielgrant** [comment]
@villander what's the actual error you're seeing?

Not sure if this will solve all your problems, but it looks like you'll at least need to use [test-model-waiter](https://github.com/gabrielgrant/ember-cli-test-model-waiter) (or do something similar yourself) to make sure that the `andThen()` call is actually waiting for EmberFire to finish saving.

**Comment by tstirrat** [comment]
@villander I did a bunch of work to ensure that model fetching caused the tests to wait. It looks like model saving was overlooked. I'll need to add test waiters to the `createRecord` and `updateRecord` methods [like I did with fetching](https://github.com/firebase/emberfire/commit/7c1b2833ee73da1fc585bea18af7fbbd28e26c1d).

**Comment by tstirrat** [comment]
Try the `ts-write-waiters` branch. Let me know if this fixes the issue.

```
ember install firebase/emberfire#ts-write-waiters
```

**Comment by gabrielgrant** [comment]
ah, didn't know you'd started incorporating test waiters @tstirrat -- great to hear, thanks!

**Comment by villander** [comment]
@gabrielgrant i used `test-model-waiter` but not works!

@tstirrat i will try with `ts-write-waiters` thanks :D

**Comment by edborden** [comment]
I believe I'm seeing a similar issue in testing with `createRecord`

```
"Assertion Failed: You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run"
```

```
EmberError	@	ember.debug.js:19642
assert	@	ember.debug.js:6715
assert	@	ember.debug.js:19444
run.schedule	@	ember.debug.js:24444
updateRecordArraysLater	@	internal-model.js:703
transitionTo	@	internal-model.js:490
loadedData	@	states.js:490
send	@	internal-model.js:383
loadedData	@	internal-model.js:275
createRecord	@	store.js:245
```

I tried the `ts-write-waiters` branch, doesn't fix it.

**Comment by tstirrat** [comment]
@edborden I've wrapped the updates and deletes with `Ember.run` in the `ts-write-waiters` branch, please let me know if that sorts things out.

btw. I did a force push (oops). If you get any weird errors with that branch, remove your `node_modules/emberfire` and redo the `ember install`

**Comment by villander** [comment]
@tstirrat i'm installed `ember install firebase/emberfire#ts-write-waiters` 

But the error continue as my first scenario these issue :(

**Comment by villander** [comment]
Other issue @tstirrat is the `error` when my app are loaded, after migrate to `emberfire 2.x`

```
firebase.js:73 Uncaught Error: Illegal url for new iframe - https://https:%2F%2Fanimalscrud.firebaseapp.com/__/auth/iframe?apiKey=uhapd…69240638021&parent=http%3A%2F%2Flocalhost%3A4200&pfname=&rpctoken=20275635
```

**Comment by villander** [comment]
@gabrielgrant, @tstirrat can you help me?

**Comment by villander** [comment]
@tstirrat this still not working using 2.0.4 version :(
