### ISSUE TITLE
Adapter does not implement `queryRecord` method

### ISSUE THREAD

**Issue by tavosansal** [firebase/emberfire#405]
### Version info

```﻿
ember.debug.js:6440DEBUG: -------------------------------
ember.debug.js:6440DEBUG: Ember      : 2.5.1
ember.debug.js:6440DEBUG: Ember Data : 2.6.0
ember.debug.js:6440DEBUG: Firebase   : 3.0.4
ember.debug.js:6440DEBUG: EmberFire  : 2.0.0
ember.debug.js:6440DEBUG: jQuery     : 2.2.4
ember.debug.js:6440DEBUG: -------------------------------
```

### Steps to reproduce

Try to fetch a model like so:
```
model() {
    return this.store.queryRecord('user', {
      filter: {
        email: this.get('auth.email'),
      },
    });
  },
```

### Expected behavior

I wanted to query for a single record in a model as per ember guides [here](https://guides.emberjs.com/v2.6.0/models/finding-records/#toc_querying-for-a-single-record).

### Actual behavior

I get the following error: You tried to make a query but your adapter does not implement `queryRecord` Error: Assertion Failed: You tried to make a query but your adapter does not implement `queryRecord`

**Comment by villander** [comment]
@tavosansal you can use an alternative method to query a record, like this:

http://stackoverflow.com/questions/33071340/how-to-use-emberfire-to-query-a-firebase-db-for-all-items-with-name-equalto-xyz?answertab=active#tab-top

**Comment by eramod** [comment]
@villander I was having the same issue with queryRecord (for a user) and I tried using the alternate method you linked to, but I got this error when I tried to log in: 
`Error: Assertion Failed: normalizeResponse must return a valid JSON API document:
	* One or more of the following keys must be present: "data", "errors", "meta".`

Do you have any idea why this would happen?
