### ISSUE TITLE
Quickstart and Guide broken with new default security rules

### ISSUE THREAD

**Issue by gabrielgrant** [firebase/emberfire#407]
Both the [Quickstart](https://github.com/firebase/emberfire/blob/master/docs/quickstart.md) and the [full guides](https://github.com/firebase/emberfire/blob/master/docs/guide/saving-and-retrieving-data.md) don't seem to mention the new default security rules that block access when the user is not authenticated. As a result, the examples fail with `Error: Some errors were encountered while saving fbapp@model:post: -KLvKvOP80u4RVkKWUHf` when trying to create the record.

Setting the rules to 

```json
{
  "rules": {
    ".read": "true",
    ".write": "true"
  }
}
```

removes the problem.

**Comment by tstirrat** [comment]
Ahh, yes we need to call this out more clearly in the guides.

**Comment by jamesdaniels** [comment]
We're fixing this in #450
