### ISSUE TITLE
Does EmberFire support FirebaseUI Authentication?

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#408]
I cannot seem to find it here or anywhere and it seems to be where AUTH is moving for hosted FB domains.

**Comment by tstirrat** [comment]
You could use the FirebaseUI widgets to do auth. Once you know the FirebaseUI state changed, you would need to call `this.get('session').fetch()` to have Torii look up the firebase auth state and populate its session object.

**Comment by tstirrat** [comment]
I haven't personally tried, so let us know how that goes.

**Comment by brendanoh** [comment]
OK Cool that it is possible. Will try out at some point and will add my findings here.

Thanks @tstirrat

**Comment by steven-ferguson** [comment]
We moved over to using the FirebaseUI widget for auth in our app. Here is a [gist for our implementation](https://gist.github.com/steven-ferguson/8eddf63123fa74066e9d92f7e829d8e9).

**Comment by brendanoh** [comment]
@steven-ferguson you are awesome for creating that Gist. It will be a huge help to many I am sure.

Thanks a lot.

Brendan

**Comment by jamesdaniels** [comment]
Proposing we add this to an Additional Resources section on the Guide #440
