### ISSUE TITLE
EmberFire fails under Fastboot

### ISSUE THREAD

**Issue by gabrielgrant** [firebase/emberfire#410]
### Version info

```
DEBUG: Ember      : 2.6.2
DEBUG: Ember Data : 2.6.1
DEBUG: Firebase   : 3.2.0
DEBUG: EmberFire  : 2.0.1
```

### Steps to reproduce

Run an EmberFire app with fastboot:
```
$ ember fastboot --serve-assets
Built project successfully. Stored in "dist".
Installing FastBoot npm dependencies
DEBUG: -------------------------------
DEBUG: Ember      : 2.6.2
DEBUG: Ember Data : 2.6.1
DEBUG: Firebase   : 3.2.0
DEBUG: EmberFire  : 2.0.1
DEBUG: -------------------------------
Ember FastBoot running at http://[::]:3000
```

and visit any page that loads data through Emberfire

### Expected behavior

Fastboot loads the data and renders the page.

### Actual behavior

Fastboot fails with `Error while processing route: index The XMLHttpRequest compatibility library was not found.`

This error message comes from `bower_components/firebase/firebase.js`, but that file's source is obfuscated, making it difficult to debug further. Is there an unobfuscated version of the current `firebase.js` lib available? It used to be possible to access [`firebase-debug.js`](https://cdn.firebase.com/v0/firebase-debug.js) but the [current location of firebase.js](https://www.gstatic.com/firebasejs/3.2.0/firebase.js) doesn't seem to have a [debug version](https://www.gstatic.com/firebasejs/3.2.0/firebase-debug.js) available.

**Comment by gabrielgrant** [comment]
This problem seems to stem from the bower version of the firebase lib (understandably) not including the code to replace  XHR on node. Patching EmberFire to pull in the Node-compatible version of firebase (using `FastBoot.require('firebase')`) overcomes that. But it seems that won't serve as a substitute for complete support, since [the Firebase v3 JS lib is not longer isomorphic] (https://groups.google.com/forum/#!topic/firebase-talk/ZuIt7o6WwQI).

It seems most (all?) of the incompatibilities are in the auth-related code, so it may be possible to work around this for when Fastboot will only be used to load publicly-accessible data (most cases, I presume). But subbing out all the auth code seems like a fairly major undertaking, so I haven't tried that yet.

Another alternative would be to plug the missing browser API holes with Node shims, allowing the browser lib to run unmodified. For XHR, this should be fairly easily doable (a [couple](https://github.com/pwnall/node-xhr2) [libs]( https://github.com/driverdan/node-XMLHttpRequest) already seem to support most of the API). But unfortunately the v3 auth (even for email/password) seems to to be way more complex than the old GET request to `https://auth.firebase.com/v2/YOUR-DB-NAME/auth/password` (it appears to involve creating an iframe and `postMessage`ing back the data), so that will still cause problems.

Hoping this may work with EmberFire 1.x/Firebase v2 more easily.

**Comment by oskarrough** [comment]
Perhaps https://github.com/tomdale/ember-network can help? Would love to see FastBoot support with EmberFire.

**Comment by erkarl** [comment]
I'm also very interested in FastBoot support. Due to time constraints I gave up at 

```
DEBUG: -------------------------------
DEBUG: Ember      : 2.4.6
DEBUG: Ember Data : 2.7.0
DEBUG: Firebase   : 2.4.2
DEBUG: EmberFire  : 1.6.6
DEBUG: -------------------------------
Ember FastBoot running at http://[::]:3000

/Users/ar/Projects/boilerplate-front/dist/fastboot/vendor.js:95530
    throw new Error("No transports available");
Error: No transports available
    at [object Object].fb.realtime.TransportManager.initialTransport (/Users/ar/Projects/boilerplate-front/dist/fastboot/vendor.js:95530:11)
```

In theory this should work since Firebase v2 is isomorphic.

**Comment by 20v100** [comment]
+1 for having Emberfire be fastbootable

**Comment by rwwagner90** [comment]
I put up a PR for fastboot support, if people can go thumbs up it and/or comment on it, perhaps we can move toward getting it merged in! https://github.com/firebase/emberfire/pull/419

**Comment by dweremeichik** [comment]
@oskarrough using ember-network would require the main firebase.js file to use fetch instead of XMLHttpRequest. They certainly could do this, and it would enable the ability to use the ember-network addon,  however I believe that fetch is still "experimental". Also they would have to pollyfill it for browser compatibility; not sure that they would want to do that either. Could be worth asking though.

**Comment by oskarrough** [comment]
@dweremeichik let's try to ask @tstirrat.

**Comment by rwwagner90** [comment]
@oskarrough @dweremeichik I approve of this 👍

**Comment by jamesdaniels** [comment]
@oskarrough @dweremeichik @rwwagner90 I'm working with @tstirrat and taking a peek at getting some fastboot support together. I am looking at ember-network; hopefully should make some headway soon.

**Comment by gvelesandro** [comment]
@jamesdaniels, thank you. Please keep us posted!

**Comment by rwwagner90** [comment]
Thanks @jamesdaniels and @tstirrat! Really looking forward to this 😄

**Comment by tstirrat** [comment]
#419 we're working on this, expecting that we will have support for fastboot soon including data retrieval, however we don't expect the first fastboot compatible release will have fastboot auth session support.
