### ISSUE TITLE
Plan for Firebase 2.x support (EmberFire v1.x)

### ISSUE THREAD

**Issue by gabrielgrant** [firebase/emberfire#411]
Due to a number of missing features and incompatibilities in Firebase v3, it looks like we may need to stick with v2 for foreseeable future. Fortunately, we've been assured that [v2 will be supported "for a long time to come"](https://groups.google.com/d/msg/firebase-talk/ZuIt7o6WwQI/0QB0Xx2xGwAJ). Can the same be said for EmberFire 1.x? What does that support look ilke? Is it just not turning off the lights? Or will potential security issues, bugs, and/or new features continue to be developed? 

Whatever the answers, it would be great if that info could be made clear in the ["selecting your version of EmberFire" discussion within the README](https://github.com/firebase/emberfire#compatibility)

FWIW the biggest issue seems to be the [removal of all auth methods other than service accounts from the v3 Node lib](https://firebase.google.com/support/release-notes/js#auth_5): as far as I can tell, this makes it impossible for a node-based command line client to work.

Also, it seems like [Fastboot support may only work on v2 for the same reason](https://github.com/firebase/emberfire/issues/410#issuecomment-233018007)

**Comment by tstirrat** [comment]
I will consider porting critical priority bug fixes back to EmberFire 1.6.x but it will be somewhat of a cherry-pick and manual process.

**Comment by tstirrat** [comment]
The adapter code should be portable without much hassle, because the means to get the firebase ref is hidden in the `firebase` service.

Torii adapter fixes wont port as easily.

**Comment by jamesdaniels** [comment]
I'm going to close this for now. If anything critical breaks, please open a new issue.
