### ISSUE TITLE
Catching Errors/Error Handling - createUserWithEmailAndPassword method

### ISSUE THREAD

**Issue by jpguzman** [firebase/emberfire#415]
Thanks @tstirrat for sharing the auth.createUserWithEmailAndPassword method on this issue (https://github.com/firebase/emberfire/issues/390).
It works great, and by default, errors show up in the console. But the problem is, my custom error callbacks aren't always firing. It only fires if both the email and password field is set.

Example of the default console log: 
_Error: createUserWithEmailAndPassword failed: First argument "email" must be a valid string._

I've tried two different approaches, but neither seems to work.
```
auth.createUserWithEmailAndPassword(email, pass).then(function(userResponse) {
  // Create Record in Store
}).catch(function(error) {
  console.log('test');
}); 
```
and
```
auth.createUserWithEmailAndPassword(email, pass).then(function(userResponse) {
  // Create Record in Store
}, function(error){
  console.log('test');
});
```

Is this a bug? If so, does it have anything to do with the recent angularFire update?
https://github.com/firebase/angularfire/releases/tag/v2.0.1

**Comment by jpguzman** [comment]
I fixed the problem by giving both the email and password values an empty value of ''. 
Now the callback fires. Weird.

**Comment by ericel** [comment]
Any solution to this yet? I get the same  error!

**Comment by ecommerce-technician** [comment]
Nice, having the same problem

**Comment by Nishkixs** [comment]
I am having the same issue. I'm confused where I should be setting the email and password to empty values. Below is my code.


`import Ember from 'ember';

export default Ember.Controller.extend({
  firebaseApp: Ember.inject.service(),

  actions: {

    createUser(email, pass) {
      const auth = this.get('firebaseApp').auth();
      auth.createUserWithEmailAndPassword(email, pass).then((userResponse) => {
        const user = this.store.createRecord('user', {
          id: userResponse.uid,
          email: userResponse.email
        });
        return user.save();
      });
    }

  }
});`

**Comment by tstirrat** [comment]
See the docs here for [createUserWithEmailAndPassword](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#createUserWithEmailAndPassword).

The method should return a promise. You should be seeing the code enter the `.catch()` block when there is an error. If not, make sure you are up to date with the `firebase` SDK in your `package.json`.

The error is suggesting that you are passing something other than a string to the action. Very likely you are passing the value `undefined`. Use `console.log` or a debug breakpoint to verify the value for `email` inside the `createUser` action.

How are you calling the action `createUser` from your template? You need to pass two parameters to the action in the template, perhaps these are undefined.

**Comment by eldiyar7** [comment]
You can use Promise.resolve() method : 
[](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)

**Comment by shaniba** [comment]
please help to solve this issue 
my code is
signup()
{
  this.firebaseauth.auth.createUserWithEmailAndPassword(this.email,this.password).then( data=>
  {
    console.log("user registered suucessfully",data);
  })
  

}
