### ISSUE TITLE
Trying to link user with data by appending child path

### ISSUE THREAD

**Issue by vinamelody** [firebase/emberfire#418]
Hi, my Firebase data only has 1 user right now with data structure like this:

```
root {
  fxJXvLoL9gezsXLOSBc50KqVlb43 {
    books {
      -KOJVTFtYUBZA1jWE5ZH: {
        title: "Some title"
        qty: 5
       },
      -KOJd9MSdA3cpBspHnKo {
         title: "Another title"
         qty: 2
       },
   }
}
```

Before adding the userID (fxJXvLoL9gezsXLOSBc50KqVlb43) , I can query this book using

```
import Ember from 'ember';

export default Ember.Route.extend({
	model: function() {
		return this.store.query('book', {
			orderBy: 'qty',
			limitToLast:3
		});
	}
});

```

But with the addition of UserID (fxJXvLoL9gezsXLOSBc50KqVlb43)
the code no longer works.

How can I hard code the path to add only for this one UserID?

Thanks for your help!

**Comment by keithkelly** [comment]
I think that flatting out the data structure would work best. So I think your data structure would end up looking like this:

```
books: {
   -KOJVTFtYUBZA1jWE5ZH: {
     title: "Some title"
     users: {
       fxJXvLoL9gezsXLOSBc50KqVlb43: true
     },
     qty: 5
   },
   -KOJd9MSdA3cpBspHnKo: {
     title: "Another title",
     users: {
       fxJXvLoL9gezsXLOSBc50KqVlb43: true
     },
     qty: 2
   }
},
users: {
   fxJXvLoL9gezsXLOSBc50KqVlb43: {
     books: {
       -KOJVTFtYUBZA1jWE5ZH: true,
       -KOJd9MSdA3cpBspHnKo: true
     }
   }
}
```

You will need to hasMany relationships to your models.

Books model
```
import Model from 'ember-data/model';
import { hasMany } 	from 'ember-data/relationships';

export default Model.extend({
	...
	users: hasMany('user')
});
```

Users model
```
import Model from 'ember-data/model';
import { hasMany } 	from 'ember-data/relationships';

export default Model.extend({
	...
	books: hasMany('book')
});
```

How to flatten the data and the reasons why are explained here in the [Firebase Docs](https://firebase.google.com/docs/database/web/structure-data#flatten_data_structures).

**Comment by tstirrat** [comment]
If you absolutely cannot change the data structure.. and **all** books are **always** under the key `fxJXvLoL9gezsXLOSBc50KqVlb43`, you can override the pathForType in your books adapter:

```js
// adapters/book.js
import FirebaseAdapter from 'emberfire/adapters/firebase';

export default FirebaseAdapter.extend({
  pathForType(modelName) {
    const originalPath = this._super();
    return 'fxJXvLoL9gezsXLOSBc50KqVlb43/' + originalPath;
  }
});
```

Keep in mind, this will store EVERY book under that `fxJXvLoL9gezsXLOSBc50KqVlb43/books`.

If, however, you actually just want each user to have their own books stored directly under them, you could use [embedded objects](https://github.com/firebase/emberfire/blob/master/docs/guide/relationships.md#embedded).

e.g.

```js
{
  users: {

    user1: {
      name: 'bob',
      books: {
        -KOJVTFtYUBZA1jWE5ZH: { ... },
      }
    },

    user2: {
      name: 'steve',
      books: {
        -KOJVTFtYUBZA1jDFSXZ: { ... },
      }
    },
  },
}
```

You would do that with the following changes to the user model and serializer:

```js
// app/models/user.js
import DS from 'ember-data';
export default DS.Model.extend({
  // ...
  books: DS.hasMany('book', { async: false }),
});

// app/serializers/user.js
import FirebaseSerializer from 'emberfire/serializers/firebase';
export default FirebaseSerializer.extend({
  attrs: {
    books: { embedded: 'always' },
  }
});
```
