### ISSUE TITLE
Observer are being triggered left and right when a model is saved, even if no value have been changed.

### ISSUE THREAD

**Issue by olivierchatry** [firebase/emberfire#420]
### Version info

```
DEBUG: -------------------------------
DEBUG: Ember             : 2.7.2
DEBUG: Ember Data        : 2.7.0
DEBUG: Firebase          : 3.3.0
DEBUG: EmberFire         : 2.0.1
DEBUG: jQuery            : 2.2.4
DEBUG: Ember Simple Auth : 1.1.0
DEBUG: -------------------------------
```

### Test case

Save any kind of model twice.

### Steps to reproduce

Save any kind of model twice.

### Expected behavior

Not observer should be called ( or property update ) on the second save, since no value have been changed.

### Actual behavior

Observer are triggered, which make everything either very slow or not practical at all. You multiply that by the fact that relationships are saved on a different pass, and you obtain a callback nightmare.

**Comment by tstirrat** [comment]
2.0.2 is released with #425, please re-open if there are any other issues.
