### ISSUE TITLE
Unable to create belongsTo/readOnly relationship

### ISSUE THREAD

**Issue by bfeltman** [firebase/emberfire#422]
Hello,

I'm trying to create a belongsTo/readOnly relationship between two models.

For example I have a registration and variant models.

The registration model contains
variant: belongsTo('variant', { async: true})

While the variant model just has:
registration: attr()

When I try to save the registration only the properties without the relationship get saved.  The variant property is not saved.

I think this should be possible but I'm not sure if I'm doing something wrong or if this is a bug?

Any help would be appreciated.

Version numbers below.  

Thank you

DEBUG: -------------------------------
DEBUG: Ember      : 2.5.1
DEBUG: Ember Data : 2.7.0
DEBUG: Firebase   : 3.2.1
DEBUG: EmberFire  : 0.0.0
DEBUG: jQuery     : 2.2.4
DEBUG: -------------------------------

**Comment by tstirrat** [comment]
Hey, are you saving the variant first, and then saving the registration model?

Try also setting `{async: true, inverse: null}` just to be sure there isnt some Ember Data relationship magic getting in the way.

**Comment by bfeltman** [comment]
I did get this worked out by using the inverse: null.

Thanks for the response.

Brandon

Brandon Feltman
LinkedIn <https://www.linkedin.com/profile/view?id=109506817>

This information is confidential and intended solely for the use
of the individual or entities to whom it is addressed. If you have
received this email in error please notify the sender.
