### ISSUE TITLE
Using Torii - session service doesn't inject into routes/controllers

### ISSUE THREAD

**Issue by thedig** [firebase/emberfire#424]
Have pored over several tutorials for an EmberFire / Torii setup and am not able to get the `session` service to work at all. Is a step missing or is there possibly an issue with newer versions of EmberJS when injecting the session service?

`environment.js`
```
module.exports = function(environment) {
  var ENV = {
    ...
    firebase: {
      apiKey: '',
      authDomain: '',
      databaseURL: '',
      storageBucket: ''
    },
    torii: { sessionServiceName: 'session' },
    ...
  };
}
```

`app/torii-adapters/application.js`
```
import Ember from 'ember';
import ToriiFirebaseAdapter from 'emberfire/torii-adapters/firebase';

export default ToriiFirebaseAdapter.extend({
  firebase: Ember.inject.service()
});
```

`routes/application.js`
```
import Ember from 'ember';

export default Ember.Route.extend({
  beforeModel: function() {
    return this.get("session").fetch().catch(function() {});
  },
  ...
}
```

Browser console when visiting application route:
```
ember.debug.js:28058Error while processing route: index Cannot read property 'fetch' of undefined TypeError: Cannot read property 'fetch' of undefined
```

Guides consulted while trying to sort this out: 
http://www.programwitherik.com/emberjs_2-0_example_app_with_firebase/
http://www.danielgynn.com/third-party-auth-in-ember-with-firebase/

Package versions - 
    "ember-cli": "2.3.0",
    "emberfire": "2.0.1",
    "ember": "~2.3.1",
    "firebase": "^3.0.0"

**Comment by jamesdaniels** [comment]
You'll need to inject the session service.

```
import Ember from 'ember';

export default Ember.Route.extend({
  session: Ember.inject.service(),
  beforeModel: function() {
    return this.get("session").fetch().catch(function() {});
  },
  ...
}
```

That should work, LMK if you continue to have issues.

**Comment by thedig** [comment]
I tried doing this with explicitly injecting the session, to which it complained there was no such service.

Also all examples of how to use Torii I found imply that session is already implicitly injected.  Please see: https://www.danielgynn.com/third-party-auth-in-ember-with-firebase/

**Comment by erichiggins** [comment]
I'm having this same issue with a brand new ember app/install. Injecting the session service as per @jamesdaniels suggestion doesn't fix the problem.  Could there be a version compatibility issue between emberfire and torii?

**Comment by erichiggins** [comment]
I think I found the issue. I had installed `ember-simple-auth`, which is no longer needed and causes this to break. Removing this npm package allowed everything to work as expected.

**Comment by keanedawg** [comment]
A bit late but that was it for me to eric
