### ISSUE TITLE
[Proposal] Add support for using filters and limits when querying

### ISSUE THREAD

**Issue by rmmmp** [firebase/emberfire#433]
So right now, we can't combine filters (`startAt`, `endtAt`, `equalTo`) with limits (`limitToFirst`, `limitToLast`). If we do, we get the `Error: Query: Can't combine startAt(), endAt(), and limit(). Use limitToFirst() or limitToLast() instead.`

I believe this error happens when we begin the query with a limit and not a filter.  I checked the adapter and it seems the `applyQueryToRef` forces the query to use limits first then filters.

```
['limitToFirst', 'limitToLast', 'startAt', 'endAt', 'equalTo'].forEach(function (key) {
  if (query[key] || query[key] === '' || query[key] === false) {
    ref = ref[key](query[key]);
  }
});
```

I believe changing it up to have filters first then limits would bypass the error. Like this:

```
['startAt', 'endAt', 'equalTo', 'limitToFirst', 'limitToLast'].forEach(function (key) {
  if (query[key] || query[key] === '' || query[key] === false) {
    ref = ref[key](query[key]);
  }
});
```

I'm not sure if there's any downside to this method. Has this been thought up before and scrapped because it's bad?

**Comment by tstirrat** [comment]
There is no particular reason why I looped through the methods in that order in the first place. We should definitely apply them in the order you suggested, thanks!

Care to make a PR? If so, please include a breaking test that highlights the current error, and shows that it is fixed by the change.

**Comment by rmmmp** [comment]
Okay. I'll try to get something done by the weekend.

**Comment by brendanoh** [comment]
@rmmmp this is awesome. Thanks so much for figuring this out. Can't wait to use it.
