### ISSUE TITLE
DEPRECATION: `Enumerable#contains` is deprecated, use `Enumerable#includes`

### ISSUE THREAD

**Issue by brendanoh** [firebase/emberfire#436]
DEPRECATION: `Enumerable#contains` is deprecated, use `Enumerable#includes` instead. [deprecation id: ember-runtime.enumerable-contains] 
See [HERE](http://emberjs.com/deprecations/v2.x#toc_enumerable-contains) for more details.
### Versions

```
Ember Inspector 2.0.3
Ember                   2.8.1
Ember Data          2.8.1
Firebase                    3.4.0
EmberFire           0.0.0  It is actually pointing at #MASTER
jQuery                  3.1.1
```
### Steps to reproduce

Use with version of Ember and deprecations occur.

**Comment by jamesdaniels** [comment]
Thanks for the patch @oskarrough
