### ISSUE TITLE
Redirect when databaseURL have 403 (Forbidden) error

### ISSUE THREAD

**Issue by absemetov** [firebase/emberfire#449]
How to redirect to error page?

Thith code work after firebase connection timeout

/routes/application.js
````
import Ember from 'ember';

export default Ember.Route.extend({
  beforeModel() {
    var page = this;

    Ember.$.ajax({
      url: 'https://someurl.firebaseio.com/.json',
      success: function () {
        page.transitionTo('/');
      },
      error: function () {
        page.transitionTo('error-page');
      }
    });

  }
});

````

**Comment by tstirrat** [comment]
That's a question for Ember, not for EmberFire.

See the docs here: https://guides.emberjs.com/v2.8.0/routing/redirection/

**Comment by absemetov** [comment]
I need adapter failed event. Because beforeModel() waite model data.
PS: I am from Crimea in this territory google products dont work (sanktions)

**Comment by tstirrat** [comment]
I'm sorry, I don't understand. The code you have written looks correct.

You want to redirect to `error-page` when `Ember.$.ajax` returns an error?

**Comment by absemetov** [comment]
I would like to check in the adapter if databaseURL forbidden.

**Comment by tstirrat** [comment]
If you set your security rules to deny access:

```json
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
```

When you are using REST api, then you will get a 401 error:

```
$ curl -i https://your-firebase-db.firebaseio.com/.json

HTTP/1.1 401 Unauthorized
Server: nginx
Date: Wed, 19 Oct 2016 20:38:32 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 36
Access-Control-Allow-Origin: *
Cache-Control: no-cache

{
  "error" : "Permission denied"
}
```

This should throw an error when using `Ember.$.ajax`.

Is the code in your `error` block executing?

**Comment by absemetov** [comment]
No this code dont work i dont access https://your-firebase-db.firebaseio.com/.json my ip address bloking.

If I use VPN this code work.

**Comment by tstirrat** [comment]
Is it timing out?

Try putting a `timeout` value and a `complete` handler:

```js
    Ember.$.ajax({
      url: 'https://someurl.firebaseio.com/.json',
      timeout: 20000, // milliseconds
      success: () => this.transitionTo('/'),
      error: () => this.transitionTo('error-page'),
      complete: () => console.log('complete'),
    });
```

**Comment by absemetov** [comment]
Yes, thanks!
