### ISSUE TITLE
Acceptance Test Permission Issue

### ISSUE THREAD

**Issue by rmmmp** [firebase/emberfire#453]
### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 2.8.3
DEBUG: Ember Data : 2.9.0
DEBUG: Firebase   : 3.5.3
DEBUG: EmberFire  : 2.0.4
DEBUG: jQuery     : 3.1.1
DEBUG: -------------------------------
```

### Steps to reproduce

Create an acceptance test with offline ref helpers.

### Expected behavior

Should be able to do stuff with Firebase (e.g. read and write).

### Actual behavior

I'm getting a `Client doesn't have permission to access the desired data.`

### Possible solution

It seems that the `create-offline-ref.js` helper has `export const DEFAULT_NAME = '[EmberFire offline test app]';` while the firebase service has `export const DEFAULT_NAME = '[EmberFire default app]';`.

I believe this is causing to stub `[Ember offline test app]` Firebase instance but the app is actually using `[EmberFire default app]`.

I think we should probably scrap that `DEFAULT_NAME` and just use the built-in default in Firebase which is `[DEFAULT]` as indicated in the [docs](https://firebase.google.com/docs/reference/js/firebase#.initializeApp) or change the offline ref to use the same name in the service.

[SO reference](https://stackoverflow.com/questions/38114609/ember-emberfire-firebase-3-acceptance-test)

**Comment by tstirrat** [comment]
I'm thinking we should scrap the names too. I think I over-engineered that part at the time.
