### ISSUE TITLE
auth.signInWithEmailAndPAssword success -> don't change session.isAuthenticated

### ISSUE THREAD

**Issue by XavG** [firebase/emberfire#455]
Hi,

So I confiure my Ember projetc with simple auth ember, but when I deployed my app with firebase hosting, the local auth didn't work anymore... :(

So I configure the firebase authentification (with torii, etc..). Now it's working !!
I mean the authentification : 

> 
> auth.signInWithEmailAndPassword(identification, password)
> 				.then(function (req, response) {
> 					_this.set('session.session.isAuthenticated', true);
> 					console.log('authentification goes well');
> 					_this.transitionTo('vehicule');
> 				})
> 				.catch(function (error) {
> 					// Handle Errors here.
> 					var errorCode = error.code;
> 					var errorMessage = error.message;
> 					console.log(errorCode + errorMessage);
> 				});
> }

I receive the message "authentification goes well' but NOTHING happen.. The session.isAuthenticated doesn't come true :/ So I stay block in the login page !!
Thank for helping me :) 

Ember 2.9
Emberfire: 2.0.4

**Comment by tstirrat** [comment]
Check out docs on [authentication](https://github.com/firebase/emberfire/blob/master/docs/guide/authentication.md).

We use torii for auth within Ember, so you should use torii to open the session:

```js
// in your route
this.get('session').open('firebase', {
  provider: 'password',
  email: 'test@example.com',
  password: 'password1234'
}).then((session) => {
  console.log(session.currentUser);
});
```
