### ISSUE TITLE
Create user Email/Password Auth method

### ISSUE THREAD

**Issue by ivangrimaldo** [firebase/emberfire#459]
Hello every one, I'm trying to create a user management area in my app, but something is wrong. I'm using the basic method in in the firebase documentation **firebase.auth().createUserWithEmailAndPassword(email, password)** but time to execute the action an error displays

``` javascript
firebase.js:50 Uncaught Error: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp()
```

I was searching in the guides and the torii provider for the implementation but nothing shows related with the user admin.

I try to find the auth using **this.get('auth')** as the session object but return undefined. Here is my code.

```javascript
addUser () {
      var that = this,
          ctrl = that.get('controller');
     //Here is where throw the error
    //Even I try to use that.get('auth')
      firebase.auth()
        .createUserWithEmailAndPassword(ctrl.email, ctrl.password)
        .catch(function(error){
          Ember.set(that.currentModel, 'error', true);
          Ember.set(that.currentModel, 'errorMessage', error.message);
        });
    }

```

Thank you for the help!

**Comment by ivangrimaldo** [comment]
I found the issue, in the future reference you can add an example hoy to inject the service to work with the object firebase, here the solution:

``` javascript
firebaseApp : Ember.inject.service(), //Here need to inject the service, use the convention that use when you 
  actions:{
    addUser () {
      var that = this,
          ctrl = that.get('controller');
      that.get('firebaseApp').auth()
        .createUserWithEmailAndPassword(ctrl.email, ctrl.password)
        .catch(function(error){
          Ember.set(that.currentModel, 'error', true);
          Ember.set(that.currentModel, 'errorMessage', error.message);
        });
    }
```

Sorry for bother and hope this will help others

**Comment by jamesdaniels** [comment]
We should cover this in our docs, we only really mention social sign in

**Comment by ivangrimaldo** [comment]
Well I think that I'm doing something wrong but I want to find the answer. Let me explain my self.

I need create users, but every time I create a user, the firebase login to the new user, so I lost my session,  like if I "sign in" as a new user, but I just want to create the user. I found a solution but I'm not sure if that solution is the best.

Here is the post [Create user manually in firebase](http://stackoverflow.com/questions/37553362/firebase-create-user-manually).

Here explain that I need a create a new context using the next code:

```javascript
var authApp = firebase.initializeApp({
  // ...
}, 'authApp');
var detachedAuth = authApp.auth();

detachedAuth.createUserWithEmailAndPassword('foo@example.com', 'asuperrandompassword');
```

- **First question:** is that a good practice?
- **Second question:** emberfire or torii has a method to create a new context for create a new user?
- **Third question:** the ``` this.get('firebaseApp').initializeApp()``` doesn't exist, How can I inject the instance of firebase to create the new context?

I think is so much info but I really search a lot but I didn't find much info. Sorry for reopen it.

**Comment by jamesdaniels** [comment]
So what I'm gathering is that you intend to create users, rather than support a sign-up flow?

If that's the case, you'll want to do it on a backend + use our Admin SDK https://firebase.google.com/docs/auth/admin/manage-users

**Comment by ivangrimaldo** [comment]
Is not possible to me use node, I'm using the firebase hosting for the app, I need create a "super admin" user has the ability to create other users with profiles.

Is that possible?
thank you for your help

**Comment by jamesdaniels** [comment]
Right now the user management APIs are only available for the Node Admin SDK.

An alternative is a bit of a different design; where you have a users collection in the Real-time Database where you can store meta-data. It would not however, allow you to set an invitees password for them.

**Comment by ivangrimaldo** [comment]
Thank you, I'm re-thinking how to create a user in a better way.

**Comment by jamesdaniels** [comment]
Feel free to get in touch if you have any more questions.

**Comment by jshwartz** [comment]
So if I am using firebase hosting + authentication + realtime database, and I have user metadata stored in the database as an associated database user record, then is there any way for admins to create and delete users? I suppose to delete users the admin can just sign-in directly to firebase and delete the user record and the associated database user record, but creating a user with this method would be a bit cumbersome because you have to copy and paste in the user ID.

**Comment by ivangrimaldo** [comment]
@jshwartz at this time is kind of possible, but when the user is created the session is lost and need to relogin as admin user. Is kind of a pain I solve the issue creating a users record, when I storage a new user I send a "confirmation email" the landing page is a form to "create a password" but is the sign in form, before create the user I check in the table if the "invitation code" exist, if true I just continue and delete the code from the database. But I still think that is a vulnerable step, is kind of wierd.

**Comment by es6Test** [comment]
When I do `      that.get('firebaseApp').auth()` I get `undefined`

**Comment by es6Test** [comment]
the object I get back is kinda weird
![image](https://user-images.githubusercontent.com/13809207/27538208-d6d9895a-5a6e-11e7-853f-ee01cebad0ce.png)

**Comment by rmmmp** [comment]
@es6Test, looks like you're injecting `firebase` service not `firebaseApp`.

**Comment by es6Test** [comment]
Ah, so firebaseApp is the name, this really needs to be added to the docs on the front page, caused a days worth of confusion.
