### ISSUE TITLE
transitionTo doesn't work in user creation

### ISSUE THREAD

**Issue by ivangrimaldo** [firebase/emberfire#460]
Hi everyone.

I'm having a little issue when I create a user, in "then" callback doesn't change to index route until I refresh the page, can you help me please? I think I'm doing as the torii-emberfire-firebase documentation.

````javascript

that.get('firebaseService')
          .auth()
          .createUserWithEmailAndPassword(
            ctrl.email,
            ctrl.password
          )
          .then(function(){
            that.transitionTo('/');
          })
          .catch(function(error){
            Ember.set(that.currentModel, 'flag', true);
            Ember.set(that.currentModel, 'error', error.message);
          })
````
Thank you for your help.

**Comment by oskarrough** [comment]
In Ember there are (at least) two ways to transition. From a controller you use `transitionToRoute` and from route you use `transitionTo`. Is this the issue?

**Comment by ivangrimaldo** [comment]
Hi @oskarrough thanks for answer, but I use the to ways and neither works, just simply not transition to any route.

**Comment by ivangrimaldo** [comment]
I saw the problem, is related with the session management, I'm transitioning to authenticatedRoute so, ember is dispatching the method accessDenied, and this method return me to the login route.

But if you see in the image, the session was saved in the local storage, but the storage never been set in the ember context. I'm looking in the torii documentation but the documentation says: 

      // The returned object is merged onto the session (basically). Here
      // you may also want to persist the new session with cookies or via
      // localStorage.

![screen shot 2016-12-19 at 10 52 57 am](https://cloud.githubusercontent.com/assets/529750/21319132/fa23b6a8-c5d9-11e6-8cef-63b3f54974f4.png)

**Comment by oskarrough** [comment]
The last screenshot says 'no session available'. You might need to `session: Ember.inject.service()` where you're accessing it.

Where is the code from your first post?

**Comment by ivangrimaldo** [comment]
the code is in the routes/login.js file, I injected and is working correctly the session object and is in localStorage but the session stills unset

**Comment by oskarrough** [comment]
If the `/` route is the one requiring authentication the problem might be that you're transitioning after creating a user and NOT after signing in. Since emberfire uses Torii under the hood, are you "opening the session" as well?

**Comment by ivangrimaldo** [comment]
hi @oskarrough the problem is related with the process of the user creation, at the moment when I create the user my session is deleted and re enter as the new user so the transition made return me at the same route.

https://github.com/firebase/emberfire/issues/459#issuecomment-267138839

**Comment by tonycoco** [comment]
You'll probably want something like:

```js
createUser(email, password) {
  const route = this;
  const auth = route.get('firebaseApp').auth();

  auth.createUserWithEmailAndPassword(email, password).then((userResponse) => {
    route.get('session').open('firebase', {
      provider: 'password',
      email: email,
      password: password,
    }).then(() => {
      route.transitionTo('something-new-here'); // FIXME
    });
  }, (errorResponse) => {
    alert(errorResponse.message);
  });
}
```

**Comment by ivangrimaldo** [comment]
Hi  @tonycoco I'll test, I already finish the project using a middleware to invite the user to "sign in" checking a provisional token generated with the email invitation. But I think will work let me check it, thanks

**Comment by oskarrough** [comment]
@ivangrimaldo did you get it to work and can we close the issue here now?

**Comment by dirkdirk** [comment]
I just solved this issue myself similarly to @tonycoco suggestion:
`  createEmailUser() {
    console.log('--> createEmailUser() firing');
    let store = this.get('store');
    let userEmail = this.get('loginEmail');  // from login form
    let userPw = this.get('loginPw');          // from login form
    let timeStamp = Date.now();
    return this.get('firebaseApp').auth()
      .createUserWithEmailAndPassword(userEmail, userPw)
      .then((user) => {
        let userId  = user.uid;
        let newUser = store.createRecord('user', {
                            id: userId,
                            accountCreated: timeStamp,
                            lastLogin: timeStamp,
                            email: userEmail
                      });
        newUser.save()
                .then(() => {
                  console.log('    auth user');
                  this.get('session').open('firebase', { provider: 'password',
                                                         email: userEmail,
                                                         password: userPw })
                      .then(() => {
                        console.log('    transitionToRoute user');
                        this.transitionToRoute('user');
                      });
                 })
                .catch(error => {
                  console.log(' -- createEmailUser save error:');
                  console.log(error.message);
                });
      })
      .catch((error) => {
        console.log(' -- signIn error.message:');
        console.log(error.message);
      });
  },`
