### ISSUE TITLE
hasMany embedded records won't save if parent has adapter with custom pathForType

### ISSUE THREAD

**Issue by levint** [firebase/emberfire#466]
### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 2.10.2
DEBUG: Ember Data : 2.10.0
DEBUG: Firebase   : 3.6.4
DEBUG: EmberFire  : 0.0.0
DEBUG: jQuery     : 3.1.1
DEBUG: -------------------------------
```

### Problem

When trying to save a record containing `hasMany` embedded records, the embedded records will fail to save. This occurs whenever the parent record adapter has a custom `pathForType()` value. For example:

`content-type` is the parent record and has many embedded `controls`. The `content-type` record is stored in a path different than the default firebase `root/contentTypes`.

```
// adapters/content-type.js
...
export default FirebaseAdapter.extend({
  ...
  pathForType() {
    return `management/${this.get('session.currentUser.uid')}/content-types`;
  }
});
```

```
// models/content-type.js
...
 export default DS.Model.extend({
  name: DS.attr('string'),
  controls: DS.hasMany('control', {async: false, inverse: null})
});
```

```
// serializers/content-type.js
...
export default FirebaseSerializer.extend({
  attrs: {
    controls: {embedded: 'always'}
  }
});
```

**The saving of embedded record logic does not respect the parent's pathForType.**

### Expected behavior

Embedded records should be save under its parent. In my case, each `control` record should be saved with a path similar to `management/$userId/content-types/$contentTypeId/controls/$controlId`.

### Actual behavior

Firebase will generate an error similar below upon trying to save the embedded records.
`update at /contentTypes/-Ka14NscdoZJOhcGzabe/controls/-Ka1ACNO5RtNKp3wZhh_ failed`

**Comment by bentacles** [comment]
I'm experiencing this too. Any resolution to this?
