### ISSUE TITLE
Storing extra user info in a separate DB.

### ISSUE THREAD

**Issue by davidchalifoux** [firebase/emberfire#467]
I need to be able to store extra user data, so I plan on doing so in a separate "users" table such as:
```
users.json
{
  "user-id" : {
    "isAdmin" : false
  }
}
```

However if I used Ember to store & retrieve the data, I would end up with a table that contains an extra unique ID, because of how it gives everything a unique ID:

```
ember-users.json
{
  "ember-id" : {
    "user-id" : {
      isAdmin : false
    }
  }
}
```

This is really a lot more complex than it needs to be. I've tried to manually use Firebase instead of Ember's Data Store but I can't seem to come up with a solution. Any ideas?

**Comment by Suven** [comment]
Hey!

Just 2 ideas:

1. You could create another model with the same id as the user-id. I did that too to separate between private und public user-data. As ID I am always setting the auth-id. That way writing rules in firebase is also quite easy. Using the same id's in different places is no problem as long as they are different collections.

2. You can always access everything documented in the firebase web-docu via `firebaseApp: Ember.inject.service()`

**Comment by davidchalifoux** [comment]
Hey @Suven , thanks for the reply!
I am aware of being able to use the Firebase service without going through Ember, I guess that kind of answers my question by itself(stupid me). However, in your first idea I was not aware of having the ability of manually setting the ID of the model in Ember. I will have to give that a try! Is there perhaps any sort of documentation describing what you are doing?
Thanks!

**Comment by davidchalifoux** [comment]
Okay, so I've pretty much figured out how to do it.
(Here's some info in case other people have a similar problem)
Things to note:

- Manually call Firebase to store the extra user info(as @Suven describes in his 2nd point). When you store the info manually, make sure to format it to include the "Unique ID" which in this case is the User ID

- You can then just use the built-in Ember functions to call the data.

Here's how I called the specific user's info in my routes/application.js:
```
model: function() {
    //Get Current User ID
    const auth = this.get('firebaseApp').auth();
    const userId = auth.currentUser.uid;

    return this.store.query('users', {
        //Query specific user ID
        equalTo: userId
    });
}
```

**Comment by Suven** [comment]
Hey (:

Are you also using toorii? If so you can also always access 'session.currentUser.uid' directly. That would make your lookup just `this.store.findRecord('users', this.get('session.currentUser.uid'));`.

Also, if that was not clear, you can also use the build-in functions to create the data: `this.store.createRecord('users', { id: this.get('session.currentUser.uid'), foo: 'bar' }`.

I tend to nest all routes that require the user being logged in into one parent-route and have that handle the (re-)login-stuff in its beforeModel-hook. If the user is not loged in, I abort the transition. If he is logged in, I try to receive his default records (settings, profile, whatever), if they don't exist I'll create default ones, and make them available in my app via a service.

Hope that helps!
