### ISSUE TITLE
DEBUG: EmberFire  : 0.0.0

### ISSUE THREAD

**Issue by davidchalifoux** [firebase/emberfire#469]
_Not sure if this is already known._
So when you are running in a development environment for Ember, it console.log's the version of the dependencies, and I just noticed that there is no version set for EmberFire.
```
DEBUG: -------------------------------
Ember      : 2.10.2
Ember Data : 2.11.0
Firebase   : 3.6.4
EmberFire  : 0.0.0
jQuery     : 3.1.1
-------------------------------
```

I feel like setting a version for EmberFire would be helpful, no?

**Comment by jamesdaniels** [comment]
This is a bug in our release script, we should have it patched up next release; see #462

I'll leave this issue open till then. Thanks for the report

**Comment by dougshults** [comment]
Still open, still an issue

**Comment by tpetrone** [comment]
This is still an issue for me? Anyone else?
Tks

**Comment by davidchalifoux** [comment]
Yep, still there.

**Comment by davidchalifoux** [comment]
@jamesdaniels Mind re-opening this?

**Comment by jamesdaniels** [comment]
Tracking in #504
