### ISSUE TITLE
Undocumented difference between findAll and query

### ISSUE THREAD

**Issue by Suven** [firebase/emberfire#471]
Hey,

as discussed with @oskarrough on embers slack, there is an undocumented difference between `store.findAll('model')` and `store.query('model', {})`.

 ### query

This fetches all the data and registers child_added, child_removed and value-change-listeners. So updating, inserting and deleting data is reflected in the app.

### findAll

This fetches all the data and registers for child_added only. This has the sideeffect that value-changes on existing data will not be reflected in the store, but value-changes on newly pushed data, will be reflected. You can find this in https://github.com/firebase/emberfire/blob/master/addon/adapters/firebase.js#L349

---

To me this seems more like a bug then an undocumented feature since if you wanted to provide one way of dealing with self-updating data and one way to deal with static data, you also should not have binded the child_added event to findAll or at least only push new records once, but don't watch for valuechanges on them.

My vote would cleary go in the direction of handling findAll the same way as query.

Non the less, even if you disagree this difference should clearly be mentioned in the docs. Also the source-codes comment is misleading in this case as it states:

> After `.findAll()` is called on a modelName, continue to listen for `child_added`, `child_removed`, and `child_changed`

**Comment by jamesdaniels** [comment]
Thanks for digging into this @Suven @oskarrough, I'll carve out some time over the next couple days to look into this
