### ISSUE TITLE
Embedded HasMany delete bug

### ISSUE THREAD

**Issue by tsubik** [firebase/emberfire#475]
I found a problem with removing child objects from embedded records when using `hasMany` relationship. I think the problem is related to the `recordCache` is not being updated for embedded records hasMany relationships. Then when saving `hasMany` relationship after removing an object from object's collection, removed object is [not beign marked for deletion](https://github.com/firebase/emberfire/blob/master/addon/adapters/firebase.js#L521) because it was not cached. I will try to introduce PR soon.

### Version info

```
DEBUG: -------------------------------
DEBUG: Ember      : 2.10.2
DEBUG: Ember Data : 2.11.0
DEBUG: Firebase   : 3.6.6
DEBUG: EmberFire  : master (#2ebeab9)
DEBUG: jQuery     : 3.1.1
DEBUG: -------------------------------
```

### Test case

Simple repository to reproduce the bug: [https://github.com/tsubik/emberfire-embedded-hasmany-child-delete-bug](https://github.com/tsubik/emberfire-embedded-hasmany-child-delete-bug)

Models

`event.js`
```
export default Model.extend({
  name: attr("string"),
  expenses: hasMany("expense", { async: false }),
  users: hasMany("user", { async: false })
});
```

`expense.js`
```
export default Model.extend({
  name: attr("string"),
  event: belongsTo("event", { async: false }),
  participants: hasMany("user", { async: false })
});
```
`user.js`
```
export default Model.extend({
  name: attr("string"),
  event: belongsTo("event")
});
```

Removal code
```
remove(expense, participant) {
  expense.get("participants").removeObject(participant);
  expense.save();
}
```

### Steps to reproduce

Steps to reproduce a bug are described in above repository Readme file.

### Expected behavior

It should successfully remove child object from the database.

### Actual behavior

It is not removing the child object from the database.

**Comment by jamesdaniels** [comment]
Thanks for the report @tsubik I don't often use embedded records myself, so I haven't felt this pain. Let me get together a repro and get back to ya.
