### ISSUE TITLE
Seems like emberfire is broken with 2.11

### ISSUE THREAD

**Issue by olivierchatry** [firebase/emberfire#479]
Hello,

I just upgraded my app to 2.11, and emberfire does not seems to live update from firebase anymore. Does anyone have the same problem ?

**Comment by nsbingham** [comment]
@olivierchatry I'm experiencing the same thing on `2.0.5`

**Comment by nsbingham** [comment]
@olivierchatry if you're using `findAll` and not seeing the data update, it might be related to #471

**Comment by nsbingham** [comment]
@olivierchatry can confirm that using `query` instead of `findAll` will allow data to update when the value is changed, so it appears to be related to #471.

**Comment by olivierchatry** [comment]
I'm not sure, it works very well using ember + ember-data 2.10, in 2.11 the emberfire callback that is called when firebase receive an update message is never called. I will try to investigate more tomorrow.

**Comment by jamesdaniels** [comment]
Yeah, I just pulled in my updates to ember-try; I've been meaning to carve some time out this week to address but haven't been able to yet. @olivierchatry let us know if you find anything, if we don't cut a fix this week we should aim to set the ember-data dep to "< 2.11" :/

**Comment by olivierchatry** [comment]
Ok, I found the issue. Ember data internal code replace all call from `store.push` to the private ` store._push`, meaning that the **hook** that is installed at init by ember ( Store reopen ) will not work anymore. I will see if I can change it, but we might be better of finding a better solution than doing the reopen thing if possible.
