### ISSUE TITLE
Ember 2.11 : getting infinite rendering when loading a model with relationships

### ISSUE THREAD

**Issue by olivierchatry** [firebase/emberfire#480]
With Ember 2.11, when I load a relationships that have more than 10 elements, I get and "infinite rendering invalidation detected". 

This seems to come from adapters/firebase.js:142

```js
  _fetch(ref, log) {
    this._incrementWaiters();
    return new Promise((resolve, reject) => {

      ref.once('value', (snapshot) => {
        this._decrementWaiters();
        Ember.run(null, resolve, snapshot);

      }, (err) => {
        this._decrementWaiters();
        Ember.run(null, reject, err);
      });

    }, log);
  },
``` 

replacing by :

```js
  _fetch(ref, log) {
    this._incrementWaiters();
    return new Promise((resolve, reject) => {

      ref.once('value', (snapshot) => {
        this._decrementWaiters();
        Ember.run.scheduleOnce('afterRender', this, resolve, snapshot);

      }, (err) => {
        this._decrementWaiters();
        Ember.run.scheduleOnce('afterRender', this, reject, err);
      });

    }, log);
  },
``` 

works. I would guess it happens when we get a lot of update message at the same time, and they are called one after each other instead of being queued, anyway I will submit a pull request and you can see if you want to either fix the problem in firebase client or just fix it using ember.

**Comment by olivierchatry** [comment]
Well, seems like a lot of test are actually expecting value to get updated ASAP, not sure what to do to fix these issue.

**Comment by olivierchatry** [comment]
@jamesdaniels any chance you can publish a new version ? that would be great ( actually I'm sorry to ask, but how much time does google / firebase allows you to spend on emberfire ? I'm a bit disapointed by the speed of the release :( I mean, we still have the version number set to 0.0.0 :(.

**Comment by jamesdaniels** [comment]
@olivierchatry I'm waiting on access to our Jenkins deploy job. I haven't been given access to this yet. In the meantime perhaps @tstirrat could cut a release? Unfortunately both Tim and I have been pressed with releases of upcoming features lately + haven't spent the amount of time we'd like on the project. I'm sorry.

I am setting goals and expectations with my manager regarding time spent on (and objectives with) Emberfire, so hopefully this improves in the future.

**Comment by olivierchatry** [comment]
That would be super cool to have some love given to the project :). I 
know you are all quite busy, and I will just thank you for what you are 
doing ( and also thank for replying ).

**Comment by jamesdaniels** [comment]
2.0.6 has been cut :+1:

**Comment by olivierchatry** [comment]
Thanks a bunch !
