### ISSUE TITLE
Upgrading from 2.04 to 2.06 cause acceptance tests to fail

### ISSUE THREAD

**Issue by tpetrone** [firebase/emberfire#484]
### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 2.8.3
DEBUG: Ember Data : 2.11.1
DEBUG: Firebase   : 3.6.8
DEBUG: EmberFire  : 2.0.6
DEBUG: jQuery     : 3.1.1
DEBUG: -------------------------------
```

### Test case

I am using Emberfire along with Torii to manage user sessions.
After upgrading from `2.0.4` to `2.0.6`, all my acceptance tests that had any request to Firebase server would throw: `Uncaught Error: Assertion Failed: You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run`.

### Steps to reproduce

Upgrade from 2.04 to 2.0.6
Run any previous passing acceptance test that also has a request to Firebase server

### Expected behavior

Tests should pass

### Actual behavior

Tests are failing with: `Uncaught Error: Assertion Failed: You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run`

**Comment by zurnet** [comment]
I'm also getting an error after going from 2.0.4/2.0.5 to 2.0.6...

For example calling this worked fine:
`firebase.database.ServerValue.TIMESTAMP`

but not it cannot find: firebase

going back to 2.0.4 or 2.0.5 works fine again.
