### ISSUE TITLE
Doesn't work with FirebaseUI Web for EmberFire 2.0.6

### ISSUE THREAD

**Issue by rmmmp** [firebase/emberfire#490]
### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 2.10.2
DEBUG: Ember Data : 2.10.0
DEBUG: Firebase   : 3.7.2
DEBUG: EmberFire  : 2.0.6
DEBUG: jQuery     : 3.1.1
DEBUG: -------------------------------
```

### Steps to reproduce

Follow this guide https://gist.github.com/steven-ferguson/8eddf63123fa74066e9d92f7e829d8e9

### Expected behavior

FirebaseUI auth should work

### Actual behavior

Doesn't work. Error says `Uncaught ReferenceError: firebase is not defined`.

### Additional notes

Works with EmberFire 2.0.5. I believe it has something to do with moving Firebase from bower to npm.

**Comment by rmmmp** [comment]
Turns out the issue is with FirebaseUI library.

One part of their code is calling `firebase.initializeApp()`. However, Firebase in EmberFire is an AMD module so you need to `import firebase from 'firebase'` first which FirebaseUI isn't doing.

For a workaround, we need to set a global variable for Firebase like this:

```javascript
import firebase from 'firebase';

window.firebase = firebase;
```

**Comment by p0six** [comment]
where best to add global variables, @rmmmp ? Right now I'm setting it directly inside my controller - I figure there's gotta be a better place :D

**Comment by rmmmp** [comment]
@p0six I'd say initializer but placing it in the controller/component paired for rendering firebaseui-web should be fine too. Just note that if you do it in initializer your integration test that renders firebaseui would fail since initializers won't run in those tests. You'll need to manually set window.firebase in your test too.
