### ISSUE TITLE
(Authentication) Error: Could not create factory

### ISSUE THREAD

**Issue by pjcarly** [firebase/emberfire#493]
### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 2.12.0
DEBUG: Ember Data : 2.12.1
DEBUG: Firebase   : 3.7.3
DEBUG: EmberFire  : 0.0.0
DEBUG: jQuery     : 3.2.1
DEBUG: -------------------------------
```

### Steps to reproduce

- Create a basic Ember 2.12 app
- Connect with firebase
- Enable Google Authentication (just like this: https://github.com/firebase/emberfire/blob/master/docs/guide/authentication.md)
- Click Sign-in

### Expected behavior

Google authentication pop-up

### Actual behavior

Nothing, a Javascript error is thrown "Error: Could not create factory".
I guess it has something to do with the way that lookups are being done in the Ember Container.

Same code works without a problem with Ember 2.11.3

**Comment by laureanoarcanio** [comment]
Having the same issue here, any workaround about this ? Thanks

**Comment by mileszim** [comment]
I want to reopen this error, I am getting it again with the exact same symptoms: when the provider hash option has 'google' I get ```ember.debug.js:18015 Error: Could not create factory```

This happens on two different applications with two different structures and ways of invoking session. Both are using the latest ember, ember-cli, and emberfire if that helps

**Comment by dougshults** [comment]
Yes, same issue [here](https://github.com/firebase/emberfire/issues/501) I believe. Please re-open

**Comment by dougshults** [comment]
@mileszim I believe this is fixed in the master branch but not the ember-cli version. Using the emberfire master branch solved this for me.
