### ISSUE TITLE
Allow a base reference to be specified in the application configuration

### ISSUE THREAD

**Issue by elgordino** [firebase/emberfire#496]
To support running multiple 'applications' in the same Firebase project I would like to be able to specify a base reference that will apply to all objects created.

My specific requirement is to support my CI/CD environment which creates a new environment per branch. Unfortunately Firebase does not have an API for creating new Firebase projects and thus I am deploying multiple applications to the same Firebase instance, just under a different base path, eg:

    /master
    --/users
    --/groups
    /test
    --/users
    --/groups
    /feature1
    --/users
    --/groups

I have implemented this very simply here: https://github.com/lineupninja/emberfire/commit/af8c82da33699aeceec9a1ac50ea0d0d9d825800

Would you consider a pull request for this if I wrote test plans and updated the docs?

**Comment by jamesdaniels** [comment]
I would consider a PR, yes.
