### ISSUE TITLE
New record does not remove from store after server delete

### ISSUE THREAD

**Issue by neverfox** [firebase/emberfire#50]
I have two models, account and ticket, with the latter linking to the former via a `belongTo` (with no corresponding `hasMany`). After creating one of each, displaying them in separate tables (on different routes), I then go into Forge and blow away both records. The account record disappears from my store and app as expected. The ticket, however, sticks around. The store still thinks it's there and it's still displayed in the app. It doesn't matter the order I blow them away either. If I delete the ticket from Firebase, and leave the account, the ticket remains in my store. It also doesn't matter if I remove the `belongsTo`. To me, this is unexpected behavior.

**Comment by tstirrat** [comment]
Hey, doing a triage on bugs and I needed to re-title this :)

**Comment by tstirrat** [comment]
Just did some testing of this issue and it appears to have been fixed with the changes in #133
