### ISSUE TITLE
DEPRECATION: Using "_lookupFactory" is deprecated. Please use container.factoryFor instead.

### ISSUE THREAD

**Issue by dougshults** [firebase/emberfire#501]
Following the docs [here](https://github.com/firebase/emberfire/blob/master/docs/guide/authentication.md) but the lookupfactory error keeps showing up. 

Also checked the [deprecation](https://emberjs.com/deprecations/v2.x/#toc_migrating-from-_lookupfactory-to-factoryfor) docs but unclear of fix

https://github.com/firebase/emberfire/blob/master/docs/guide/authentication.md 

### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 2.12.1
DEBUG: Ember Data : 2.12.2
DEBUG: Firebase   : 3.8.0
DEBUG: EmberFire  : 0.0.0
DEBUG: jQuery     : 3.2.1
DEBUG: -------------------------------
```

**Comment by rmmmp** [comment]
Are you using the master branch? I think that branch already fixed this.

**Comment by dougshults** [comment]
Hm, not sure why this was closed but yes I'm using the master branch and see the fix applied [here](https://github.com/firebase/emberfire/commit/85e8f0f77797a7e0cf216e93b54f2e539ab4d053) but does not resolve.

**Comment by dougshults** [comment]
@rmmmp tyvm - using the master branch fixed this for me. Perhaps the ember cli version doesn't have this update yet? thanks again

**Comment by jamesdaniels** [comment]
@dougshults @rmmmp cut a new version with the fix, sorry for the delay
