### ISSUE TITLE
Firebase 3.x API with Emberfire 2.x fails to authenticate using Torii

### ISSUE THREAD

**Issue by ksnyde** [firebase/emberfire#503]
I am upgrading an app that has used Emberfire 1.x (and using the Firebase 2.x API) to the latest and greatest. To my great disappointment, I can not authenticate using the Emberfire/Torii combination. The error I get is:

> TypeError: Cannot read property 'open' of undefined

And more explicitly, it appears this is the code sequence that is failing:

![2017-04-28_11-06-27](https://cloud.githubusercontent.com/assets/980757/25541639/3af69f5c-2c04-11e7-829d-96191db614d9.png)

The `provider` is set to 'firebase' and the `options` is set correctly with:

    {
      provider: 'password',
      email: email,
      password: password
    }

I had seen somewhere in the discussion of other issues that some people were having problems explicitly with `ember-source` **2.13.0** so I tried reverting to **2.12.2** where it had been working with emberfire 2.x API but the problem seems to be identical.

**Comment by ksnyde** [comment]
I can now verify that moving back to Ember **2.11.3** does bring this back to a working state. That is true for emberfire 2.x and 1.x (and the corresponding Firebase version).

**Comment by Cryrivers** [comment]
I guess the mechanism for getting owner or factory has been changed in Ember 2.13.

**Comment by ksnyde** [comment]
@Cryrivers yes i believe that is right. Specifically I think they enforce the official way of doing it (now that there is one). The official is just off of Ember:

    Ember.getOwner(this).lookup('service:xxxxx');

**Comment by mileszim** [comment]
What's the status of this? Has it been updated to work with ember 2.13? Happy to submit a PR if not. Currently locked at 2.12.0, anything above that throws this exact torii error.

**Comment by gokatz** [comment]
+1

**Comment by rwwagner90** [comment]
Also seeing this issue. Perhaps related to this? https://emberjs.com/deprecations/v2.x/#toc_migrating-from-_lookupfactory-to-factoryfor

**Comment by luiscovar** [comment]
+1

**Comment by keanedawg** [comment]
+1

**Comment by mileszim** [comment]
Seems like it;s actually a torii issue, Ive started using this user's torii fork and it works perfectly on 2.13.1 https://github.com/Vestorly/torii/pull/355

**Comment by ksnyde** [comment]
Good to know. Fingers crossed the PR is brought in soon.

**Comment by Dhaulagiri** [comment]
released in 0.8.3 of torii this afternoon 🎉

**Comment by QuantumInformation** [comment]
Any ideas when ember fire will upgrade to 0.8.3?

**Comment by jamesdaniels** [comment]
@QuantumInformation I'll take a peek at this when I introduce Firebase 4.0 support, as it will have some API changes. Should have some time in the next week, though I still need to get access to our build system.

In the meantime, happy to accept PRs :)

**Comment by ksnyde** [comment]
I don't know this for sure but I had thought that the API changes were pretty non-existant between 3.x and 4.x.

**Comment by BobrImperator** [comment]
I'm still getting that error on authentication via google provider after choosing account for authentication.
"The Torii adapter must implement `open` for a session to be opened"
Ember  2.13.4
Ember Data : 2.14.9
Firebase   : 3.9.0
EmberFire  : 0.0.0
Torii 0.9.5

**Comment by jpguzman** [comment]
@jamesdaniels I'm really excited for that 4.0 support, when I saw you pushed something up earlier. :+1:
