### ISSUE TITLE
support "phone" as a provider

### ISSUE THREAD

**Issue by jmonster** [firebase/emberfire#511]
One of the Firebase features that got me psyched up was the support for Phone authentication. However, that seems to be absent from emberfire? Ideally it could work just like the existing Torii methods. So, something like...

```hbs
<button {{action "signIn" "phone"}}>Sign in via your Phone</button>
```
And whatever else is involved abstracted away to the page that is loaded in the pop-over window.

If this isn't possible or if there is a simple way to extend emberfire to support it that would be very helpful, too.

Mahalo!

**Comment by jamesdaniels** [comment]
I'm going to be taking a look at this next week :)

**Comment by colinzhang** [comment]
I'd love to hear if anyone has figured this out yet. I took a stab at including the FirebaseUI plugin as a component (based on [this gist](https://gist.github.com/steven-ferguson/8eddf63123fa74066e9d92f7e829d8e9)) but it doesn't open a popup and is giving me a lot of issues related to linking credentials with the torii provider.

Is there a timeline for built-in phone provider support in emberfire?

Appreciate any insight!

**Comment by galmi** [comment]
I have made simple provider for phone auth. It can used while it not built-in.
It using prompt window for input confirmation code. If have any ideas how can do it better, it will be great.

[https://www.npmjs.com/package/emberfire-phone](url)
