### ISSUE TITLE
Multiple filters during query?

### ISSUE THREAD

**Issue by brancusi** [firebase/emberfire#514]
### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 2.13.2
DEBUG: Ember Data : 2.13.1
DEBUG: Firebase  	3.9.0
DEBUG: EmberFire  : 2.0.7
DEBUG: jQuery     : 3.2.1
DEBUG: -------------------------------
```
Hi, I'm wondering if there is a way to add multiple filter options during a query. I am trying to achieve multi tenancy using a filter on the `organization` key as well as others at the same time. I don't see how I would do this with the options hash during query.

Thanks

**Comment by jamesdaniels** [comment]
Firebase only supports a single filter. You need to take this into account when designing your "schema".

See #432 for what we're planning on doing medium term + maybe checkout something like emberfire-utils in the meantime.
