### ISSUE TITLE
https://github.com/firebase/firebaseui-web#developer-setup

### ISSUE THREAD

**Issue by EmberJSParis** [firebase/emberfire#517]
One of the Firebase support Engineers told me that the code here https://github.com/firebase/firebaseui-web#developer-setup doesn't work with EmberJS because the EmberJS is not directly affiliated with Firebase. It seems to me strange as the code here should work independent of the framework. Is anyone tested the Authentication code of Firebase here https://github.com/firebase/firebaseui-web#developer-setup ? Thanks

PS: I got a reply to use https://github.com/rmmmp/emberfire-utils#firebaseui but is still not working, normally https://github.com/firebase/firebaseui-web#developer-setup should be independent of the framework

______________________________________________________________________

**Comment by rmmmp** [comment]
That should work. I've actually implemented a component addon for that. Check it out [here](https://github.com/rmmmp/emberfire-utils#firebaseui).

**Comment by EmberJSParis** [comment]
OK Thanks I checked and solved nothing. This is the code here https://github.com/firebase/firebaseui-web#developer-setup and I sill need the code for the landing page and the code for the routing page. Thanks for your add-on but I have the same symptoms. The code here https://github.com/firebase/firebaseui-web#developer-setup should work disregard of the framework. Where is your code for the landing page and the code for the routing page ? I tried your add-on and I got nothing Thanks

**Comment by rmmmp** [comment]
I'm not sure what your use-case is. Can you elaborate on that? The link you're showing is just to setup the developer environment which isn't what you want to do when you want to use Firebase UI Web in Ember.

At any case, if this is a bug with my addon please file an issue there. Though I don't think it's a bug but just a misunderstanding of the usage.

**Comment by EmberJSParis** [comment]
Thanks for the reply.

yes I want to setup from scratch the developer environment and write the code for the landing page like here

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Sample FirebaseUI App</title>
    
    <script src="https://cdn.firebase.com/libs/firebaseui/2.1.1/firebaseui.js"></script>
    <link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/2.1.1/firebaseui.css" />
    <script type="text/javascript">
      // FirebaseUI config.
      var uiConfig = {
        signInSuccessUrl: '<url-to-redirect-to-on-success>',
        signInOptions: [
          // Leave the lines as is for the providers you want to offer your users.
          firebase.auth.GoogleAuthProvider.PROVIDER_ID,
          firebase.auth.FacebookAuthProvider.PROVIDER_ID,
          firebase.auth.TwitterAuthProvider.PROVIDER_ID,
          firebase.auth.GithubAuthProvider.PROVIDER_ID,
          firebase.auth.EmailAuthProvider.PROVIDER_ID,
          firebase.auth.PhoneAuthProvider.PROVIDER_ID
        ],
        // Terms of service url.
        tosUrl: '<your-tos-url>'
      };

      // Initialize the FirebaseUI Widget using Firebase.
      var ui = new firebaseui.auth.AuthUI(firebase.auth());
      // The start method will wait until the DOM is loaded.
      ui.start('#firebaseui-auth-container', uiConfig);
    </script>
  </head>
  <body>
    
    <h1>Welcome to My Awesome App</h1>
    <div id="firebaseui-auth-container"></div>
  </body>
</html>

then to write the code for a route page like here

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Sample FirebaseUI App</title>
    
    <script type="text/javascript">
      initApp = function() {
        firebase.auth().onAuthStateChanged(function(user) {
          if (user) {
            // User is signed in.
            var displayName = user.displayName;
            var email = user.email;
            var emailVerified = user.emailVerified;
            var photoURL = user.photoURL;
            var uid = user.uid;
            var phoneNumber = user.phoneNumber;
            var providerData = user.providerData;
            user.getToken().then(function(accessToken) {
              document.getElementById('sign-in-status').textContent = 'Signed in';
              document.getElementById('sign-in').textContent = 'Sign out';
              document.getElementById('account-details').textContent = JSON.stringify({
                displayName: displayName,
                email: email,
                emailVerified: emailVerified,
                phoneNumber: phoneNumber,
                photoURL: photoURL,
                uid: uid,
                accessToken: accessToken,
                providerData: providerData
              }, null, '  ');
            });
          } else {
            // User is signed out.
            document.getElementById('sign-in-status').textContent = 'Signed out';
            document.getElementById('sign-in').textContent = 'Sign in';
            document.getElementById('account-details').textContent = 'null';
          }
        }, function(error) {
          console.log(error);
        });
      };

Forget the demo here https://github.com/firebase/firebaseui-web#developer-setup is working since one month and is operational on my web site here https://artadys.com click on the right corner on Sign Up and see the demo is working

What is not working are the errors I get when I insert the developer environment on the landing page and on the route page I get these errors

and all errors are Firebase errors

**Comment by EmberJSParis** [comment]
I put the code here https://github.com/EmberJSParis/Firebasetest

Is just the landing page index.hbs and the route page kontact.hbs that are not working and is not EmberJS the problem

The problem is Firebase

**Comment by rmmmp** [comment]
Sorry, I still don't get why you want to use the developer setup. If I'm correct, you only do that if you wish to do some dev work on that library and contribute it back. It's also unrelated to EmberFire.

Seeing your code, it's gonna be hard to debug since that's definitely not how you should use Firebase UI Web. You shouldn't be putting `<script></script>` tags in your `.hbs` files.

Just insert the `{{firebase-ui-auth uiConfig=uiConfig}}` in your sign-in/sign-up template. Make sure the `uiConfig` is defined in your controller where the `firebase-ui-auth` component can access it. After the user signs-in, you can redirect them to your home page again so the `session` can set-up which is being done in our `application` route.

One last thing, add a return in your session fetching in your `application` route like this:

```javascript
beforeModel() {
    return this.get('session').fetch().catch(function() {});
},
```

This is also unrelated to EmberFire so I think it'd be best to ask this in Stackoverflow or the [Firebase Google Groups](https://groups.google.com/forum/#!forum/firebase-talk).

**Comment by EmberJSParis** [comment]
OK Thanks for the answer. 

> You shouldn't be putting <script></script> tags in your .hbs files.
> 


is just to test, it could be there is not an error.

> Just insert the {{firebase-ui-auth uiConfig=uiConfig}} in your sign-in/sign-up template. Make sure the uiConfig is defined in your controller where the firebase-ui-auth component can access it. After the user signs-in, you can redirect them to your home page again so the session can set-up which is being done in our application route.
> 
> One last thing, add a return in your session fetching in your application route like this:
> 
> beforeModel() {
>     return this.get('session').fetch().catch(function() {});
> },

I don’t kniow how to do what you say ?

If youa re EmberJS why not build an example in EmberJS from scratch with one landing page and a routing page ?

I don’t understand when you say 

> Just insert the {{firebase-ui-auth uiConfig=uiConfig}} in your sign-in/sign-up template. Make sure the uiConfig is defined in your controller where the firebase-ui-auth component can access it. After the user signs-in, you can redirect them to your home page again so the session can set-up which is being done in our application route.
> 
> One last thing, add a return in your session fetching in your application route like this:
> 
> beforeModel() {
>     return this.get('session').fetch().catch(function() {});
> },

WHY YOU TALK WITH ME ? WHO ARE YOU ?

WHERE IS YOUR CODE ?

I UNDERSTAND NOTHIN

……………………………………..
why should I use your add-on ?

Why EmberJS is all on me ? Who call you ? How can I use your advices ? 

CAN YOU BUILD A DEMO AND PUT ON GITHUB ?

THANKS

WHAT ARE YOU DOING HERE, IF NOT Who call you ?

……………………………………………………………………...

Who asked you to come in place of Firebase ?

Why not just let the Firebase team to show me how they write code on the landing page then on the route page ? AND FORGET EMBERJS THEY HAVE NO CODE TO SHOW ON GITHUB ON THAT.

Where is the config (in Firebase ?)

Why the EmberJS team come to me ?

Why not REACT ? Why not Angular ?

I WANT FIREBASE TO SHOW ME THE CODE ON THE LANDING PAGE and THE ROUTING PAGE plus where are the config.js files and the files that I get errors as hereafter ?

Please if you dont do code, please stop to write litterature please I need code

**Comment by rmmmp** [comment]
[Here's](https://gist.github.com/steven-ferguson/8eddf63123fa74066e9d92f7e829d8e9) a sample code. 

👌

**Comment by EmberJSParis** [comment]
Thanks I will test tomorrow. Thanks

**Comment by EmberJSParis** [comment]
OK I am on it

So how you run this code ? Is not EmberJS so is not ember server

is not firebase server …what it is ?

Thanks

Here is what you propose - see on the right is firebase-ui-auth.js etc…..


This has nothing to do with the https://github.com/firebase/firebaseui-web#installation or with EmberJS it seems someone say is related with your participation here  https://github.com/rmmmp/emberfire-utils#firebaseui <https://github.com/rmmmp/emberfire-utils#firebaseui>, it also works pretty well.

I really need operational code not literature please

Thanks

**Comment by EmberJSParis** [comment]
Hi Firebase,

May I enter in contact with Firebase developers who wrote the code here https://github.com/firebase/firebaseui-web#installation ?

Please Thanks

It doesn’t matter if they tested this code in AngularJS, REACT, View or other framework, all what I need is to get an operational code for 2 pages running together a landing page and an authenticated route page (could be in any framework it doesn’t matter, Firebase choice)

I just need to understand how they managed the files in installation and I wish to reproduce that in my framework (I can learn others if necessary)

Thanks

**Comment by EmberJSParis** [comment]
Firebase,

Please don’t bring me again people like this one from stackoverflow. Have been there already and no solution.

Let’s focus on your code https://github.com/firebase/firebaseui-web#installation from here.

Can you reproduce again ?

Thanks


PS: this guy from EmberJS can not help his code is no longer operational he come here to give only ideas

A literature guy

**Comment by jamesdaniels** [comment]
For Emberfire see our getting started guide https://github.com/firebase/emberfire/blob/master/docs/guide/README.md if you're interested in this library.

Otherwise this is not an emberfire issue so I am closing. Please feel free to continue discussing here.
