### ISSUE TITLE
Correct way to access firebase object when using emberfire

### ISSUE THREAD

**Issue by es6Test** [firebase/emberfire#518]
I am trying to access firebase by doing the following in an app equipped with emberfire:

```js
  firebase:Ember.inject.service(),

  actions:{
    submitPost(newPost) {

      newPost.dateCreated = new Date().toISOString()
      newPost.dateUpdated = this.get('firebase').database.ServerValue.TIMESTAMP
```

however this.get('firebase') is undefined, so I am wondering if I need to install firebase seperately or I can use emberfire somehow.

**Comment by oskarrough** [comment]
Try this

```js
import firebase from 'firebase'
const timestamp = firebase.database.ServerValue.TIMESTAMP
```

**Comment by es6Test** [comment]
Ok so we need to have firebase as a separate dependency to emberfire?

**Comment by es6Test** [comment]
@oskarrough I don't want to do it that way as I will have to supply the api keys again if I want to do something like:

```js
import Ember from 'ember';

import firebase from 'firebase'

export default Ember.Controller.extend({



  actions:{
    submitPost(newPost) {

      newPost.dateCreated = new Date().toISOString()
      newPost.dateUpdated = firebase.database.ServerValue.TIMESTAMP

      newPost.save().then(()=>{
        this.set('model.newPost',this.store.createRecord('post'))

        this.transitionToRoute('app.index')

      })
    }
  }

});
```

There must be a simple way to access firebase from emberfire but I can't find it in the docs :(

**Comment by oskarrough** [comment]
Firebase is already a dependency of Emberfire so that should be good. But try this instead to get the 'app' instance created with your config etc.

```js
firebaseApp: inject.service(),

createFirebaseUser(email, password) {
  const auth = get(this, 'firebaseApp').auth()
  return auth.createUserWithEmailAndPassword(email, password)
}
```
