### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by rwwagner90** [firebase/emberfire#521]
It has been quite awhile since there was a release, and we've been relying on the master branch. Could we get another release cut sometime soon? Also, it seems the issues and PRs have become somewhat stagnant. I could potentially help out with some stuff if needed. I love this addon and would like to see it flourish.

**Comment by edborden** [comment]
Ember used to have a dedicated engineer at Firebase, anyone know if that is still the case? I feel like Google could probably afford it!

**Comment by rwwagner90** [comment]
@edborden I assume it's very low priority, since they want people to use Angular and not Ember 😞

**Comment by rmmmp** [comment]
😢

**Comment by mileszim** [comment]
@rwwagner90 check out #522 , I'm not sure what the deal is with the emberfire devs but we are currently on our own in getting this back up to speed as far as I can tell. I don't want to go back to the ember 1 days where we had a fork that was much better and more commonly used (https://github.com/rlivsey/fireplace) but that may be the route for now. In any case, check out the discussion in the issue linked above, I'd love to hear your thoughts.

**Comment by edborden** [comment]
Response from Firebase/google about this repo:

```
Hello Edward,

Thanks for bringing this to our attention. This is Allen, and I'd be happy to take note of your feedback.

I understand your concern, and apologies for the inconvenience this may have caused you.
I've raised your feedback to our engineers so they could have a look at the EmberFire library. However, I could not guarantee you that those Pull Requests will be merged anytime soon.
Continuous improvement is very important for our community, so we're keeping any feedback moving forward. And again, thanks for bringing this up.

Don't hesitate to reach out to us again if you have any other issues or questions.
Thank you for using Firebase and happy coding, Edward! :)

Cheers,
∞Allen
```

**Comment by mileszim** [comment]
@edborden thank you so much for contacting them directly, that is awesome. Unfortunately it reads more like a non-answer. Let's hope these awesome firebase engineers will get back about it, because they have done an awesome job so far and I'd love to see them keep that ball rolling.

**Comment by jamesdaniels** [comment]
The main delay here is that I've not gotten the necessary access to the release tooling. Maybe @tstirrat can cut a release?

**Comment by jamesdaniels** [comment]
I got access to the release tooling. I'll cut a new version soon.
