### ISSUE TITLE
Fastboot compatibility fails in Ember 2.14.1 and fastboot 1.0

### ISSUE THREAD

**Issue by alexmasita** [firebase/emberfire#523]
### Version info

```
e.g.
DEBUG: -------------------------------
Ember Inspector | 2.0.6
Ember | 2.14.1
Ember Data | 2.14.10
Firebase | 3.9.0
EmberFire | 0.0.0
jQuery | 3.2.1
Fireboot | 0.0.0+7fc2e482
DEBUG: -------------------------------
```

### Test case

https://github.com/alexmasita/fireboot.git

You will need to create your own firebase database and put in your firebase configuration in the environment js.  Then create a new post record in the firebase database with attributes as seen on the ember app 'post' model.

### Steps to reproduce

When you run the above repository locally with ember serve, it will run the fastboot server.  Because it already has the ember fire addon, the fetch from the firebase database will fail.  However, if you run fastboot with the query params: http://localhost:4200/?fastboot=false.  The fetch will succeed.

### Expected behavior

The api call to the firebase server should succeed with both the fastboot server call enabled and disabled.

### Actual behavior

Only the api call to firebase with the fastboot server disabled succeeds.

**Comment by rmmmp** [comment]
Try using the master branch. It should be fixed there.

**Comment by alexmasita** [comment]
Fantastic.  Problem solved.
