### ISSUE TITLE
Cloud Firestore Support?

### ISSUE THREAD

**Issue by davidchalifoux** [firebase/emberfire#529]
Hey all, I was just wondering what the team's plan is for supporting [Firestore](https://firebase.googleblog.com/2017/10/introducing-cloud-firestore.html) within EmberFire? 

I've seen other people asking about it in some Slack channels but have yet to hear an official response.

Cheers!

**Comment by marendra** [comment]
Me too, hopefully no just angular get the SDK fast

**Comment by jamesdaniels** [comment]
I will be releasing a community roadmap shortly and a WIP branch will follow. Cloud Firestore has a model which is much much more inline with ember-data than the Firebase Realtime Database, so that will become the preferred adapter.

I am also hoping to roughly align with the Ember 3.0 timetables.

**Comment by rmmmp** [comment]
Cool. Can't wait to see the roadmap. Although I feel aligning with Ember 3.0 is too long as it's 5 months from now. Let us know how we can help to speed things up. :grin:

**Comment by Luiz-N** [comment]
> Cloud Firestore has a model which is much much more inline with ember-data than the Firebase Realtime Database

Yesss! Those were my exact thoughts when reading up on firestore... I feel these two together will make for a very powerful toolset... excited to see this happen. I imagine given the similarity of their apis this shouldn't be too hard of a refactor

**Comment by Ghostavio** [comment]
Any news on this?

**Comment by jernejc** [comment]
This would be awesome, seems like the Firebase team is pushing a lot towards Firestore.

**Comment by jeanleonino** [comment]
Any any news on this, feeling that Ember.js is left behind.

**Comment by jamesdaniels** [comment]
I have demonstrated a WIP Firestore adapter to stakeholders here at Google. Putting together the community proposal and pushing the WIP branch is on my plate for next week!

**Comment by appadvice** [comment]
Great to hear, looking forward to it!

**Comment by onewiseburdman** [comment]
Can we get an update on this please?  I am at a point for my app that I could end up with expensive hardware for user auth and user roles, when I could just use Firebase for Auth and Firestore for the table structures.  I would like to see some examples on how it would be done properly.

**Comment by jacojoubert** [comment]
Looking forward to this. Any plans to allow data to be auto-migrated from the real-time database to the cloud firestore?

**Comment by willviles** [comment]
Very interested in using the Firestore adapter ASAP! I'm happy to test & contribute @jamesdaniels if there's a branch ready to be pushed.

**Comment by jeanleonino** [comment]
@willviles same here. A bit disappointed with all that.

**Comment by jernejc** [comment]
Any ideas on when we can expect this ?

**Comment by jamesdaniels** [comment]
Sorry there's been some comms here on #522, Firestore support is roughly targeting Ember v3 timelines.

**Comment by juviwhale** [comment]
Are there other plugins or options available? Its been a few months now and my team needs to finalize architecture decisions. It feels like if Ember is our frontend choice then Firebase may not be a well supported datastore to choose.  It is not only the lack of Firestore support that is frustrating but also the promise of [server side rendering for Ember in the \<near future\>](https://youtu.be/nbTn1czE2L8?t=51s) from last August that never appeared. Don't get me wrong, I bet you are doing what you can, but the appeal of Firebase for us was to move quickly and it feels like Firebase is now what is slowing us down.

**Comment by rmmmp** [comment]
@juviwhale regarding the server side stuff. You don't need to wait for their video. Just look into ember fastboot and you'll be good to go. Firestore's just what you have to wait for if you want to build around that.

**Comment by juviwhale** [comment]
Thanks @rmmmp. I will take a look. I was under the impression there was a yet to be documented firebase cloudfunction config.

**Comment by rmmmp** [comment]
@juviwhale also, I also have a an [ember-cloud-firestore-adapter](https://github.com/rmmmp/ember-cloud-firestore-adapter) that you can use temporarily at least until we get an official release here. Just note that my design decisions (e.g. how relationships are persisted in the db, unit testings, etc.) might not be the same as what's getting released here. However in your case it might be good enough just to keep you going then refactor on a month from now which should be the official release of cloud firestore in emberfire (if the ember 3.x release is followed).

**Comment by eibrahim** [comment]
I would love this too too.

**Comment by Ghostavio** [comment]
this is pretty much dead, easier just migrating to react :/

**Comment by mikkopaderes** [comment]
I don't like seeing people moving to other frameworks because a major development platform doesn't have first class support for it.

For those that may consider, feel free to checkout https://github.com/mikkopaderes/ember-cloud-firestore-adapter if it fits your needs.

**Comment by gvelesandro** [comment]
Hi @jamesdaniels, by closing this issue, are you indicating that emberfire will not support Firestore?

**Comment by zoltan-nz** [comment]
@gvelesandro As I see `Firestore` will be the default adapter, so it will be supported.

https://github.com/firebase/emberfire/blob/master/docs/guide/installation.md#1-install-emberfire-as-an-ember-cli-addon

Don't hesitate to try out the master branch in your project so we can give feedback quickly for James.
