### ISSUE TITLE
Create a separate addon for exposing Firebase service?

### ISSUE THREAD

**Issue by mikkopaderes** [firebase/emberfire#531]
What are everyone's thoughts on an addon that simply exposes a Firebase service?

I think a problem on a community developed addon for Firebase is being reliant on emberfire for the `firebase` and `firebaseApp` service which is lagging behind in terms of version. Here's an example of my use-case, I have an [ember-firebaseui](https://github.com/rmmmp/ember-firebaseui) addon that could move up to the 2.x version of [firebaseui-web](https://github.com/firebase/firebaseui-web) which supports phone auth if it's using an up-to-date Firebase version.

With this, community based addons can now target the latest Firebase without creating their own Firebase service that will do `firebase.initializeApp()`. Not to mention having more than 1 `firebase.initializeApp()` can introduce clashes. EmberFire then, could simply target a lower version of that Firebase service addon if it can't support yet the latest one. I can also imagine that getting updates on that addon will be quicker since it would pretty much just be a matter of updating the dependency in it's package.json. EmberFire team would be able to update it easily.

Is this something that the EmberFire team would entertain?

**Comment by heat** [comment]
Why not kee  updated this addon with the last one version of ember api and firebase ?
I started a fresh 2.16 ember application and I think emberfire isn't use new module API.  I'm very sad with that.
