### ISSUE TITLE
npm or yarn ?

### ISSUE THREAD

**Issue by fuse-mars** [firebase/emberfire#532]
The local setup documentation uses npm but travis uses yarn. would it be possible to use one tool in both cases?

### Expected behavior
Use either yarn or npm on both, but not both at the same time.

### Actual behavior
* Use npm locally
* Use yarn on travis

**Comment by jamesdaniels** [comment]
Yarn had an unresolved bug that caused me to back peddle for the sake of Travis, I will look at this again.
