### ISSUE TITLE
deprecation notice when using Ember 2.17.2

### ISSUE THREAD

**Issue by jabbermarky** [firebase/emberfire#536]
There is a deprecation notice in the console when using EmberFire 2.0.8 with Ember 2.17.2.

```
Ember Inspector (Deprecation Trace): Ember.String.pluralize() is deprecated. Please explicitly: import { pluralize } from 'ember-inflector';
```
### Version info
DEBUG: -------------------------------
DEBUG: Ember           : 2.17.0
DEBUG: Ember Data      : 2.17.0
DEBUG: Firebase        : 3.9.0
DEBUG: EmberFire       : 0.0.0 (2.0.8)
DEBUG: jQuery          : 3.2.1
DEBUG: Ember Bootstrap : 1.0.0

**Comment by oskarrough** [comment]
This is already (almost) fixed here https://github.com/firebase/emberfire/pull/533

**Comment by jamesdaniels** [comment]
`2.0.9` has been released addressing.
