### ISSUE TITLE
Using Firebase Auth with custom API - am I doing this right?

### ISSUE THREAD

**Issue by davidchalifoux** [firebase/emberfire#537]
Hey, I'm currently planning on using Firebase for everything except for data storing. Therefore I'm writing a custom API as a Cloud Function and am working on implementing Firebase's Auth into my API. From my research, the JWT from Firebase Auth is currently available under `session.currentUser.Yd` thanks to the Torii adapter.

At the moment this seems to be working as expected since `Firebase-Admin` is successfully decoding it, but I'd like to double check if I'm wrong somehow. `Yd` just seems to be an odd name for the JWT token, especially since the refresh token is under `refreshToken`.

Thanks!

**Comment by pawangiri** [comment]
I am ding the same thing 
`session.currentUser.Yd`
It does not feel right but works. I was unable to find anything else.

**Comment by MatthewSBarnes** [comment]
I spent far too long researching, and realized that ember fire uses the `3.9.0` firebase SDK, (inject the firebaseApp service, and check it's `SDK_VERSION` property).

That means the `firebaseApp` service only has access to the deprecated `getToken()` method.

You'll find that `session.currentUser.Yd` returns the exact same thing as `getToken()`.

Thanks for this, better late than never!
