### ISSUE TITLE
Deprecation warning with Ember 2.18.0 (Ember Inflector deprecation (pluralizing)) 

### ISSUE THREAD

**Issue by ArmeniaH** [firebase/emberfire#544]
Hello

With Ember 2.18.0 there is an update of Ember Inflector component which cases a deprecation error with EmberFire 2.0.9

```DEPRECATION: Ember.String.pluralize() is deprecated. Please explicitly: import { pluralize } from 'ember-inflector'; [deprecation id: ember-inflector.globals]```

which is used in ```adapters/firebase.js```

```/**
   * Determines a path fo a given type
   */
  pathForType(modelName) {
    var camelized = Ember.String.camelize(modelName);
    return Ember.String.pluralize(camelized);
  },
```

**Comment by jamesdaniels** [comment]
Would you be willing to send a PR?

**Comment by ArmeniaH** [comment]
Yes, give me some time please
