### ISSUE TITLE
support for the 4.x release of firebase

### ISSUE THREAD

**Issue by b0182** [firebase/emberfire#546]
Currently emberfire seems to support 3.4.1. Ar there any news or guides to update emberfire to use 4.x release?

**Comment by jamesdaniels** [comment]
I will have an RC of the next major version of Emberfire available for
testing next week.

**Comment by b0182** [comment]
Thanks James, that is exciting news! will look out for the next release

**Comment by bnetter** [comment]
Really expecting this as well!

**Comment by anibalrivero** [comment]
Hi! Would this new Emberfire version allow us to use Fastboot with Firestore, hosted on Firebase?

Thanks!

**Comment by jamesdaniels** [comment]
That's the plan yes. Working on a release candidate right now.

**Comment by Ghostavio** [comment]
Any news on when the RC will be available?

**Comment by bnetter** [comment]
🙏 same question.

**Comment by bnetter** [comment]
@jamesdaniels it's been almost 2 months now. Should we look for (or build) alternatives to this?

**Comment by Ceany** [comment]
Still nothing?

**Comment by conormag** [comment]
it appears @jamesdaniels is [working on it](https://twitter.com/jamesuriah/status/1007753209346060289) although he's not updating here regularly. I think angularfire is taking up most of his time, unfortunately for us :(

**Comment by jamesdaniels** [comment]
Hey sorry for the lack of update here, [v3](https://github.com/firebase/emberfire/commits/v3) is in early alpha testing now. I was going to cut a beta build on NPM last week but bit off more than I could chew attempting to get Fastboot support wrapped and experimenting with ember-auto-import.

The main problem we ran into (aside from my getting pulled away by angularfire becoming so popular) was the release of Firebase JS SDK v5, which had some troubles with it's module exports; which are started getting resolved.

**Comment by rmmmp** [comment]
@jamesdaniels I see your Twitter posts. If you require `firebase/firestore` in FastBoot env rather than than the 'firebase-firestore.js` that should make it work in FastBoot and not run into the `XMLHttpRequest`.

I beliece it's because the `firebase/firestore` is the node friendly version while `firebase-firestore.js` is the browser friendly one.

**Comment by jamesdaniels** [comment]
@rmmmp I got it, [passed into the environment sandbox](https://github.com/firebase/emberfire/blob/v3/express.js#L10). 

`ember-auto-import` is also building the browser version regardless which was compounding my problems. I gave up on that for now, especially [since I have to do all this junk](https://github.com/firebase/emberfire/blob/ember-auto-import-fastboot/addon/services/firebase-app.ts#L36) (and auth doesn't export the method) due to another bug with `ember-auto-import`.

**Comment by rmmmp** [comment]
Hmm. So if we want to use fastboot, we also have to sandboxGlobal it?

**Comment by jamesdaniels** [comment]
Yes, this is a problem I've also encountered in Angular Universal. I've raised with the SDK team and they're considering building in polyfills in 6.0.

**Comment by conormag** [comment]
the v3 branch has been sitting for a month now waiting for review. Does anyone know what the story is with that?

**Comment by jamesdaniels** [comment]
Vacation and Cloud Next ;) I'll be back in the game next week.

**Comment by conormag** [comment]
this is frustrating

**Comment by jpguzman** [comment]
Any ETA on this update?

**Comment by Ghostavio** [comment]
It's sad to see this halted for over half a year :/

**Comment by conormag** [comment]
I asked @jamesdaniels [about this on twitter](https://twitter.com/jamesuriah/status/1050024916270161920). He doesn't seem to reply much here. He says the v3 branch contains the new emberfire for firebase 5 and is looking for more feedback before releasing.

**Comment by lookininward** [comment]
Do you guys have any suggestions for emberfire alternatives or other ways you integrate firebase into your projects? Feel like I'm gonna get old waiting for updates here.

**Comment by zurnet** [comment]
I wish I had a better answer other than reluctantly I've started to look at Angular.  There's a reason we all use Ember and gravitated toward that library over Angular.

**Comment by conormag** [comment]
if you want to use firestore rather than rtdb you could take a look at [ember-cli-zuglet](https://github.com/ampatspell/ember-cli-zuglet)
