### ISSUE TITLE
App does not find 'emberfire/addon/adapters/firebase'

### ISSUE THREAD

**Issue by jdvallejor** [firebase/emberfire#548]
Hello I am using emberfire and I get the next error when trying to create a object from a model.

![image](https://user-images.githubusercontent.com/20892553/39076958-220a0428-44c4-11e8-9235-4794658abe93.png)

I have checked and the file already exists!

![image](https://user-images.githubusercontent.com/20892553/39076994-55c9f94e-44c4-11e8-9e9a-6ca2b6d2084e.png)

This is the code. The step of creating the user and authentication using torii works perfect, but when when I try to save data to the database I got the error described before.

![image](https://user-images.githubusercontent.com/20892553/39077119-35c0ead0-44c5-11e8-9d29-391adbf97db2.png)

Thanks for any help!!

### Version info

DEBUG: Ember      : 3.1.0
DEBUG: Ember Data : 3.0.0
DEBUG: Firebase   : 3.9
DEBUG: EmberFire  : 2.0.9

**Comment by oskarrough** [comment]
Hey, can you share your `adapters/application.js` where you import it? Note, you should not include "addon" in the path. This is how my application adapter looks:

```js
import FirebaseAdapter from 'emberfire/adapters/firebase'
export default FirebaseAdapter.extend({})
```

**Comment by jdvallejor** [comment]
Thanks, now it works!, but i have a question. The adapters/application.js was generated automatically when I installed emberfire, so is there a problem in the installation?

**Comment by oskarrough** [comment]
Great!

I couldn't find anywhere in the blueprints where `addon/` should be defined... So I'm not sure why it happened.

https://github.com/firebase/emberfire/blob/master/blueprints/firebase-adapter/files/app/adapters/__name__.js
