### ISSUE TITLE
Unable to signup user with email password on ember fire

### ISSUE THREAD

**Issue by yashLadha** [firebase/emberfire#550]
### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 3.1.2
DEBUG: Ember Data : 3.1.1
DEBUG: Firebase   : 3.9.0
DEBUG: EmberFire  : 2.0.10
DEBUG: jQuery     : 3.3.1
DEBUG: -------------------------------
```

### Test case

```js
signIn() {
      const ctrl = this.get('controller');
      const auth = this.get('session').auth();
      auth.createUserWithEmailAndPassword(ctrl.email, ctrl.password)
        .then(function(userResponse) {
          console.log(userResponse);
        })
        .cath(function(err) {
          console.error(err.message);
        });
    },
```

### Steps to reproduce

Try to create user with email and password.

### Expected behavior

The user should get created.

### Actual behavior

It shows TypeError: `auth() is not a function`. 

PS: I have injected the service.

**Comment by oskarrough** [comment]
Hi, are you using Emberfire 2.x?

If so, the `auth()` object is not stored on the `session` but on the `firebaseApp` service. See https://github.com/firebase/emberfire/blob/353ad6b9e53a90bc92b073391b086ff42a0569d6/docs/migration/1XX-to-2XX.md#update-auth-methods.

**Comment by yashLadha** [comment]
@oskarrough I am using 2.0.10 ember fire

**Comment by aalimovs** [comment]
What is `this.get('session')`?

Try this

```js
firebaseApp: service(),

...

signIn(email, password) {
    const auth = this.get('firebaseApp').auth();
    auth.createUserWithEmailAndPassword(email, password)
        .then(() => { ... });
}
```
