### ISSUE TITLE
Filter array object

### ISSUE THREAD

**Issue by mapeveri** [firebase/emberfire#551]
Hi everyone, i have this issue with this code:

This filter in my route:

`this.get('store').query('post', { filter: { categories: { filter: { id: params.id } } } })`

My models:

```
// Post
export default DS.Model.extend({
  title: DS.attr('string'),
  body: DS.attr('string'),
  slug: DS.attr('string'),
  user: DS.attr(),
  image: DS.attr(),
  create: DS.attr('date'),
  categories: DS.attr(),
  comments: DS.hasMany('comment')
});

// Category
export default DS.Model.extend({
  name: DS.attr('string'),
  slug: DS.attr('string')
});
```

My data, for example:

![image](https://user-images.githubusercontent.com/6276555/40280384-b0b7520e-5c28-11e8-9850-ad3dcc1015ad.png)

Returns all the records. Nothing filtered.

That filter, should not it be filtering correctly?. It's a issue?.

Thanks!

**Comment by oskarrough** [comment]
Normally that's how you'd filter but Emberfire follows the firebase syntax. Check https://github.com/firebase/emberfire/blob/master/docs/guide/querying-data.md#querying-data

**Comment by mapeveri** [comment]
I understand, but the filter that they show is very simple and I do not finish to understand how I would have to filter then to be able to obtain the category that I need in my filter.

**Comment by paperlambda** [comment]
same here. the docs refers to the firebase querying method but i cannot findthe right way to implement it on emberfire

**Comment by paperlambda** [comment]
i think this issue should be closed @oskarrough

**Comment by paperlambda** [comment]
watching this issue (https://github.com/firebase/emberfire/issues/529) right now
