### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated.

### ISSUE THREAD

**Issue by oepscina** [firebase/emberfire#555]
Hi

Im getting this warning when start my ember s

DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.1.6 located: /home/develop/desarrollos/wtr-avl/node_modules/emberfire/node_modules/ember-cli-babel

My ember...
ember-cli: 3.3.0
node: 10.6.0
os: linux x64

emberfire 2.0.10

Hope any can help 

Regards

**Comment by zurnet** [comment]
Checking to see if there's any movement on this one....

**Comment by oepscina** [comment]
HI,

steel not found how to fix this issue, can you help?

regards

**Comment by oskarrough** [comment]
Related https://github.com/firebase/emberfire/issues/541

**Comment by oepscina** [comment]
See the related in i don’t found what to do…..

any suggestions , already try rm -rf node_modules
and npm install and have the same depreciation message.

**Comment by oskarrough** [comment]
@oepscina you can't fix it in your application I'm afraid.

This has to be fixed by upgrading some dependencies in the emberfire addon itself. In particular, we have to make sure that no dependencies of emberfire uses `ember-cli-babel` below version 6.

**Comment by dirkdirk** [comment]
It's been over a year and I'm still getting this warning (now on Ember 3.8.3).

Will it be resolved at some point?  Or just ignore it?

**Comment by Akash1399** [comment]
I'm still struggling with this error
