### ISSUE TITLE
Emberfire not working with Ember 3.4

### ISSUE THREAD

**Issue by Ceany** [firebase/emberfire#556]
### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 3.4.x
DEBUG: Ember Data : 3.4.x
DEBUG: Firebase   : 3.4.1
DEBUG: EmberFire  : 2.0.10
DEBUG: -------------------------------
```

### Test case

Start an Ember app with version 3.4

### Steps to reproduce

Install current version of emberfire (2.0.10). And install Ember 3.4. Run it with ember serve. Site does not load. 

### Expected behavior

Side should load.

### Actual behavior

Error in console

````
Uncaught Error: Could not find module `ember` imported from `emberfire/initializers/emberfire`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at resolveInitializer (index.js:34)
    at registerInitializers (index.js:47)
    at exports.default (index.js:28)
```

**Comment by fsmanuel** [comment]
@Ceany `ember install ember-cli-shims` should do the trick.

**Comment by Ceany** [comment]
@fsmanuel That works perfectly. Thank you

**Comment by Ceany** [comment]
you just have to execute the command in your ember app. than the ember addon will be installed. 
That should do the trick to get the app back running

**Comment by msdedwards** [comment]
@mikespittal this [link](https://github.com/ember-cli/ember-cli-shims#why) helped me figure out why ember-cli-shims was in my app. Hope it helps.

**Comment by mikespittal** [comment]
> @mikespittal this [link](https://github.com/ember-cli/ember-cli-shims#why) helped me figure out why ember-cli-shims was in my app. Hope it helps.

Thank you!
