### ISSUE TITLE
Relationship with Outside API Model

### ISSUE THREAD

**Issue by ChristopherJohnson25** [firebase/emberfire#558]
I'm curious if this is possible. I'm using EmberFire for my user profile and authentication data, but using Ember Wordpress for all of my content. I have a model from Wordpress called ```trips``` and I'd like to give my EmberFire user a hasMany relationship to trips. Is this possible? I keep getting serializer errors and have not seen anything directly related to this in the docs.

**Comment by heat** [comment]
I have a project with REST + Firebase and every think works fine to me. What you need to do is create adapter for other kinds of reources.
` ember g adapter modelname`
