### ISSUE TITLE
Uncaught TypeError: Cannot read property 'modelName' of undefined

### ISSUE THREAD

**Issue by lokesh411** [firebase/emberfire#567]
### Version info

```
e.g.
DEBUG: -------------------------------
DEBUG: Ember      : 3.7
DEBUG: Ember Data : 3.7.0
DEBUG: Firebase   : 5.9.0
DEBUG: EmberFire  : 2.0.10
DEBUG: jQuery     : x.x.x
DEBUG: -------------------------------
```

### Test case

Not able to push records which has relashionships like belongsTo and hasMany.

### Expected behavior

Records should be pushed to the firebase

### Actual behavior

TypeError:  Cannot read property 'modelName' of undefined
<img width="1439" alt="Screen Shot 2019-03-20 at 3 30 53 PM" src="https://user-images.githubusercontent.com/26621756/54676432-b213e700-4b26-11e9-88bd-285dfea87ddd.png">

**Comment by zoltan-nz** [comment]
Please use Ember v3 4

If you really wanna use Ember v3.7, you have to use the beta release of the latest emberfire.

**Comment by ChristopherJohnson25** [comment]
I'm getting the same issue, any updates here? I'm on Ember 3.6, should I really downgrade to 3.4?

**Comment by lokeshwaran-kirubanandan** [comment]
edit Firebase.js in ember folder or just change the version in package.json and run npm install
