### ISSUE TITLE
TypeError: internalModel._relationships is undefined

### ISSUE THREAD

**Issue by baks1** [firebase/emberfire#569]
Hey,

I have a problem with sending data to firebase. I think I'm doing everything right but when I want to send data to firebase, I see this "TypeError: internalModel._relationships is undefined" error. Of course I tried to solve the problem myself.

ember -v

> ember-cli: 3.8.2
> node: 10.15.3
> os: win32 x64

models/invitation.js

> import DS from 'ember-data';
> 
> export default DS.Model.extend({
>   email: DS.attr('string')
> });

config/environment.js

> let ENV = {
>     modulePrefix: 'lib....',
>     environment,
>     rootURL: '/',
>     locationType: 'auto',
>     firebase: {
>     apiKey: "AIza....",
>     authDomain: "ap...",
>     databaseURL: "https://ap...",
>     projectId: "ap....",
>     storageBucket: "ap....",
>     messagingSenderId: "70....1"
>     },

**Comment by bhernez** [comment]
🤔 Is that the only model in the project?  That error commonly refers that Ember couldn't find the inverse relation for a `belongsTo` or `hasMany`

**Comment by Srinivasan-Natarajan** [comment]
what is the solution for this problem? but closed?

**Comment by jamesdaniels** [comment]
I have no repro and someone suggested what the error might be related to, so closed.  If I have a demonstrated repro, it’s actionable.
