### ISSUE TITLE
firebase-app service app file missing

### ISSUE THREAD

**Issue by knownasilya** [firebase/emberfire#573]
I don't see firebase-app service reexported in app/services.

I tried this locally and during ts precompile got: `app/services/firebase-app.ts(1,25): error TS2307: Cannot find module 'emberfire/services/firebase-app'.`

**Comment by knownasilya** [comment]
Looks like ` "emberfire/services/firebase-app": [ "addon/services/firebase-app"],` needed to be added to tsconfig.json under `paths`.

**Comment by jamesdaniels** [comment]
Shipped in `rc.2`
