### ISSUE TITLE
a question on async: true (not really an issue)

### ISSUE THREAD

**Issue by yial2** [firebase/emberfire#58]
<code>
App.Post = DS.Model.extend({
  comments: DS.hasMany('comment', { async: true })
});
</code>
if I left the {async: true} out

<code>
App.Post = DS.Model.extend({
  comments: DS.hasMany('comment')
});
</code>
how will the adapter behave? It looks like it will load all comments while fetching the post "at the same time", correct?

**Comment by tstirrat** [comment]
As you found out, `async: false` requires the server to `sideload` the related records into the main payload. This is not something that firebase is capable of doing, thus, we only support `async: true` or `embedded: true`
