### ISSUE TITLE
This seems to throw an error

### ISSUE THREAD

**Issue by denzo** [firebase/emberfire#592]
https://github.com/firebase/emberfire/blob/db079a6575c5053893b961a3a97b92addbd043b8/addon/torii-adapters/firebase.ts#L12

```"Could not find module `path` imported from `emberfire/torii-adapters/firebase`"```

**Comment by jamesdaniels** [comment]
Whoops! Good catch. Looks like VS Code autocomplete attacked, should be resolve from rsvp.

**Comment by jamesdaniels** [comment]
Addressed in ~~rc.5~~ rc.6
