### ISSUE TITLE
Records not saving/updating with allSettled

### ISSUE THREAD

**Issue by gertig** [firebase/emberfire#68]
I'm using ember-rails (what I know) and emberFire together and am recreating the todoMVC app http://emberjs.com/guides/getting-started/planning-the-application/

When I attempt to save a record it fails in emberFire on this line:
https://github.com/firebase/emberFire/blob/master/src/data.js#L406

When I change .allSettled to .all things work great. My sense is that this is related to the Todo model not having any relationships. Which could be related to this:
https://github.com/emberjs/ember.js/blob/v1.5.0/packages/rsvp/lib/main.js#L94

**Comment by sararob** [comment]
@gertig I'm going to close this, feel free to reopen if you still need help and can provide additional details
