### ISSUE TITLE
new local only embedded record rollback to new state

### ISSUE THREAD

**Issue by williamli** [firebase/emberfire#95]
not sure if this is intentional.
say i have an embedded relationship

// contact
mobile: DS.belongsTo(‘phonenumber’, {embedded: true});

when phonenumber model is created, I just need to set it into contact’s mobile field like
number = this.store.createRecord('phonenumber’);
…
newContact.set(‘mobile, number);
newContact.save();

if I also call number.save(), the number object will also get pushed to firebase under ‘phonenumber’ which is unnecessary

now, if I was number becomes dirty after some edit, and the edit was cancel, i can call a rollback on it

number.rollback()

but since number was never saved to the server, calling rollback() will put number back to a blank state…

is there anyway around this problem now?

if i force the program to retrieve a new copy of number from server right after newContact is saved, then the problem goes away… since that copy is from server… but this feel like a hack… is there a better way to handle this?

**Comment by tstirrat** [comment]
Thanks for the workaround with `FixtureAdapter`. I think thats probably the best solution at the moment.

Embedded records need some love, I've linked this to #135 so we can capture this in the next embedded records update.

I'll leave this open so people can see your workaround.

**Comment by tstirrat** [comment]
Fixed in #249
